Repository bluewave-labs/verifywise, pull requests merged in 2024-12, with the labels that each got.

#307 enhancements and rewriting compliance tracker page
  Clients/src/App.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/Table/AccordionTable/index.tsx
  Clients/src/presentation/containers/Dashboard/index.css
  Clients/src/presentation/mocks/compliance.data.ts
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
  Clients/src/presentation/pages/ComplianceTracker/index.css
  Clients/src/presentation/pages/ComplianceTracker/index.tsx
  Clients/src/presentation/structures/ComplianceTracker/01-ai-literacy.subcontrol.ts
  Clients/src/presentation/structures/ComplianceTracker/02-transparency-provision.ts
  Clients/src/presentation/structures/ComplianceTracker/03-human-oversight .subcontrol.ts
  Clients/src/presentation/structures/ComplianceTracker/04-corrective-actions.subcontrol.ts
  Clients/src/presentation/structures/ComplianceTracker/05-responsibilities.subcontrol.ts
  Clients/src/presentation/structures/ComplianceTracker/06-obligations-of-deployers.subcontrol.ts
  Clients/src/presentation/structures/ComplianceTracker/07-fundamental-rights.subcontrol.ts
  Clients/src/presentation/structures/ComplianceTracker/08-transparency-obligations-for-providers.subcontrol.ts
  Clients/src/presentation/structures/ComplianceTracker/09-registration.subcontrol.ts
  Clients/src/presentation/structures/ComplianceTracker/10-eu-database-for-high-risk.subcontrol.ts
  Clients/src/presentation/structures/ComplianceTracker/11-post-market-monitor-by-providers.subcontrol.ts
  Clients/src/presentation/structures/ComplianceTracker/12-report-serious-incidents.subcontrol.ts
  Clients/src/presentation/structures/ComplianceTracker/13-general-purpose-ai.subcontrol.ts
  Clients/src/presentation/structures/ComplianceTracker/controls.ts
  Servers/controllers/assessment.ctrl.ts
  Servers/controllers/control.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/controllers/projectRisks.ctrl.ts
  Servers/controllers/projectScope.ctrl.ts
  Servers/controllers/question.ctrl.ts
  Servers/controllers/role.ctrl.ts
  Servers/controllers/subcontrol.ctrl.ts
  Servers/controllers/subtopic.ctrl.ts
  Servers/controllers/topic.ctrl.ts
  Servers/controllers/user.ctrl.ts
  Servers/controllers/vendor.ctrl.ts
  Servers/controllers/vendorRisk.ctrl.ts
  Servers/flags.ts
Labels: frontend

#308 051 Nov 29 Storing Evidence files
  Servers/controllers/question.ctrl.ts
  Servers/models/file.model.ts
  Servers/package-lock.json
  Servers/package.json
  Servers/routes/question.route.ts
  Servers/swagger.yaml
  Servers/utils/fileUpload.utils.ts
  Servers/utils/question.utils.ts
Labels: backend

#310 044 dec 2 authentication pages
  Clients/src/App.tsx
  Clients/src/application/authentication/authSlice.ts
  Clients/src/application/repository/entity.repository.ts
  Clients/src/presentation/components/ProtectedRoute/index.tsx
  Clients/src/presentation/components/Sidebar/index.tsx
  Servers/controllers/user.ctrl.ts
  Servers/endpoints-test/user.http.test.rest
  Servers/mocks/tools/user.mock.db.ts
  Servers/routes/user.route.ts
  Servers/utils/user.utils.ts
Labels: frontend

#323 053 Dec 6: Updated the Mock data
  Servers/controllers/control.ctrl.ts
  Servers/controllers/question.ctrl.ts
  Servers/controllers/topic.ctrl.ts
  Servers/driver/autoDriver.driver.ts
  Servers/mocks/assessment.mock.data.ts
  Servers/mocks/control.mock.data.ts
  Servers/mocks/project.mock.data.ts
  Servers/mocks/projectRisks.mock.data.ts
  Servers/mocks/projectScope.mock.data.ts
  Servers/mocks/question.mock.data.ts
  Servers/mocks/subcontrol.mock.data.ts
  Servers/mocks/vendor.mock.data.ts
  Servers/mocks/vendorRisk.mock.data.ts
  Servers/models/control.model.ts
  Servers/models/project.model.ts
  Servers/swagger.yaml
  Servers/utils/question.utils.ts
Labels: backend

#325 Capturing values for controls
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Inputs/Select/index.tsx
  Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/RichTextEditor/index.tsx
Labels: frontend

#328 npm run build runs successfully
  Clients/src/presentation/components/Modals/Controlpane/index.tsx
  Clients/src/presentation/mocks/projects/project-add-new-risk-tab1.data.ts
  Clients/src/presentation/mocks/projects/project-add-new-risk-tab2.data.ts
  Clients/src/presentation/mocks/roles/roles.data.ts
  Clients/src/presentation/mocks/users/users.data.ts
  Clients/src/presentation/pages/ComplianceTracker/index.tsx
  Clients/src/presentation/pages/SettingsPage/Password/index.tsx
  Clients/tsconfig.app.tsbuildinfo
  Clients/tsconfig.node.tsbuildinfo
Labels: bug

#331 Move validateForm and passwordChecks to separate file(validations/formValidation)
  Clients/src/application/validations/formValidation.ts
  Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterUser/index.tsx
  Clients/src/presentation/pages/Authentication/SetNewPassword/index.tsx
Labels: frontend

#333 049 dec 9 iterating assessments store in db
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
  Clients/src/presentation/pages/Assessment/assessments.req.structure.ts
  Clients/src/presentation/structures/AssessmentTracker/accountability-and-governance.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/accuracy-robustness-cybersecurity.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/bias-monitoring-and-mitigation.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/conformity-assessment.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/data-governance.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/environmental-impact.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/explainability.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/human-oversight.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/post-market-monitoring.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/record-keeping.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/risk-management-system.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/technical-documentation.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/transparency-user-information.subtopic.ts
  Servers/controllers/assessment.ctrl.ts
  Servers/controllers/question.ctrl.ts
  Servers/controllers/subtopic.ctrl.ts
  Servers/controllers/topic.ctrl.ts
  Servers/mocks/question.mock.data.ts
  Servers/mocks/tools/question.mock.db.ts
  Servers/mocks/tools/subtopic.mock.db.ts
  Servers/mocks/tools/topic.mock.db.ts
  Servers/models/question.model.ts
  Servers/routes/assessment.route.ts
  Servers/utils/question.utils.ts
Labels: frontend, backend, team work and collaboration

#339 Get Network requests for vendors View is done
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
Labels: frontend

#336 317 iterating compliance store in db
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Inputs/Field/index.tsx
  Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/Table/AccordionTable/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
  Clients/src/presentation/pages/ComplianceTracker/controls.req.structure.ts
  Servers/controllers/assessment.ctrl.ts
  Servers/controllers/control.ctrl.ts
  Servers/controllers/controlCategory.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/controllers/subcontrol.ctrl.ts
  Servers/mocks/controlCategory.mock.data.ts
  Servers/mocks/tools/control.mock.db.ts
  Servers/mocks/tools/controlCategory.mock.db.ts
  Servers/models/controlCategory.model.ts
  Servers/routes/controlCategory.route.ts
  Servers/routes/project.route.ts
  Servers/utils/controlCategory.util.ts
  Servers/utils/subControl.utils.ts
Labels: frontend, backend, team work and collaboration

#337 Feat/002 dec 12 connect register user to backend
  Clients/src/application/constants/apiResponses.ts
  Clients/src/application/hooks/useRegisterUser.tsx
  Clients/src/application/tools/log.engine.ts
  Clients/src/presentation/pages/Authentication/RegisterUser/index.tsx
Labels: frontend

#350 050 dec 13 overflow in compliance tracker
  Clients/src/presentation/components/Inputs/Field/index.css
Labels: bug, frontend

#321 file uploader modalization
  Clients/src/application/redux/slices/fileSlice.ts
  Clients/src/application/redux/store.ts
  Clients/src/presentation/assets/icons/folder-upload.svg
  Clients/src/presentation/components/FileUpload/FileUpload.styles.ts
  Clients/src/presentation/components/FileUpload/eventHandlers.ts
  Clients/src/presentation/components/FileUpload/index.css
  Clients/src/presentation/components/FileUpload/index.tsx
  Clients/src/presentation/components/FileUpload/types.ts
  Clients/src/presentation/components/FileUpload/uppyConfig.ts
  Clients/src/presentation/components/Modals/FileUpload/index.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
Labels: frontend

#352 051 dec 13 assessment tracker modals
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
  Clients/src/presentation/pages/index.tsx
  Clients/src/presentation/themes/v1SingleTheme.ts
  Clients/src/presentation/vw-v2-components/Buttons/index.tsx
  Clients/src/presentation/vw-v2-components/Dialogs/DualButtonModal/index.css
  Clients/src/presentation/vw-v2-components/Dialogs/DualButtonModal/index.tsx
Labels: enhancement, frontend

#354 Confirmation modal for Create new project added
  Clients/src/presentation/components/CreateProjectForm/index.tsx
Labels: enhancement, frontend

#355 Confirmation modal added for the compliance tracker
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
Labels: enhancement, frontend

#356 053 dec 16 settings page polishing
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Servers/controllers/user.ctrl.ts
  Servers/mocks/users.data.ts
  Servers/models/user.model.ts
  Servers/utils/user.utils.ts
Labels: bug, enhancement, frontend

#357 Enhancements on Settings/password tab
  Clients/src/presentation/pages/SettingsPage/Password/index.tsx
Labels: enhancement, frontend

#358 VWTable is implemented
  Clients/src/presentation/pages/index.tsx
  Clients/src/presentation/themes/tables.ts
  Clients/src/presentation/themes/v1SingleTheme.ts
  Clients/src/presentation/vw-v2-components/index.tsx
Labels: enhancement, frontend

#359 Small fix
  Clients/src/presentation/components/Inputs/Select/index.tsx
Labels: bug, frontend

#351 settings backend request
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Servers/routes/user.route.ts
Labels: frontend, backend

#360 055 dec 16 connecting to be
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/containers/Dashboard/index.tsx
  Clients/src/presentation/pages/ProjectView/Overview/index.tsx
Labels: enhancement, frontend, team work and collaboration

#334 32 dec 08 data validation in compliance
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Inputs/Select/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/index.tsx
Labels: frontend

#361 056 Dec 15 Refactor Compliance Tracker Metadata
  Servers/controllers/control.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/controllers/topic.ctrl.ts
  Servers/routes/control.route.ts
  Servers/routes/project.route.ts
Labels: backend

#368 056 dec 17 enhancements
  Clients/src/application/repository/entity.repository.ts
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Inputs/Select/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/index.tsx
  Clients/src/presentation/pages/SettingsPage/Password/index.tsx
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Servers/controllers/control.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/controllers/topic.ctrl.ts
  Servers/routes/control.route.ts
  Servers/routes/project.route.ts
  Servers/routes/user.route.ts
Labels: enhancement, frontend, team work and collaboration

#372 057 dec 23 build errors
  Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
  Clients/tsconfig.app.tsbuildinfo
Labels: bug, frontend

#367 058 Dec 19 Calculate Assessment and Compliance Tracker progress
  Servers/controllers/user.ctrl.ts
  Servers/routes/user.route.ts
  Servers/swagger.yaml
  Servers/utils/user.utils.ts
Labels: backend

#366 Feat/003 dec 18 connect projects overview and project view to api
  Clients/src/application/hooks/useNavigateSearch.tsx
  Clients/src/application/hooks/useProjectData.tsx
  Clients/src/application/repository/entity.repository.ts
  Clients/src/presentation/components/ProjectCard/index.tsx
  Clients/src/presentation/pages/ProjectView/Overview/index.tsx
  Clients/src/presentation/tools/isoDateToString.ts
  Servers/controllers/control.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/controllers/topic.ctrl.ts
  Servers/routes/control.route.ts
  Servers/routes/project.route.ts
Labels: frontend

#365 settings modal logic
  Clients/.env
  Clients/.gitignore
  Clients/package-lock.json
  Clients/package.json
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
Labels: frontend

#375 Resolve conflicts
  Clients/src/presentation/components/IconButton/index.tsx
  Clients/src/presentation/components/Inputs/Select/index.tsx
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
Labels: Conflict

#362 057 Dec 15 Updated the auto-driver
  Servers/driver/autoDriver.driver.ts
  Servers/mocks/control.mock.data.ts
  Servers/models/control.model.ts
Labels: backend

#377 added border-bottom to empty state
  Clients/src/presentation/pages/FileManager/index.tsx
Labels: bug, frontend

#381 Fix assessment active menu and display default value for dropdown
  Clients/src/presentation/components/Sidebar/index.tsx
Labels: frontend

#382 Fixed the pagination of the tale in Teams
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
Labels: frontend
