Repository bluewave-labs/verifywise, pull requests merged in 2024-11, with the labels that each got.

#182 026 Nov 1 Add Swagger for Auditor Feedbacks
  Servers/controllers/auditorFeedback.ctrl.ts
  Servers/swagger.yaml
  Servers/utils/auditorFeedback.util.ts
Labels: backend

#183 027 Nov 1 Add swagger for Compliance Lists
  Servers/controllers/complianceList.ctrl.ts
  Servers/swagger.yaml
  Servers/utils/complianceList.util.ts
Labels: backend

#184 028 Nov 1 Add Swagger for Compliance Tracker
  Servers/controllers/complianceTracker.ctrl.ts
  Servers/swagger.yaml
  Servers/utils/complianceTracker.util.ts
Labels: backend

#186 030 Nov 1 Add Swagger for Overview
  Servers/controllers/overview.ctrl.ts
  Servers/swagger.yaml
  Servers/utils/overview.util.ts
Labels: backend

#189 029 nov 1 vendors fix inconsistencies
  Clients/src/App.tsx
  Clients/src/application/repository/entity.repository.ts
  Clients/src/infrastructure/api/networkServices.ts
  Clients/src/presentation/components/IconButton/index.tsx
  Clients/src/presentation/components/Modals/Basic/index.tsx
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/mocks/risks/risks.data.ts
  Clients/src/presentation/mocks/vendors/vendors.data.ts
  Clients/src/presentation/tools/isoDateToString.ts
  Servers/controllers/vendor.ctrl.ts
  Servers/driver/autoDriver.driver.ts
  Servers/endpoints-test/vendor.test.rest
  Servers/mocks/vendors/vendors.data.ts
  Servers/models/Vendor.ts
  Servers/routes/vendor.route.ts
  Servers/utils/vendor.utils.ts
Labels: frontend

#190 minor redesigns
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
Labels: frontend

#195 032 Nov 4 Add Swagger for Question
  Servers/controllers/question.ctrl.ts
  Servers/swagger.yaml
  Servers/utils/question.util.ts
Labels: backend

#196 033 Nov 5 Add Swagger for Question Evidence
  Servers/swagger.yaml
  Servers/utils/questionEvidence.util.ts
Labels: backend

#197 034 Nov 5 Add Swagger for Requirement
  Servers/controllers/requirement.ctrl.ts
  Servers/swagger.yaml
  Servers/utils/requirement.util.ts
Labels: backend

#208 Removed 'Project name' from Project risk table
  Clients/src/presentation/mocks/projects/project-risks.data.ts
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
Labels: frontend

#209 Changed users field to select
  Clients/src/presentation/components/CreateProjectForm/index.tsx
Labels: frontend

#198 035 Nov 5 Add Swagger for Risk
  Servers/controllers/risk.ctrl.ts
  Servers/swagger.yaml
  Servers/utils/risk.utils.ts
Labels: backend

#211 015 nov 05 modify vendor risks table
  Clients/src/presentation/mocks/projects/project-vendor-risks.data.ts
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
Labels: frontend

#212 Implemented pagination in Project risks & Vendor risks tables
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
Labels: frontend

#214 Table content validation
  Servers/validations/email.valid.ts
  Servers/validations/number.valid.ts
  Servers/validations/password.valid.ts
Labels: backend

#200 036 Nov 5 Add Swagger for Role
  Servers/swagger.yaml
Labels: backend

#201 037 Nov 5 Add Swagger for Section
  Servers/controllers/section.ctrl.ts
  Servers/swagger.yaml
  Servers/utils/section.util.ts
Labels: backend

#206 040 Nov 5 Add Swagger for Vendors
  Servers/controllers/vendor.ctrl.ts
  Servers/driver/autoDriver.driver.ts
  Servers/mocks/vendorRisks/vendorRisks.data.ts
  Servers/swagger.yaml
Labels: backend

#204 038 Nov 5 Add Swagger for Subrequirements
  Servers/controllers/subrequirement.ctrl.ts
  Servers/swagger.yaml
  Servers/utils/subrequirement.util.ts
Labels: backend

#205 039 Nov 5 Add Swagger for Subrequirement Evidences
  Servers/swagger.yaml
  Servers/utils/subrequirementEvidence.util.ts
Labels: backend

#224 type deleted from vendors table
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
Labels: frontend

#228 Removed "Probability" from Project risks table
  Clients/src/presentation/mocks/projects/project-risks.data.ts
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
Labels: frontend

#227 Changed "Project name" to "Risk name" in Add New Risk popup
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
Labels: frontend

#222 031 Nov 1 Add Swagger for Project
  Servers/controllers/project.ctrl.ts
  Servers/swagger.yaml
  Servers/utils/project.utils.ts
Labels: backend

#231 024 nov 08 getting input value compliance
  Clients/src/presentation/components/Inputs/Datepicker/index.tsx
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Inputs/Field/index.tsx
  Clients/src/presentation/components/Inputs/Image/index.tsx
  Clients/src/presentation/components/Inputs/Radio/index.tsx
  Clients/src/presentation/components/Inputs/Select/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/index.tsx
  Clients/src/presentation/components/ProgressBar/index.tsx
  Clients/src/presentation/components/Table/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/index.tsx
Labels: frontend

#232 033 nov 9 models recreation
  Servers/controllers/project.ctrl.ts
  Servers/controllers/question.ctrl.ts
  Servers/controllers/vendorRisk.ctrl.ts
  Servers/driver/autoDriver.driver.ts
  Servers/endpoints-test/assessment.http.test.rest
  Servers/endpoints-test/control.http.test.rest
  Servers/endpoints-test/project.http.test.rest
  Servers/endpoints-test/projectRisk..http.test.rest
  Servers/endpoints-test/projectScope.http.test.rest
  Servers/endpoints-test/question.http.test.rest
  Servers/endpoints-test/role.http.test.rest
  Servers/endpoints-test/subcontrol.http.test.rest
  Servers/endpoints-test/subtopic.http.test.rest
  Servers/endpoints-test/topic.http.test.rest
  Servers/endpoints-test/vendor.test.rest
  Servers/endpoints-test/vendorRisk.http.test.rest
  Servers/index.ts
  Servers/routes/assessment.route.ts
  Servers/routes/control.route.ts
  Servers/routes/project.route.ts
  Servers/routes/projectRisks.route.ts
  Servers/routes/projectScope.route.ts
  Servers/routes/question.route.ts
  Servers/routes/subcontrol.route.ts
  Servers/routes/subtopic.route.ts
  Servers/routes/topic.route.ts
  Servers/routes/vendor.route.ts
  Servers/routes/vendorRisk.route.ts
  Servers/utils/project.utils.ts
Labels: backend

#234 019 nov 10 input value validation for the project
  Clients/src/application/validations/selectValidation.ts
  Clients/src/application/validations/stringValidation.ts
  Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/Inputs/Datepicker/index.tsx
  Clients/src/presentation/components/Inputs/Field/index.css
  Clients/src/presentation/components/Inputs/Field/index.tsx
  Clients/src/presentation/components/Inputs/Select/index.tsx
  Clients/src/presentation/components/Popup/index.tsx
  Clients/src/presentation/components/RiskLevel/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
  Clients/src/presentation/themes/light.ts
Labels: frontend

#238 Implemented Add a new vendor risk popup
  Clients/src/presentation/components/AddNewVendorRiskForm/index.tsx
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
Labels: frontend

#241 Added links
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
Labels: frontend

#233 045 Nov 10 Refactor swagger
  Servers/controllers/assessment.ctrl.ts
  Servers/controllers/control.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/controllers/projectRisks.ctrl.ts
  Servers/controllers/projectScope.ctrl.ts
  Servers/controllers/question.ctrl.ts
  Servers/swagger.yaml
  Servers/utils/assessment.utils.ts
  Servers/utils/control.utils.ts
  Servers/utils/project.utils.ts
  Servers/utils/projectRisk.utils.ts
  Servers/utils/projectScope.utils.ts
  Servers/utils/question.utils.ts
Labels: backend

#242 Implemented validation for Project settings tab
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
Labels: frontend

#243 046 Nov 12 Refactor Swagger
  Servers/controllers/subcontrol.ctrl.ts
  Servers/controllers/topic.ctrl.ts
  Servers/swagger.yaml
  Servers/utils/subControl.utils.ts
  Servers/utils/subtopic.utils.ts
  Servers/utils/topic.utils.ts
Labels: backend

#249 047 Nov 12 Refactor Swagger
  Servers/controllers/vendor.ctrl.ts
  Servers/controllers/vendorRisk.ctrl.ts
  Servers/swagger.yaml
  Servers/utils/vendor.utils.ts
  Servers/utils/vendorRisk.util.ts
Labels: backend

#250 Pagination for vendor list
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/mocks/vendors/vendors.data.ts
  Servers/controllers/vendor.ctrl.ts
  Servers/mocks/vendor.mock.data.ts
Labels: frontend

#251 035 nov 16 vendors table svg
  Clients/src/presentation/components/Inputs/Field/index.tsx
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/mocks/vendors/vendors.data.ts
  Servers/controllers/vendor.ctrl.ts
  Servers/mocks/vendor.mock.data.ts
  Servers/models/vendor.model.ts
Labels: frontend

#252 conflicts resolved
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/mocks/vendors/vendors.data.ts
  Servers/controllers/vendor.ctrl.ts
  Servers/mocks/vendor.mock.data.ts
Labels: bug, Conflict

#258 037 nov 16 assessment tracker view
  Clients/src/App.css
  Clients/src/App.tsx
  Clients/src/presentation/components/RichTextEditor/index.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/index.tsx
  Clients/src/presentation/pages/Assessment/index.tsx
  Clients/src/presentation/structures/AssessmentTracker/Topics.ts
  Clients/src/presentation/structures/AssessmentTracker/risk-management-system.subtopic.ts
Labels: frontend

#259 037 nov 16 assessment tracker view
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
  Clients/src/presentation/structures/AssessmentTracker/Topics.ts
  Clients/src/presentation/structures/AssessmentTracker/accountability-and-governance.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/accuracy-robustness-cybersecurity.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/bias-monitoring-and-mitigation.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/conformity-assessment.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/data-governance.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/environmental-impact.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/explainability.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/human-oversight.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/post-market-monitoring.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/record-keeping.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/technical-documentation.subtopic.ts
  Clients/src/presentation/structures/AssessmentTracker/transparency-user-information.subtopic.ts
Labels: frontend

#262 048 Nov 19 Add Role model
  Servers/controllers/role.ctrl.ts
  Servers/index.ts
  Servers/mocks/role.mock.data.ts
  Servers/mocks/tools/role.mock.db.ts
  Servers/models/role.model.ts
  Servers/routes/role.route.ts
  Servers/swagger.yaml
  Servers/utils/role.utils.ts
Labels: backend

#254 026 nov 10 adding accordion controls
  Clients/src/presentation/components/Modals/Controlpane/index.tsx
  Clients/src/presentation/mocks/compliance.data.ts
  Clients/src/presentation/pages/ComplianceTracker/index.tsx
Labels: frontend

#273 049 Nov 19 Update Auto-Driver
  Servers/controllers/project.ctrl.ts
  Servers/driver/autoDriver.driver.ts
  Servers/mocks/project.mock.data.ts
  Servers/mocks/projectScope.mock.data.ts
  Servers/mocks/vendor.mock.data.ts
  Servers/models/project.model.ts
  Servers/routes/autoDriver.route.ts
  Servers/utils/project.utils.ts
Labels: backend

#274 038 nov 19 getting input values assessment tracker
  Clients/src/App.tsx
  Clients/src/presentation/components/RichTextEditor/index.css
  Clients/src/presentation/components/RichTextEditor/index.tsx
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
  Servers/driver/autoDriver.driver.ts
  Servers/mocks/question.mock.data.ts
  Servers/mocks/subtopic.mock.data.ts
  Servers/mocks/topic.mock.data.ts
  Servers/models/question.model.ts
Labels: bug, frontend, Conflict

#280 Fixed date field name
  Clients/src/presentation/components/AddNewVendorRiskForm/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
Labels: bug

#281 Added styles
  Clients/src/presentation/components/Modals/FileUpload/index.tsx
Labels: frontend

#255 some fixes
  Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/AddNewVendorRiskForm/index.tsx
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/MetricSection/index.tsx
  Clients/src/presentation/components/Modals/FileUpload/index.tsx
  Clients/src/presentation/components/RiskLevel/constants.ts
  Clients/src/presentation/components/RiskLevel/index.tsx
  Clients/src/presentation/components/Table/index.css
  Clients/src/presentation/components/Table/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
Labels: frontend

#282 038 nov 19 getting input values assessment tracker
  Clients/.env
  Clients/env.vars.ts
  Clients/index.html
  Clients/package.json
  Clients/src/application/repository/entity.repository.ts
  Clients/src/infrastructure/api/customAxios.ts
  Clients/src/infrastructure/api/networkServices.ts
  Clients/src/presentation/components/RichTextEditor/index.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/assessments.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/priorities.tsx
  Clients/vite.config.ts
  Servers/index.ts
  Servers/package-lock.json
  Servers/package.json
Labels: frontend

#288 fixed vendor dropdown menu
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
Labels: enhancement

#290 039 nov 24 assessments tracker connect to backend
  Clients/env.vars.ts
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
  Servers/controllers/topic.ctrl.ts
Labels: frontend

#291 039 nov 24 assessments tracker connect to backend
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
Labels: frontend

#292 removed hover effect in team's tab/ other tasks in issue already been done
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
Labels: frontend

#295 user email on dropdown list item is added
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/Inputs/Select/index.tsx
Labels: frontend

#296 background color for hover effect is restored
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/index.tsx
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/components/Popup/index.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
  Clients/src/presentation/pages/Assessment/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Clients/src/presentation/pages/SettingsPage/Password/index.tsx
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
  Clients/src/presentation/themes/v1SingleTheme.ts
Labels: frontend

#294 request to backend for profile tab
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Servers/package-lock.json
  Servers/package.json
  Servers/routes/user.route.ts
Labels: enhancement, backend

#301 025 nov 25 fetch backend data for create new project popup
  Clients/src/application/repository/entity.repository.ts
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/ProjectCard/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
  Servers/controllers/project.ctrl.ts
  Servers/utils/project.utils.ts
Labels: frontend, Minor

#302 getting project by id
  Clients/src/application/repository/entity.repository.ts
  Clients/src/presentation/pages/ProjectView/Overview/index.tsx
  Clients/src/presentation/pages/ProjectView/index.tsx
Labels: frontend, Minor

#303 043 nov 28 enhancements for the performance
  Clients/src/presentation/pages/SettingsPage/Password/index.tsx
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
  Clients/src/presentation/pages/SettingsPage/index.tsx
Labels: frontend

#304 050 Nov 29: Use DB for the API calls instead of mock data
  Servers/controllers/assessment.ctrl.ts
  Servers/controllers/control.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/controllers/projectRisks.ctrl.ts
  Servers/controllers/projectScope.ctrl.ts
  Servers/controllers/question.ctrl.ts
  Servers/controllers/role.ctrl.ts
  Servers/controllers/subcontrol.ctrl.ts
  Servers/controllers/subtopic.ctrl.ts
  Servers/controllers/topic.ctrl.ts
  Servers/controllers/vendor.ctrl.ts
  Servers/controllers/vendorRisk.ctrl.ts
  Servers/mocks/question.mock.data.ts
Labels: backend
