Repository bluewave-labs/verifywise, pull requests merged in 2024-10, with the labels that each got.

#30 006 sep 30 backend modifications
  Servers/database/db.ts
  Servers/dtos/userIn.dto.ts
  Servers/dtos/userOut.dto.ts
  Servers/files/users.json
  Servers/http.test.rest
  Servers/index.ts
  Servers/mocks/users.data.ts
  Servers/models/user.model.ts
  Servers/package-lock.json
  Servers/package.json
  Servers/routes/users.route.ts
  Servers/src/index.ts
  Servers/src/routes/users.route.ts
  Servers/tsconfig.json
Labels: backend

#27 004 sep 25 application layer
  Clients/package-lock.json
  Clients/package.json
  Clients/src/application/authentication/authSlice.ts
  Clients/src/application/authentication/authTransform.ts
  Clients/src/application/redux/store.ts
  Clients/src/application/tools/fileUtil.ts
  Clients/src/application/tools/logger.ts
  Clients/src/application/validations/emailAddress.rule.ts
  Clients/src/application/validations/phoneNumber.rule.ts
  Clients/src/main.tsx
  Clients/src/presentation/tools/uiSlice.ts
Labels: frontend

#26 005 sep 26 UI modifications and fixes
  Clients/src/presentation/components/IconButton/index.tsx
  Clients/src/presentation/components/Sidebar/index.css
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/containers/Dashboard/index.css
  Clients/src/presentation/pages/Vendors/index.tsx
  Clients/src/presentation/themes/dark.ts
  Clients/src/presentation/themes/light.ts
  Servers/.env
Labels: frontend

#32 003 Oct 1 Add Authentication
  Servers/controllers/users.controller.ts
  Servers/index.ts
  Servers/middlewares/auth.middleware.ts
  Servers/package-lock.json
  Servers/package.json
  Servers/routes/users.route.ts
  Servers/types/IUserAuthRequest.ts
  Servers/utils/jwt.utils.ts
  Servers/utils/userStatusCodes.utils.ts
  Servers/utils/users.utils.ts
  package-lock.json
Labels: backend

#33 007 oct 3 UI refactors fixes
  Clients/src/presentation/containers/Dashboard/index.css
  Clients/src/presentation/mocks/complianceTracker/compliance.data.ts
  Clients/src/presentation/mocks/dashboard/create-project.data.ts
  Clients/src/presentation/mocks/dashboard/dashboard.data.ts
  Clients/src/presentation/mocks/dashboard/project.data.ts
  Clients/src/presentation/mocks/projects/project-add-new-risk-tab1.data.ts
  Clients/src/presentation/mocks/projects/project-add-new-risk-tab2.data.ts
  Clients/src/presentation/mocks/projects/project-overview.data.ts
  Clients/src/presentation/mocks/projects/project-risks.data.ts
  Clients/src/presentation/mocks/projects/project-vendor-risks.data.ts
  Clients/src/presentation/pages/Home/index.tsx
  Clients/src/presentation/themes/light.ts
Labels: frontend

#29 First commit on Assessment Page
  Clients/package-lock.json
  Clients/src/presentation/pages/Assessment/index.tsx
Labels: frontend

#34 008 oct 3 backend configs
  Servers/.env
  Servers/controllers/role.ctrl.ts
  Servers/controllers/user.ctrl.ts
  Servers/controllers/users.controller.ts
  Servers/database/db.ts
  Servers/dtos/userIn.dto.ts
  Servers/dtos/userOut.dto.ts
  Servers/endpoints-test/role.http.test.rest
  Servers/endpoints-test/user.http.test.rest
  Servers/http.test.rest
  Servers/index.ts
  Servers/middleware/auth.middleware.ts
  Servers/middlewares/auth.middleware.ts
  Servers/mocks/roles/roles.data.ts
  Servers/mocks/tools/role.mock.db.ts
  Servers/mocks/tools/user.mock.db.ts
  Servers/mocks/users.data.ts
  Servers/mocks/users/users.data.ts
  Servers/models/Role.ts
  Servers/models/User.ts
  Servers/models/user.model.ts
  Servers/nodemon.json
  Servers/package-lock.json
  Servers/package.json
  Servers/routes/role.route.ts
  Servers/routes/user.route.ts
  Servers/routes/users.route.ts
  Servers/tsconfig.json
  Servers/types/IUserAuthRequest.ts
  Servers/utils/jwt.util.ts
  Servers/utils/jwt.utils.ts
  Servers/utils/role.utils.ts
  Servers/utils/statusCode.utils.ts
  Servers/utils/user.utils.ts
  Servers/utils/userStatusCodes.utils.ts
  Servers/utils/users.utils.ts
Labels: backend

#38 003 sep 27 compliance tracker control pane
  Clients/package-lock.json
  Clients/package.json
  Clients/src/App.tsx
  Clients/src/presentation/assets/icons/cloudUpload.svg
  Clients/src/presentation/assets/icons/headingIcone.svg
  Clients/src/presentation/components/Inputs/Datepicker/index.tsx
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Inputs/Field/index.tsx
  Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx
  Clients/src/presentation/components/Modals/Controlpane/index.tsx
  Clients/src/presentation/components/RichTextEditor/index.tsx
  Clients/src/presentation/components/Table/index.css
  Clients/src/presentation/components/Table/index.tsx
  Clients/src/presentation/mocks/compliance.data.ts
  Clients/src/presentation/pages/ComplianceTracker/index.tsx
Labels: frontend

#42 007 oct 3 UI refactors fixes
  Clients/package-lock.json
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx
  Clients/src/presentation/components/Modals/Controlpane/index.tsx
  Clients/src/presentation/components/RichTextEditor/index.tsx
  Clients/src/presentation/components/Table/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/index.tsx
Labels: frontend

#51 009 oct 6 signup signin
  Clients/index.html
  Clients/public/vite.svg
  Clients/src/App.tsx
  Clients/src/presentation/assets/icons/check-outlined.svg
  Clients/src/presentation/assets/icons/email.svg
  Clients/src/presentation/assets/icons/key.svg
  Clients/src/presentation/assets/icons/left-arrow-long.svg
  Clients/src/presentation/assets/icons/lock.svg
  Clients/src/presentation/assets/imgs/background-grid.svg
  Clients/src/presentation/components/Checks/index.tsx
  Clients/src/presentation/components/Inputs/Checkbox/index.tsx
  Clients/src/presentation/pages/Assessment/index.tsx
  Clients/src/presentation/pages/Authentication/ForgotPassword/index.tsx
  Clients/src/presentation/pages/Authentication/Login/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterUser/index.tsx
  Clients/src/presentation/pages/Authentication/ResetPassword/index.tsx
  Clients/src/presentation/pages/Authentication/ResetPasswordContinue/index.tsx
  Clients/src/presentation/pages/Authentication/SetNewPassword/index.tsx
  Clients/src/presentation/pages/Settings/index.tsx
Labels: frontend

#54 Fix bug
  Clients/package-lock.json
  Clients/package.json
  Clients/src/infrastructure/api/api.ts
  Clients/src/infrastructure/api/apiServices.ts
  Clients/src/main.tsx
Labels: bug

#55 Refactoring network services and exception handler
  Clients/src/infrastructure/api/api.ts
  Clients/src/infrastructure/api/apiServices.ts
  Clients/src/infrastructure/api/customAxios.ts
  Clients/src/infrastructure/api/networkServices.ts
  Clients/src/infrastructure/exceptions/apiError.ts
  Clients/src/infrastructure/exceptions/customeException.tsx
Labels: frontend

#59 Control pane bug fix
  Clients/src/presentation/components/Inputs/Datepicker/index.css
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
Labels: bug

#72 Remove back and save buttons in the vendors page
  Clients/src/presentation/components/IconButton/index.tsx
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
Labels: bug, frontend

#73 005 Oct 12 Fix Authentication
  Servers/.example.env
  Servers/controllers/user.ctrl.ts
  Servers/package-lock.json
  Servers/routes/user.route.ts
  Servers/utils/jwt.util.ts
Labels: backend

#74 006 Oct 12 Add VendorRisk model
  Servers/controllers/vendorRisk.ctrl.ts
  Servers/index.ts
  Servers/mocks/tools/vendorRisk.mock.db.ts
  Servers/mocks/vendorRisks/vendorRisks.data.ts
  Servers/models/VendorRisk.ts
  Servers/routes/vendorRisk.route.ts
  Servers/utils/vendorRisk.util.ts
Labels: backend

#75 007 Oct 12 Add Risk model
  Servers/controllers/risk.ctrl.ts
  Servers/index.ts
  Servers/mocks/risks/risks.data.ts
  Servers/mocks/tools/risk.mock.db.ts
  Servers/models/Risk.ts
  Servers/routes/risk.route.ts
  Servers/utils/risk.utils.ts
Labels: backend

#76 removing effects and refactoring styling values
  Clients/src/presentation/components/IconButton/index.tsx
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
  Clients/src/presentation/themes/v1SingleTheme.ts
Labels: enhancement, frontend

#84 003 oct 11 projects view
  Clients/src/App.tsx
  Clients/src/presentation/components/ProjectCard/index.tsx
  Clients/src/presentation/mocks/projects/project-overview.data.ts
  Clients/src/presentation/pages/ProjectView/Overview/index.tsx
  Clients/src/presentation/pages/ProjectView/index.tsx
Labels: frontend

#44 002 sep 29 create project popup
  Clients/package-lock.json
  Clients/package.json
  Clients/src/presentation/assets/icons/calendar.svg
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/Inputs/Datepicker/index.tsx
  Clients/src/presentation/components/Inputs/Field/index.tsx
  Clients/src/presentation/components/Inputs/Select/index.tsx
  Clients/src/presentation/components/Popup/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
Labels: frontend

#86 004 oct 13 removing effects dashboard project pages
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/Inputs/Datepicker/index.css
  Clients/src/presentation/components/Inputs/Datepicker/index.tsx
  Clients/src/presentation/components/Inputs/Field/index.tsx
  Clients/src/presentation/components/Inputs/Select/index.tsx
  Clients/src/presentation/components/Popup/index.tsx
Labels: frontend, Minor

#87 008 Oct 12 Add Vendor model
  Servers/.example.env
  Servers/controllers/user.ctrl.ts
  Servers/controllers/vendor.ctrl.ts
  Servers/index.ts
  Servers/mocks/tools/vendor.mock.db.ts
  Servers/mocks/vendors/vendors.data.ts
  Servers/models/Vendor.ts
  Servers/routes/vendor.route.ts
  Servers/utils/vendor.utils.ts
Labels: backend

#88 009 Oct 12 Add Project model
  Servers/controllers/project.ctrl.ts
  Servers/index.ts
  Servers/mocks/projects/projects.data.ts
  Servers/mocks/tools/project.mock.db.ts
  Servers/models/Project.ts
  Servers/routes/project.route.ts
  Servers/utils/project.utils.ts
Labels: backend

#90 010 Oct 12 Add Compliance Tracker model
  Servers/controllers/complianceTracker.ctrl.ts
  Servers/index.ts
  Servers/mocks/complianceTrackers/complianceTrackers.data.ts
  Servers/mocks/tools/complianceTracker.mock.db.ts
  Servers/models/ComplianceTracker.ts
  Servers/routes/complianceTracker.route.ts
  Servers/utils/complianceTracker.util.ts
Labels: backend

#89 012 oct 13 removing effects authentication pages
  Clients/src/App.tsx
  Clients/src/presentation/components/Alert/index.tsx
  Clients/src/presentation/pages/Authentication/ForgotPassword/index.tsx
  Clients/src/presentation/pages/Authentication/Login/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterUser/index.tsx
  Clients/src/presentation/pages/Authentication/ResetPasswordContinue/index.tsx
  Clients/src/presentation/pages/Authentication/SetNewPassword/index.tsx
  Clients/src/presentation/pages/index.tsx
  Clients/src/presentation/themes/v1SingleTheme.ts
Labels: frontend

#91 011 Oct 12 Add Compliance Tree model
  Servers/controllers/complianceList.ctrl.ts
  Servers/index.ts
  Servers/mocks/complianceLists/complianceLists.data.ts
  Servers/mocks/tools/complianceList.mock.db.ts
  Servers/models/ComplianceList.ts
  Servers/routes/complianceList.route.ts
  Servers/utils/complianceList.util.ts
Labels: backend

#95 012 Oct 12 Add Requirements model
  Servers/controllers/requirement.ctrl.ts
  Servers/index.ts
  Servers/mocks/requirements/requirements.data.ts
  Servers/mocks/tools/requirement.mock.db.ts
  Servers/models/Requirement.ts
  Servers/routes/requirement.route.ts
  Servers/utils/requirement.util.ts
Labels: backend

#96 013 Oct 12 Add Subrequirements model
  Servers/controllers/subrequirement.ctrl.ts
  Servers/index.ts
  Servers/mocks/subrequirements/subrequirements.data.ts
  Servers/mocks/tools/subrequirement.mock.db.ts
  Servers/models/Subrequirement.ts
  Servers/routes/subrequirement.route.ts
  Servers/utils/subrequirement.util.ts
Labels: backend

#97 014 Oct 12 Add Overview model
  Servers/controllers/overview.ctrl.ts
  Servers/index.ts
  Servers/mocks/overviews/overviews.data.ts
  Servers/mocks/tools/overview.mock.db.ts
  Servers/models/Overview.ts
  Servers/routes/overview.route.ts
  Servers/utils/overview.util.ts
Labels: backend

#98 015 Oct 12 Add Evidence model
  Servers/controllers/evidence.ctrl.ts
  Servers/index.ts
  Servers/mocks/evidences/evidences.data.ts
  Servers/mocks/tools/evidence.mock.db.ts
  Servers/models/Evidence.ts
  Servers/routes/evidence.route.ts
  Servers/utils/evidence.util.ts
Labels: backend

#99 016 Oct 15 Add Auditor Feedback Model
  Servers/controllers/auditorFeedback.ctrl.ts
  Servers/index.ts
  Servers/mocks/auditorFeedbacks/auditorFeedbacks.data.ts
  Servers/mocks/tools/auditorFeedback.mock.db.ts
  Servers/models/AuditorFeedback.ts
  Servers/routes/auditorFeedback.route.ts
  Servers/utils/auditorFeedback.util.ts
Labels: backend

#100 017 Oct 15 Add Assessment Tracker Model
  Servers/controllers/assessmentTracker.ctrl.ts
  Servers/index.ts
  Servers/mocks/assessmentTrackers/assessmentTrackers.data.ts
  Servers/mocks/tools/assessmentTracker.mock.db.ts
  Servers/models/AssessmentTracker.ts
  Servers/routes/assessmentTracker.route.ts
  Servers/utils/assessmentTracker.util.ts
Labels: backend

#101 018 Oct 15 Add Section Model
  Servers/controllers/section.ctrl.ts
  Servers/index.ts
  Servers/mocks/sections/sections.data.ts
  Servers/mocks/tools/section.mock.db.ts
  Servers/models/Section.ts
  Servers/routes/section.route.ts
  Servers/utils/section.util.ts
Labels: backend

#102 019 Oct 15 Add Question Model
  Servers/controllers/question.ctrl.ts
  Servers/index.ts
  Servers/mocks/questions/questions.data.ts
  Servers/mocks/tools/question.mock.db.ts
  Servers/models/Question.ts
  Servers/routes/question.route.ts
  Servers/utils/question.util.ts
Labels: backend

#104 capture and log input values in vendors view
  Clients/src/presentation/components/Inputs/Datepicker/index.tsx
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/mocks/vendors.data.ts
  Clients/src/presentation/pages/Vendors/index.tsx
Labels: frontend

#107 Fixed background color for selected item
  Clients/src/presentation/components/Inputs/Datepicker/index.css
  Clients/src/presentation/components/Inputs/Select/index.tsx
Labels: frontend

#92 009 oct 14 profile page team
  Clients/src/App.tsx
  Clients/src/presentation/assets/icons/TrashCan.svg
  Clients/src/presentation/assets/icons/trash-01.svg
  Clients/src/presentation/pages/ComplianceTracker/index.tsx
  Clients/src/presentation/pages/Settings/index.tsx
  Clients/src/presentation/pages/SettingsPage/Password/index.tsx
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
  Clients/src/presentation/pages/SettingsPage/index.tsx
Labels: frontend

#109 flexible string validation check
  Clients/src/application/validations/stringValidation.ts
Labels: frontend

#113 Question evidence model added
  Servers/controllers/questionEvidence.ctrl.ts
  Servers/index.ts
  Servers/mocks/questionEvidence/questionEvidence.data.ts
  Servers/mocks/tools/questionEvidence.mock.db.ts
  Servers/models/QuestionEvidence.ts
  Servers/routes/questionEvidence.route.ts
  Servers/utils/questionEvidence.util.ts
Labels: backend

#110 016 oct 18 refactor authentication input validations
  Clients/src/application/validations/stringValidation.ts
  Clients/src/presentation/components/Inputs/Field/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterUser/index.tsx
  Clients/src/presentation/pages/Authentication/SetNewPassword/index.tsx
Labels: frontend

#118 implemented delete account popup
  Clients/src/presentation/components/Modals/DeleteAccount/index.tsx
  Clients/src/presentation/pages/SettingsPage/Password/index.tsx
Labels: frontend

#120 repository middleware implemented
  Clients/src/application/repository/entity.repository.ts
Labels: frontend

#117 subrequirementEvidence model completed
  Servers/controllers/subrequirementEvidence.ctrl.ts
  Servers/index.ts
  Servers/mocks/subrequirementEvidence/subrequirementEvidence.data.ts
  Servers/mocks/tools/subrequirementEvidence.mock.db.ts
  Servers/models/SubrequirementEvidence.ts
  Servers/routes/subrequirementEvidence.route.ts
  Servers/utils/subrequirementEvidence.util.ts
Labels: backend

#121 New avatar component refactored and created
  Clients/src/presentation/components/Avatar/VWAvatar/index.tsx
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/pages/index.tsx
  Clients/src/presentation/tools/stringToColor.ts
Labels: frontend

#124 021 oct 20 auth pages navigation
  Clients/src/presentation/pages/Authentication/ForgotPassword/index.tsx
  Clients/src/presentation/pages/Authentication/Login/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterUser/index.tsx
  Clients/src/presentation/pages/Authentication/ResetPassword/index.tsx
  Clients/src/presentation/pages/Authentication/ResetPasswordContinue/index.tsx
  Clients/src/presentation/pages/Authentication/SetNewPassword/index.tsx
Labels: frontend

#127 021 Oct 16 Auto-driver Mechanism
  Servers/controllers/autoDriver.ctrl.ts
  Servers/driver/autoDriver.driver.ts
  Servers/index.ts
  Servers/mocks/assessmentTrackers/assessmentTrackers.data.ts
  Servers/mocks/complianceTrackers/complianceTrackers.data.ts
  Servers/mocks/users/users.data.ts
  Servers/mocks/vendors/vendors.data.ts
  Servers/routes/autoDriver.route.ts
  Servers/utils/autoDriver.util.ts
Labels: backend

#123 004 oct 13 project risks view
  Clients/src/presentation/components/Risks/index.tsx
  Clients/src/presentation/components/Table/index.css
  Clients/src/presentation/components/Table/index.tsx
  Clients/src/presentation/mocks/projects/project-risks.data.ts
  Clients/src/presentation/mocks/projects/project-vendor-risks.data.ts
  Clients/src/presentation/pages/ProjectView/Overview/index.tsx
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
  Clients/src/presentation/pages/ProjectView/index.tsx
Labels: frontend

#130 Got input values from create project popup
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/Popup/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
Labels: frontend

#131 022 Oct 21 Auto-driver Mechanism Sub-Branch 1
  Servers/driver/autoDriver.driver.ts
  Servers/mocks/risks/risks.data.ts
  Servers/mocks/vendorRisks/vendorRisks.data.ts
Labels: backend

#132 021 oct 20 auth pages navigation
  Clients/.env
  Clients/src/application/repository/entity.repository.ts
  Clients/src/infrastructure/api/customAxios.ts
  Clients/src/infrastructure/api/networkServices.ts
  Clients/src/presentation/pages/Authentication/Login/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
  Servers/.example.env
  Servers/controllers/user.ctrl.ts
  Servers/index.ts
  Servers/utils/jwt.util.ts
  Servers/utils/user.utils.ts
Labels: backend

#133 023 Oct 21 Auto-driver Mechanism Sub-Branch 2
  Servers/driver/autoDriver.driver.ts
Labels: backend

#134 024 Oct 21 Auto-driver Mechanism Sub-Branch 3
  Servers/driver/autoDriver.driver.ts
  Servers/mocks/auditorFeedbacks/auditorFeedbacks.data.ts
  Servers/mocks/questionEvidence/questionEvidence.data.ts
  Servers/mocks/subrequirementEvidence/subrequirementEvidence.data.ts
Labels: backend

#135 007 oct 20 getting input values dashboard
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Clients/src/presentation/pages/ProjectView/index.tsx
Labels: frontend

#136 Log mechanism in the frontend application layer
  Clients/src/application/tools/log.engine.ts
  Clients/src/application/tools/logger.ts
  Clients/src/presentation/components/Sidebar/index.tsx
Labels: frontend

#144 Fixed style of titles
  Clients/src/presentation/pages/Home/index.tsx
  Clients/src/presentation/pages/Home/styles.ts
Labels: frontend

#157 024 oct 25 state management module
  Clients/src/App.tsx
  Clients/src/application/contexts/VerifyWise.context.ts
  Clients/src/presentation/containers/Dashboard/index.tsx
  Clients/src/presentation/pages/Authentication/Login/index.tsx
Labels: frontend

#143 UI update for team profile section
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
Labels: frontend

#159 008 oct 21 add a new risk popup
  Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/styles.css
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx
  Clients/src/presentation/components/Modals/FileUpload/index.tsx
  Clients/src/presentation/components/Modals/constants.ts
  Clients/src/presentation/components/Popup/index.tsx
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
Labels: frontend

#161 Fixed the width of the blocks
  Clients/src/presentation/components/Risks/index.tsx
Labels: frontend

#164 026 oct 26 network request completion
  Clients/src/application/repository/entity.repository.ts
  Clients/src/application/tools/log.engine.ts
  Clients/src/infrastructure/api/customAxios.ts
  Clients/src/infrastructure/api/networkServices.ts
  Clients/src/presentation/components/Alert/index.tsx
  Clients/src/presentation/pages/Authentication/Login/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
  Servers/controllers/user.ctrl.ts
Labels: frontend, backend, Minor

#165 Font on risks boxes is fixed
  Clients/src/presentation/components/Risks/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
Labels: bug, frontend

#166 Titles removed from Alerts
  Clients/src/presentation/pages/Authentication/Login/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
Labels: frontend

#174 025 Oct 24 Add Swagger for AssessmentTracker
  Servers/.dockerignore
  Servers/controllers/assessmentTracker.ctrl.ts
  Servers/driver/autoDriver.driver.ts
  Servers/index.ts
  Servers/package-lock.json
  Servers/package.json
  Servers/swagger.yaml
  Servers/utils/assessmentTracker.util.ts
Labels: backend
