Repository bluewave-labs/verifywise, pull requests merged in 2025-03, with the labels that each got.

#868 New project view: Overview Tab
  Clients/src/App.tsx
  Clients/src/presentation/components/Cards/ProjectCard/index.tsx
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/Overview/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/Overview/style.ts
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/style.ts
  Clients/src/presentation/pages/ProjectView/index.tsx
Labels: frontend

#866 100 Feb 28: Update the questions endpoint for storing files
  Servers/controllers/question.ctrl.ts
  Servers/routes/question.route.ts
  Servers/utils/question.utils.ts
Labels: backend

#867 #814 new vendor page
  Clients/src/presentation/components/IconButton/index.tsx
  Clients/src/presentation/components/Modals/NewRisk/index.tsx
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/components/Table/RisksTable/index.tsx
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/components/Table/index.css
  Clients/src/presentation/pages/Vendors/index.css
  Clients/src/presentation/pages/Vendors/index.tsx
  Clients/src/presentation/themes/tables.ts
Labels: frontend

#870 Refactored project overview tab
  Clients/src/domain/User.ts
  Clients/src/presentation/components/Cards/DescriptionCard/index.tsx
  Clients/src/presentation/components/Cards/DescriptionCard/style.ts
  Clients/src/presentation/components/Cards/InfoCard/index.tsx
  Clients/src/presentation/components/Cards/InfoCard/style.ts
  Clients/src/presentation/components/Cards/RisksCard/index.tsx
  Clients/src/presentation/components/Cards/RisksCard/style.ts
  Clients/src/presentation/components/Cards/TeamCard/index.tsx
  Clients/src/presentation/components/Cards/TeamCard/style.ts
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/Overview/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/Overview/style.ts
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/index.tsx
  Clients/src/presentation/pages/index.tsx
  Servers/endpoints-test/project.http.test.rest
Labels: frontend

#875 Project risk table
  Clients/src/domain/ProjectRisk.ts
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/ProjectRisks/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
  Clients/src/presentation/themes/tables.ts
  Clients/src/presentation/vw-v2-components/Table/index.tsx
  Clients/src/presentation/vw-v2-components/index.tsx
Labels: frontend

#876 handling undefined values
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
Labels: frontend

#878 Project view, Settings tab added
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/ProjectRisks/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/index.tsx
  Clients/src/presentation/pages/ProjectView/index.tsx
  Clients/src/presentation/vw-v2-components/Table/index.tsx
Labels: frontend

#888 102 Mar 5: Fix delete for Vendors
  .db_initialized
  Servers/utils/vendor.utils.ts
  Servers/utils/vendorRisk.util.ts
  docker-compose.yml
  install.sh
Labels: backend

#889 Deleting project
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
Labels: frontend

#890 Saving/updating project is fixed
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Clients/src/presentation/vw-v2-components/Buttons/index.tsx
Labels: frontend

#877 101 Mar 4: Add route to upload files
  .db_initialized
  .gitignore
  Servers/controllers/file.ctrl.ts
  Servers/controllers/question.ctrl.ts
  Servers/routes/file.route.ts
  Servers/routes/question.route.ts
  Servers/utils/question.utils.ts
  docker-compose.yml
  install.sh
Labels: backend

#894 Small UI details in the Settings
  Clients/src/presentation/pages/SettingsPage/Password/index.tsx
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
  Clients/src/presentation/pages/SettingsPage/index.tsx
  Clients/src/presentation/pages/SettingsPage/style.ts
  Clients/src/presentation/vw-v2-components/Dialogs/DualButtonModal/index.tsx
Labels: frontend

#895 104 Mar 7: Add code to return project id when creating vendors
  Servers/utils/vendor.utils.ts
Labels: backend

#896 Mo 108 mar 6 refactor enhancement
  Clients/src/presentation/pages/SettingsPage/Password/index.tsx
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
  Clients/src/presentation/pages/SettingsPage/index.tsx
Labels: enhancement, frontend

#899 Update Confirmation Dialog - Compliance Tracker Page
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
Labels: frontend

#902 Dashboard, CRUD ops and value handlings, fixed and completed
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/vw-v2-components/Forms/ProjectForm/index.tsx
Labels: enhancement, frontend

#915 Settings/profile tab, complete
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Clients/src/presentation/vw-v2-components/Skeletons/index.tsx
  Clients/src/presentation/vw-v2-components/Toast/index.tsx
Labels: bug, enhancement, frontend

#918 Compliance Tacker
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx
Labels: enhancement, frontend

#924 Password tab completed
  Clients/src/presentation/pages/SettingsPage/Password/index.tsx
  Servers/controllers/user.ctrl.ts
  Servers/routes/user.route.ts
Labels: enhancement, frontend, backend

#893 103 Mar 5: Add code to optionally insert ai generated data when creating project
  Clients/src/presentation/vw-v2-components/Forms/ProjectForm/index.tsx
  Servers/controllers/assessment.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/structures/assessment-tracker/subtopics/01-project-scope.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/02-risk-management-system.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/03-data-governance.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/04-technical-documentation.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/05-record-keeping.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/06-transparency-user-information.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/07-human-oversight.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/08-accuracy-robustness-cybersecurity.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/09-conformity-assessment.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/10-post-market-monitoring.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/11-bias-monitoring-and-mitigation.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/12-accountability-and-governance.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/13-explainability.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/14-environmental-impact.subtopic.ts
  Servers/structures/compliance-tracker/controls/01-ai-literacy.controls.ts
  Servers/structures/compliance-tracker/controls/02-transparency-provision.controls.ts
  Servers/structures/compliance-tracker/controls/03-human-oversight.controls.ts
  Servers/structures/compliance-tracker/controls/04-corrective-actions.controls.ts
  Servers/structures/compliance-tracker/controls/05-responsibilities.control.ts
  Servers/structures/compliance-tracker/controls/06-obligations-of-deployers.control.ts
  Servers/structures/compliance-tracker/controls/07-fundamental-rights.control.ts
  Servers/structures/compliance-tracker/controls/08-transparency-obligations-for-providers.control.ts
  Servers/structures/compliance-tracker/controls/09-registration.control.ts
  Servers/structures/compliance-tracker/controls/10-eu-database-for-high-risk.control.ts
  Servers/structures/compliance-tracker/controls/11-post-market-monitor-by-providers.control.ts
  Servers/structures/compliance-tracker/controls/12-report-serious-incidents.control.ts
  Servers/structures/compliance-tracker/controls/13-general-purpose-ai.control.ts
  Servers/utils/assessment.utils.ts
  Servers/utils/control.utils.ts
  Servers/utils/controlCategory.util.ts
  Servers/utils/question.utils.ts
  Servers/utils/subControl.utils.ts
  Servers/utils/subtopic.utils.ts
  Servers/utils/topic.utils.ts
Labels: backend

#927 10 mar fetch questions in assessment tracker
  .gitignore
  Clients/src/presentation/components/RichTextEditor/index.tsx
  Clients/src/presentation/components/VWQuestion/index.tsx
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/index.tsx
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/questions.tsx
  Clients/src/presentation/vw-v2-components/Inputs/FileUpload/index.tsx
Labels: bug, frontend

#928 Team table looks fixed
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
Labels: enhancement, frontend

#934 Add route to fetch vendors by project id
  Servers/controllers/vendor.ctrl.ts
  Servers/routes/vendor.route.ts
  Servers/utils/vendor.utils.ts
Labels: backend

#939 11 march ecapsulate assessment tracker api calls within hooks
  Clients/src/application/hooks/useAssessmentData.tsx
  Clients/src/application/hooks/useAssessmentProgress.tsx
  Clients/src/application/hooks/useAssessmentSubtopics.tsx
  Clients/src/application/hooks/useAssessmentTopcis.tsx
  Clients/src/domain/Assessment.ts
  Clients/src/domain/Subtopic.ts
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/index.tsx
Labels: frontend

#940 Add file upload time and uploaded by
  SQL_Commands.sql
  Servers/controllers/control.ctrl.ts
  Servers/controllers/file.ctrl.ts
  Servers/controllers/subcontrol.ctrl.ts
  Servers/models/file.model.ts
  Servers/utils/fileUpload.utils.ts
  Servers/utils/subControl.utils.ts
Labels: backend

#941 Copy SQL file to /database after build
  Servers/package-lock.json
  Servers/package.json
  Servers/scripts/copyFiles.js
Labels: backend

#942 Changing root dir welcome message
  Servers/index.ts
Labels: backend

#943 Mo 112 mar 12 modals tabs
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/Modals/NewRisk/index.tsx
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
Labels: enhancement, frontend

#947 Enhancing codebase for the Dashboard
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
Labels: enhancement, frontend

#948 #879 QA/QC - Settings
  Clients/src/presentation/components/Modals/InviteUser/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
Labels: frontend

#950 Add project_id in file uploads
  Servers/Dockerfile
  Servers/SQL_Commands.sql
  Servers/controllers/control.ctrl.ts
  Servers/controllers/file.ctrl.ts
  Servers/controllers/subcontrol.ctrl.ts
  Servers/models/file.model.ts
  Servers/scripts/copyFiles.js
  Servers/utils/fileUpload.utils.ts
  Servers/utils/question.utils.ts
  Servers/utils/subControl.utils.ts
  install.sh
Labels: backend

#956 Update StatCard on Save on subcontrol
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlCategory.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/index.tsx
Labels: frontend

#960 Role update
  Clients/src/application/hooks/useRoles.tsx
  Clients/src/application/validations/formValidation.ts
  Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
Labels: frontend, backend

#961 Mo 114 mar 12 sidebar selector
  Clients/src/App.tsx
  Clients/src/application/contexts/VerifyWise.context.ts
  Clients/src/presentation/containers/Dashboard/index.tsx
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
  Clients/src/presentation/vw-v2-components/Forms/ProjectForm/index.tsx
Labels: bug, frontend

#962 #879 QA/QC - Settings
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
Labels: frontend

#963 Delete user
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
Labels: frontend, backend

#976 Fix deleting User
  Servers/SQL_Commands.sql
  Servers/controllers/project.ctrl.ts
  Servers/driver/autoDriver.driver.ts
  Servers/mocks/control.mock.data.ts
  Servers/mocks/project.mock.data.ts
  Servers/mocks/projectRisks.mock.data.ts
  Servers/mocks/projectsMembers.mock.data.ts
  Servers/mocks/subcontrol.mock.data.ts
  Servers/mocks/vendor.mock.data.ts
  Servers/mocks/vendorRisk.mock.data.ts
  Servers/models/control.model.ts
  Servers/models/project.model.ts
  Servers/models/projectRisk.model.ts
  Servers/models/projectsMembers.model.ts
  Servers/models/subcontrol.model.ts
  Servers/models/vendor.model.ts
  Servers/models/vendorRisk.model.ts
  Servers/utils/project.utils.ts
  Servers/utils/user.utils.ts
Labels: backend

#977 Add route to fetch questions by topic id
  Servers/controllers/question.ctrl.ts
  Servers/routes/question.route.ts
  Servers/utils/question.utils.ts
Labels: backend

#979 Compliance Tracker Update
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
Labels: frontend, backend

#987 UI updates
  Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx
  Clients/src/presentation/components/Modals/InviteUser/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
  Clients/src/presentation/vw-v2-components/Inputs/FileUpload/index.tsx
Labels: frontend

#993 Update fetching vendorrisks by project id
  Servers/controllers/vendorRisk.ctrl.ts
  Servers/utils/vendorRisk.util.ts
Labels: backend

#1005 Fixing mis-calculation for assessments completed
  Servers/controllers/project.ctrl.ts
Labels: frontend, backend

#1006 Fixing surname update
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Servers/controllers/user.ctrl.ts
  Servers/utils/user.utils.ts
Labels: frontend, backend

#1001 Fix project delete bug
  Servers/utils/project.utils.ts
Labels: bug, backend

#1002 Drop existing tables in SQL script for cleanup
  Servers/SQL_Commands.sql
Labels: backend, Minor

#1004 Fix file uploads for compliance tracker
  Servers/controllers/control.ctrl.ts
  Servers/controllers/subcontrol.ctrl.ts
  Servers/routes/control.route.ts
  Servers/utils/control.utils.ts
  Servers/utils/question.utils.ts
  Servers/utils/subControl.utils.ts
Labels: backend

#1011 Forget Password Implementation
  Clients/src/presentation/pages/Authentication/ForgotPassword/index.tsx
  Clients/src/presentation/pages/Authentication/ResetPassword/index.tsx
  Clients/src/presentation/pages/Authentication/SetNewPassword/index.tsx
  Clients/src/presentation/vw-v2-components/Inputs/FileUpload/index.tsx
  Servers/routes/vwmailer.route.ts
Labels: frontend, backend

#1014 Button text change
  Clients/src/presentation/pages/Authentication/ForgotPassword/index.tsx
  Clients/src/presentation/pages/Authentication/ResetPassword/index.tsx
  Clients/src/presentation/pages/Authentication/SetNewPassword/index.tsx
  Clients/src/presentation/vw-v2-components/Inputs/FileUpload/index.tsx
  Servers/routes/vwmailer.route.ts
Labels: frontend

#1010 Add file upload functionality and delete confirmation modal
  Clients/src/application/tools/createUppy.ts
  Clients/src/domain/File.ts
  Clients/src/presentation/components/Button/index.tsx
  Clients/src/presentation/components/UppyDashboard/index.tsx
  Clients/src/presentation/components/VWQuestion/index.tsx
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/questions.tsx
  Clients/src/presentation/vw-v2-components/Inputs/FileUpload/DeleteFileModal.tsx
  Clients/src/presentation/vw-v2-components/Inputs/FileUpload/getStyles.ts
  Clients/src/presentation/vw-v2-components/Inputs/FileUpload/index.tsx
Labels: frontend

#1023 Improve forget password functionality
  Clients/src/presentation/pages/Authentication/ForgotPassword/index.tsx
  Clients/src/presentation/pages/Authentication/SetNewPassword/index.tsx
Labels: frontend

#1025 Small bug fixes
  Servers/SQL_Commands.sql
  Servers/controllers/question.ctrl.ts
Labels: backend

#1028 Handle `null` files
  Servers/utils/question.utils.ts
  Servers/utils/subControl.utils.ts
Labels: bug, backend

#1015 Sequelize ORM and migrations
  Servers/.sequelizerc
  Servers/controllers/control.ctrl.ts
  Servers/controllers/file.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/controllers/projectRisks.ctrl.ts
  Servers/controllers/user.ctrl.ts
  Servers/database/config/config.js
  Servers/database/db.ts
  Servers/database/migrations/20250319225827-initial-setup.js
  Servers/driver/autoDriver.driver.ts
  Servers/index.ts
  Servers/mocks/control.mock.data.ts
  Servers/mocks/vendorRisk.mock.data.ts
  Servers/models/assessment.model.ts
  Servers/models/control.model.ts
  Servers/models/controlCategory.model.ts
  Servers/models/file.model.ts
  Servers/models/project.model.ts
  Servers/models/projectRisk.model.ts
  Servers/models/projectScope.model.ts
  Servers/models/projectsMembers.model.ts
  Servers/models/question.model.ts
  Servers/models/role.model.ts
  Servers/models/subcontrol.model.ts
  Servers/models/subtopic.model.ts
  Servers/models/topic.model.ts
  Servers/models/user.model.ts
  Servers/models/vendor.model.ts
  Servers/models/vendorRisk.model.ts
  Servers/models/vendorsProjects.model.ts
  Servers/package-lock.json
  Servers/package.json
  Servers/tsconfig.json
  Servers/utils/assessment.utils.ts
  Servers/utils/autoDriver.util.ts
  Servers/utils/control.utils.ts
  Servers/utils/controlCategory.util.ts
  Servers/utils/fileUpload.utils.ts
  Servers/utils/project.utils.ts
  Servers/utils/projectRisk.utils.ts
  Servers/utils/projectScope.utils.ts
  Servers/utils/question.utils.ts
  Servers/utils/role.utils.ts
  Servers/utils/subControl.utils.ts
  Servers/utils/subtopic.utils.ts
  Servers/utils/topic.utils.ts
  Servers/utils/user.utils.ts
  Servers/utils/vendor.utils.ts
  Servers/utils/vendorRisk.util.ts
Labels: backend, team work and collaboration

#1017 Added `dev` and `prod`
  .env.dev
  .env.prod
  .gitignore
  Clients/.gitignore
  Clients/Dockerfile.dev
  Clients/vite.config.ts
  Servers/.gitignore
  Servers/Dockerfile.dev
  Servers/package.json
  docker-compose.override.yml
  docker-compose.prod.yml
  docker-compose.yml
  install.sh
Labels: enhancement, frontend, backend

#1029 #1021 Update the title and description text.
  Clients/src/presentation/components/Modals/NewRisk/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
Labels: frontend

#1039 Add migration for `is_demo` false
  Servers/database/migrations/20250325044112-set-is_demo-false.js
  Servers/models/assessment.model.ts
  Servers/models/control.model.ts
  Servers/models/controlCategory.model.ts
  Servers/models/file.model.ts
  Servers/models/project.model.ts
  Servers/models/projectRisk.model.ts
  Servers/models/projectScope.model.ts
  Servers/models/projectsMembers.model.ts
  Servers/models/question.model.ts
  Servers/models/role.model.ts
  Servers/models/subcontrol.model.ts
  Servers/models/subtopic.model.ts
  Servers/models/topic.model.ts
  Servers/models/user.model.ts
  Servers/models/vendor.model.ts
  Servers/models/vendorRisk.model.ts
  Servers/models/vendorsProjects.model.ts
Labels: backend

#1051 refactor: update user existence check in ProtectedRoute component
  Clients/src/presentation/components/ProtectedRoute/index.tsx
Labels: frontend

#1048 Enhance install script to support both 'docker-compose' and 'docker c…
  install.sh
Labels: backend

#1053 Fix project calculations
  Servers/controllers/project.ctrl.ts
  Servers/controllers/user.ctrl.ts
  Servers/models/project.model.ts
  Servers/utils/project.utils.ts
  Servers/utils/user.utils.ts
Labels: backend

#1045 Set a fix version for postgres in compose
  docker-compose.yml
Labels: backend

#1049 Enhance server configuration by changing app.listen()
  Servers/index.ts
Labels: backend

#1056 Sort the data by created at date
  Servers/database/migrations/20250327205650-add-created_at-field.js
  Servers/models/assessment.model.ts
  Servers/models/control.model.ts
  Servers/models/controlCategory.model.ts
  Servers/models/project.model.ts
  Servers/models/projectRisk.model.ts
  Servers/models/projectScope.model.ts
  Servers/models/question.model.ts
  Servers/models/role.model.ts
  Servers/models/subcontrol.model.ts
  Servers/models/subtopic.model.ts
  Servers/models/topic.model.ts
  Servers/models/vendor.model.ts
  Servers/models/vendorRisk.model.ts
  Servers/utils/assessment.utils.ts
  Servers/utils/control.utils.ts
  Servers/utils/controlCategory.util.ts
  Servers/utils/fileUpload.utils.ts
  Servers/utils/project.utils.ts
  Servers/utils/projectRisk.utils.ts
  Servers/utils/projectScope.utils.ts
  Servers/utils/question.utils.ts
  Servers/utils/role.utils.ts
  Servers/utils/subControl.utils.ts
  Servers/utils/subtopic.utils.ts
  Servers/utils/topic.utils.ts
  Servers/utils/user.utils.ts
  Servers/utils/vendor.utils.ts
  Servers/utils/vendorRisk.util.ts
Labels: backend

#1061 Fix response for missing subcontrols
  Servers/controllers/assessment.ctrl.ts
  Servers/controllers/control.ctrl.ts
Labels: bug, backend

#1065 update server configuration constants
  Servers/index.ts
Labels: bug, backend
