Repository bluewave-labs/verifywise, pull requests merged in 2025-10, with the labels that each got.

#2248 Feat: Organization Report Model
  Clients/src/presentation/components/Inputs/Dropdowns/ProjectFilter/ProjectFilterDropdown.tsx
  Clients/src/presentation/components/Reporting/GenerateReport/GenerateReportFrom/index.tsx
  Clients/src/presentation/components/Reporting/GenerateReport/constants.ts
  Clients/src/presentation/components/Reporting/GenerateReport/index.tsx
  Clients/src/presentation/components/Table/ReportTable/TableBody/index.tsx
  Clients/src/presentation/pages/Reporting/GenerateReport/index.tsx
  Clients/src/presentation/pages/Reporting/Reports/constants.ts
  Clients/src/presentation/pages/Reporting/Reports/index.tsx
  Servers/controllers/reporting.ctrl.ts
  Servers/database/migrations/20250925213420-update-enum-file-source.js
  Servers/domain.layer/models/reporting/reporting.model.ts
  Servers/services/markdowns/allReportMarkdown.ts
  Servers/services/markdowns/modelAndRisksMarkdown.ts
  Servers/services/markdowns/policyManagerMarkdown.ts
  Servers/services/markdowns/trainingRegistryMarkdown.ts
  Servers/services/reportService.ts
  Servers/utils/fileUpload.utils.ts
  Servers/utils/modelInventory.utils.ts
  Servers/utils/reporting.utils.ts
Labels: enhancement, frontend, backend

#2258 fixes-in-ai-trust-center
  Clients/src/presentation/pages/AITrustCenter/Subprocessors/index.tsx
Labels: frontend

#2262 Feat: Model Risks Implementation in Reports
  Servers/services/markdowns/modelAndRisksMarkdown.ts
Labels: bug, backend

#2285 Ks 030 oct 01 figma icons 2047
  Clients/src/presentation/assets/icons/formatBold.svg
  Clients/src/presentation/assets/icons/formatItalic.svg
  Clients/src/presentation/assets/icons/formatListBulleted.svg
  Clients/src/presentation/assets/icons/formatListNumbered.svg
  Clients/src/presentation/assets/icons/formatQuote.svg
  Clients/src/presentation/assets/icons/formatUnderlined.svg
  Clients/src/presentation/assets/icons/one.svg
  Clients/src/presentation/assets/icons/three.svg
  Clients/src/presentation/assets/icons/two.svg
  Clients/src/presentation/components/Policies/PolicyDetailsModal.tsx
  Clients/src/presentation/components/RichTextEditor/index.tsx
Labels: enhancement, frontend

#2286 Ks 031 oct 01 email notification 1959
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
  Servers/constants/emailTemplates.ts
  Servers/controllers/project.ctrl.ts
  Servers/controllers/user.ctrl.ts
  Servers/services/notificationService.ts
  Servers/services/projectNotification/projectCreationNotification.ts
  Servers/services/userNotification/userAddedAdminNotification.ts
  Servers/services/userNotification/userAddedEditorNotification.ts
  Servers/services/userNotification/userAddedToProjectNotification.ts
  Servers/templates/member-role-changed-editor-to-admin.mjml
  Servers/templates/policy-due-soon.mjml
  Servers/templates/user-added-project-auditor.mjml
  Servers/templates/user-added-project-reviewer.mjml
Labels: backend

#2287 Fix CRUD bugs
  Servers/utils/validations/aiTrustCentreValidation.utils.ts
  Servers/utils/validations/iso27001Validation.utils.ts
  Servers/utils/validations/iso42001Validation.utils.ts
  Servers/utils/validations/modelInventoryValidation.utils.ts
Labels: bug, backend

#2293 Mo 233 oct 3 fe domain.lay details
  Clients/src/domain/interfaces/i.mitigation.ts
  Clients/src/domain/interfaces/iRiskForm.ts
Labels: enhancement, frontend

#2256 Rb sept 22 slack notification routing
  Clients/env.vars.ts
  Clients/src/application/hooks/useSlackIntegrations.tsx
  Clients/src/application/repository/slack.integration.repository.ts
  Clients/src/presentation/assets/icons/link-external.svg
  Clients/src/presentation/assets/icons/sliders.svg
  Clients/src/presentation/components/Table/FilesBasicTable/FileBasicTable.tsx
  Clients/src/presentation/pages/SettingsPage/Slack/NotificationRoutingModal.tsx
  Clients/src/presentation/pages/SettingsPage/Slack/SlackIntegrations.tsx
  Clients/src/presentation/pages/SettingsPage/Slack/constants.ts
  Clients/src/presentation/pages/SettingsPage/Slack/index.tsx
  Clients/src/presentation/pages/SettingsPage/index.tsx
  Clients/src/vite-env.d.ts
  Servers/controllers/project.ctrl.ts
  Servers/controllers/slackWebhook.ctrl.ts
  Servers/controllers/user.ctrl.ts
  Servers/database/migrations/20250924132625-add-slack-notification-routing.js
  Servers/domain.layer/enums/slack.enum.ts
  Servers/domain.layer/interfaces/i.slackWebhook.ts
  Servers/domain.layer/models/slackNotification/slackWebhook.model.ts
  Servers/routes/slackWebhook.route.ts
  Servers/services/slack/slackNotificationService.ts
  Servers/services/slackNotificationService.ts
  Servers/utils/slackWebhook.utils.ts
Labels: enhancement, frontend, backend

#2300 Mo 235 oct 4 domain.lay interfaces + Evidence
  Clients/src/domain/interfaces/i.breadcrumbs.ts
  Clients/src/presentation/components/Breadcrumbs/PageBreadcrumbs.tsx
  Clients/src/presentation/components/Breadcrumbs/index.tsx
  Clients/src/presentation/components/Breadcrumbs/routeMapping.ts
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/pages/index.tsx
Labels: enhancement, frontend

#2304 feat: Redesign sidebar with 16px icons and menu grouping
  Clients/package-lock.json
  Clients/package.json
  Clients/src/presentation/components/Sidebar/index.tsx
Labels: enhancement, frontend

#2312 Mo 236 oct 6 fixes enhancements
  Clients/src/domain/interfaces/i.button.ts
  Clients/src/domain/interfaces/i.chart.ts
  Clients/src/presentation/components/Button/CustomizableButton/index.tsx
  Clients/src/presentation/components/Button/FilterButton/index.tsx
  Clients/src/presentation/components/ButtonToggle/index.tsx
  Clients/src/presentation/components/Charts/StatusDonutChart.tsx
  Clients/src/presentation/pages/DashboardOverview/IntegratedDashboard.tsx
  Clients/src/presentation/utils/cardEnhancements.ts
  Clients/src/presentation/utils/statusColors.ts
Labels: enhancement, frontend

#2308 Ks 032 oct 02 figma icons 2047
  Clients/src/application/tools/fileDownload.ts
  Clients/src/presentation/assets/icons/visibility-grey.svg
  Clients/src/presentation/assets/icons/visibility-off-grey.svg
  Clients/src/presentation/components/IconButton/index.tsx
  Clients/src/presentation/components/Inputs/Field/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Resources/index.tsx
  Clients/src/presentation/pages/DashboardOverview/index.tsx
  Clients/src/presentation/pages/WatchTower/Loggings/index.tsx
Labels: enhancement, frontend

#2301 Sw 22 oct 4 crud operation test
  Clients/src/application/validations/stringValidation.ts
  Clients/src/domain/interfaces/i.button.ts
  Clients/src/presentation/components/Button/CustomizableButton/index.tsx
  Clients/src/presentation/components/Modals/NewTraining/index.tsx
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Overview/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Resources/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Settings/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Subprocessors/index.tsx
  Clients/src/presentation/pages/TrainingRegistar/index.tsx
  Clients/src/presentation/pages/TrainingRegistar/trainingTable.tsx
  Servers/middleware/validateAITrustCentreVisibility.middleware.ts
  Servers/utils/validations/vendorRiskValidation.utils.ts
  Servers/utils/validations/vendorValidation.utils.ts
Labels: frontend, backend
