Repository bluewave-labs/verifywise, pull requests merged in 2025-04, with the labels that each got.

#1062 Add route to refresh access-token
  .env.dev
  .env.prod
  Servers/controllers/user.ctrl.ts
  Servers/index.ts
  Servers/package-lock.json
  Servers/package.json
  Servers/routes/user.route.ts
  Servers/utils/jwt.util.ts
Labels: enhancement, backend

#1068 Update emun for `ai_risk_classification` in projects
  Servers/database/migrations/20250401032356-update-risk_classification-projects.js
  Servers/mocks/project.mock.data.ts
  Servers/models/project.model.ts
  Servers/utils/project.utils.ts
Labels: backend

#1071 Update enum values for `type_of_high_risk_role` in projects
  Servers/database/migrations/20250402023546-update-type_of_high_risk_role-projects.js
  Servers/mocks/project.mock.data.ts
  Servers/models/project.model.ts
Labels: backend

#1067 fix missing values
  Clients/src/application/hooks/useVendorRisks.tsx
  Clients/src/presentation/components/Table/RisksTable/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
Labels: frontend

#1086 Fix autoDriver Bug
  Servers/database/migrations/20250403200238-update-projectrisks-mapping.js
  Servers/driver/autoDriver.driver.ts
  Servers/models/projectRisk.model.ts
  Servers/utils/fileUpload.utils.ts
Labels: bug, backend

#1081 Fix project delete bug
  Servers/utils/project.utils.ts
Labels: bug, backend

#1076 #1075 bugfix: update answeredAssessments property
  Clients/src/domain/Project.ts
  Clients/src/presentation/components/Cards/ProjectCard/index.tsx
Labels: frontend

#1079 #1077 fix: refresh progress bar immediately when data updates
  Clients/src/application/hooks/useAssessmentProgress.tsx
  Clients/src/presentation/components/VWQuestion/index.tsx
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/index.tsx
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/questions.tsx
Labels: frontend

#1082 Move logout functionality in separate file
  Clients/src/application/hooks/useLogout.ts
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
Labels: enhancement

#1084 Refresh Token after token expired
  Clients/package-lock.json
  Clients/package.json
  Clients/src/App.tsx
  Clients/src/infrastructure/api/customAxios.ts
  Servers/controllers/user.ctrl.ts
Labels: enhancement, frontend, backend, team work and collaboration

#1089 CORS error
  Servers/index.ts
Labels: frontend, backend

#1052 Compliance page improvement for file upload process
  Clients/src/domain/File.ts
  Clients/src/domain/Subcontrol.ts
  Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/UppyDashboard/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/styles.ts
  Clients/src/presentation/vw-v2-components/Inputs/FileUpload/index.tsx
Labels: frontend

#1063 populate file manager page with real data
  .env.dev
  Clients/src/application/hooks/useFetchFiles.ts
  Clients/src/domain/File.ts
  Clients/src/presentation/components/Table/FileTable/FileTable.tsx
  Clients/src/presentation/components/Table/FilesBasicTable/FileBasicTable.tsx
  install.sh
Labels: enhancement

#1125 Mo 117 april 8 qaqc dashbaord
  Clients/src/presentation/components/Cards/ProjectCard/index.tsx
  Clients/src/presentation/components/Cards/ProjectCard/style.ts
  Servers/controllers/project.ctrl.ts
Labels: frontend, backend

#1126 Handled console warning for select on Compliance page
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/styles.ts
Labels: bug

#1117 #1083 Update risk severity values to align with backend
  Clients/src/domain/ProjectRisk.ts
  Clients/src/domain/VendorRisk.ts
  Clients/src/presentation/components/AddNewRiskForm/projectRiskValue.ts
  Clients/src/presentation/components/Modals/NewRisk/index.tsx
  Clients/src/presentation/components/RiskLevel/constants.ts
  Clients/src/presentation/components/RiskLevel/riskValues.ts
Labels: frontend

#1118 Add support for multiple projects in vendors
  Servers/utils/vendor.utils.ts
Labels: enhancement, backend

#1139 Update frontend configuration and implement CORS origin parsing utility
  .env.dev
  Servers/index.ts
  Servers/utils/parseOrigins.ts
Labels: backend

#1149 Fix file errors
  Clients/src/application/hooks/useGeneratedReports.tsx
  Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/FileUpload/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/index.tsx
Labels: frontend

#1159 Fix email invitation
  Servers/routes/vwmailer.route.ts
  Servers/services/emailService.ts
Labels: bug, backend

#1158 Fix delete user functionality
  Servers/database/migrations/20250411224109-allow-null-values-for-project-owner.js
Labels: bug, backend

#1157 Optimize projects loading in homepage
  Servers/controllers/project.ctrl.ts
  Servers/database/db.ts
  Servers/utils/project.utils.ts
Labels: bug, enhancement, backend

#1156 update refresh token cookie path for improved routing
  Servers/controllers/user.ctrl.ts
Labels: backend

#1161 Improvements and Encapsulations
  Clients/src/App.tsx
  Clients/src/application/config/routes.tsx
  Clients/src/application/interfaces/appStates.ts
  Clients/src/presentation/components/Cards/StatsCard/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/index.tsx
Labels: bug, enhancement, frontend

#1163 Sam 13 apr fix linter errors 2
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/components/RadioGroup/index.tsx
  Clients/src/presentation/components/Reporting/GenerateReport/index.tsx
  Clients/src/presentation/components/RiskLevel/index.tsx
  Clients/src/presentation/components/Table/FileTable/data.ts
  Clients/src/presentation/components/Table/ReportTable/TableBody/index.tsx
  Clients/src/presentation/components/Table/index.tsx
Labels: frontend

#1167 Sam 13 apr fix linter errors part 3
  Clients/src/presentation/pages/Authentication/ResetPassword/index.tsx
  Clients/src/presentation/pages/PageNotFound/index.tsx
  Clients/src/presentation/pages/ProjectView/Overview/index.tsx
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
Labels: frontend

#1168 Mo 120 april 13 enhancing files
  Clients/src/application/hooks/useFetchProjects.ts
  Clients/src/application/interfaces/appStates.ts
  Clients/src/application/interfaces/iprogress.ts
  Clients/src/application/tools/log.engine.ts
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
Labels: enhancement, frontend

#1169 Send role while registering the user
  Clients/src/application/hooks/useRegisterUser.tsx
  Clients/src/presentation/pages/Authentication/RegisterUser/index.tsx
Labels: bug

#1182 Mo 121 april fix build erros
  Clients/src/application/hooks/useRegisterUser.tsx
  Clients/src/application/interfaces/appStates.ts
  Clients/src/application/tools/log.engine.ts
  Clients/src/presentation/components/Modals/NewRisk/index.tsx
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/containers/Dashboard/index.tsx
  Clients/src/presentation/pages/Authentication/Login/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterUser/index.tsx
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
  Clients/tsconfig.app.tsbuildinfo
  Clients/vite.config.ts
Labels: bug, frontend

#1185 Adapt the app for production environment
  .env.dev
  Clients/Dockerfile
  Clients/env.vars.ts
Labels: frontend

#1190 Update project's last updated date
  Servers/controllers/control.ctrl.ts
  Servers/controllers/question.ctrl.ts
  Servers/utils/project.utils.ts
  Servers/utils/projectRisk.utils.ts
  Servers/utils/vendor.utils.ts
Labels: bug, backend

#1191 HTML DOM Nesting issue
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx
Labels: bug

#1195 Add github workflow to check build app for develop and master branches
  .github/workflows/frontend-checks.yml
Labels: enhancement

#1196 Add source for file uploads
  Servers/controllers/control.ctrl.ts
  Servers/controllers/file.ctrl.ts
  Servers/database/migrations/20250415212552-add-file-upload-source.js
  Servers/models/file.model.ts
  Servers/utils/fileUpload.utils.ts
  Servers/utils/question.utils.ts
  Servers/utils/subControl.utils.ts
Labels: backend, team work and collaboration

#1204 Access token expired Implementation
  Clients/src/infrastructure/api/customAxios.ts
Labels: frontend

#1205 Error handling while saving the control form Compliance page
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx
Labels: frontend

#1206 #1104 multiple projects in vendors
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
Labels: frontend

#1209 Fix response for getting vendor by project id
  Servers/controllers/vendor.ctrl.ts
  Servers/utils/vendor.utils.ts
Labels: bug, backend

#1214 Update enum for `review_status` for vendors
  Servers/database/migrations/20250418151414-update-vendors-review_status.js
  Servers/mocks/vendor.mock.data.ts
  Servers/models/vendor.model.ts
Labels: backend

#1215 Add `status` for questions' answer
  Servers/controllers/question.ctrl.ts
  Servers/database/migrations/20250418170914-add-status-for-questions.js
  Servers/models/question.model.ts
  Servers/utils/question.utils.ts
Labels: backend

#1216 Update PUT endpoint to filter empty values
  Servers/utils/control.utils.ts
  Servers/utils/controlCategory.util.ts
  Servers/utils/project.utils.ts
  Servers/utils/projectRisk.utils.ts
  Servers/utils/projectScope.utils.ts
  Servers/utils/role.utils.ts
  Servers/utils/subControl.utils.ts
  Servers/utils/subtopic.utils.ts
  Servers/utils/topic.utils.ts
  Servers/utils/user.utils.ts
  Servers/utils/vendor.utils.ts
  Servers/utils/vendorRisk.util.ts
Labels: backend

#1218 Mo 123 apr 19 fe enhancements
  Clients/src/application/tools/log.engine.ts
  Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
  Clients/src/presentation/pages/Home/1.0Home/style.ts
Labels: enhancement, frontend

#1228 Enhance cookie security settings in loginUser function
  Servers/controllers/user.ctrl.ts
  Servers/database/config/config.js
Labels: backend

#1231 Change Review status dropdown selector in vendor modal
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
Labels: frontend

#1238 Enhance SEO and social media integration in index.html
  Clients/index.html
  Clients/public/social-card.jpgjpg
Labels: frontend

#1241 Sam 25 apr fix social card ext
  Clients/index.html
  Clients/public/social-card.jpg
Labels: frontend

#1229 fix: Update risk data after a vendor is deleted
  Clients/src/application/hooks/useVendorRisks.tsx
  Clients/src/presentation/components/Table/RisksTable/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
Labels: frontend
