Repository bluewave-labs/verifywise, pull requests merged in 2025-06, with the labels that each got.

#1503 Fix invitation link
  Clients/src/presentation/components/Alert/AlertBody.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
Labels: frontend

#1507 #1421 Modify Vendor risks section
  Clients/src/presentation/components/Inputs/Field/index.tsx
  Clients/src/presentation/components/Modals/NewRisk/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
  Servers/database/migrations/20250529151332-remove-impact-from-vendorRisks.js
  Servers/driver/autoDriver.driver.ts
  Servers/models/vendorRisk.model.ts
  Servers/services/markdowns/vendorAndRisksMarkdown.ts
  Servers/utils/vendorRisk.util.ts
Labels: frontend, backend

#1512 Mo 143 june 2 binding org
  Clients/src/application/repository/organization.repository.ts
  Clients/src/presentation/pages/SettingsPage/Organization/index.tsx
  Servers/controllers/organization.ctrl.ts
  Servers/database/db.ts
  Servers/utils/organization.util.ts
Labels: frontend

#1499 Fix "Generate report" disable
  .DS_Store
  BiasAndFairnessServers/.DS_Store
  BiasAndFairnessServers/src/__pycache__/app.cpython-39.pyc
  BiasAndFairnessServers/src/controllers/__pycache__/bias_and_fairness.cpython-39.pyc
  BiasAndFairnessServers/src/crud/__pycache__/bias_and_fairness.cpython-39.pyc
  BiasAndFairnessServers/src/database/__pycache__/config.cpython-39.pyc
  BiasAndFairnessServers/src/database/__pycache__/db.cpython-39.pyc
  BiasAndFairnessServers/src/database/migrations/__pycache__/env.cpython-39.pyc
  BiasAndFairnessServers/src/database/migrations/versions/__pycache__/3c77b926911a_create_table_for_metrics.cpython-39.pyc
  BiasAndFairnessServers/src/database/migrations/versions/__pycache__/7e483c3a8e0c_add_target_and_sensitive_column_in_.cpython-39.pyc
  BiasAndFairnessServers/src/database/migrations/versions/__pycache__/8d57f06f93c2_create_table_for_bias_and_fairness_files.cpython-39.pyc
  BiasAndFairnessServers/src/routers/__pycache__/bias_and_fairness.cpython-39.pyc
  BiasAndFairnessServers/src/utils/__pycache__/run_bias_and_fairness_check.cpython-39.pyc
  Clients/src/application/hooks/useProjects.ts
  Clients/src/presentation/components/Reporting/GenerateReport/GenerateReportFrom/index.tsx
  Clients/src/presentation/pages/FileManager/index.tsx
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Clients/src/presentation/pages/Reporting/GenerateReport/index.tsx
Labels: frontend

#1533 Remove is authorized user from gererate reports
  Servers/controllers/reporting.ctrl.ts
Labels: backend

#1543 Implementation only working for the very first Admin user!
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
Labels: frontend

#1547 Fix: All Reports Shown in Generated Reports Tab
  Servers/utils/reporting.utils.ts
Labels: backend

#1551 Fix .utils files are inconsistency
  Servers/controllers/controlCategory.ctrl.ts
  Servers/controllers/organization.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/controllers/user.ctrl.ts
  Servers/controllers/vendorRisk.ctrl.ts
  Servers/driver/autoDriver.driver.ts
  Servers/index.ts
  Servers/middleware/auth.middleware.ts
  Servers/routes/vwmailer.route.ts
  Servers/services/markdowns/vendorAndRisksMarkdown.ts
  Servers/utils/autoDriver.utils.ts
  Servers/utils/controlCategory.utils.ts
  Servers/utils/jwt.utils.ts
  Servers/utils/organization.utils.ts
  Servers/utils/parseOrigins.utils.ts
  Servers/utils/vendor.utils.ts
  Servers/utils/vendorRisk.utils.ts
Labels: backend

#1552 Fix invitation link
  Clients/src/presentation/components/Alert/AlertBody.tsx
  Servers/config/constants.js
  Servers/index.ts
  Servers/routes/vwmailer.route.ts
Labels: frontend, backend

#1509 Bias and Fairness Backend
  .env.dev
  .github/workflows/docker-image.yml
  .gitignore
  BiasAndFairnessServers/.DS_Store
  BiasAndFairnessServers/.gitignore
  BiasAndFairnessServers/Dockerfile
  BiasAndFairnessServers/Dockerfile.dev
  BiasAndFairnessServers/src/__init__.py
  BiasAndFairnessServers/src/__pycache__/app.cpython-39.pyc
  BiasAndFairnessServers/src/alembic.ini
  BiasAndFairnessServers/src/app.py
  BiasAndFairnessServers/src/controllers/__pycache__/bias_and_fairness.cpython-39.pyc
  BiasAndFairnessServers/src/controllers/bias_and_fairness.py
  BiasAndFairnessServers/src/crud/__pycache__/bias_and_fairness.cpython-39.pyc
  BiasAndFairnessServers/src/crud/bias_and_fairness.py
  BiasAndFairnessServers/src/database/__pycache__/config.cpython-39.pyc
  BiasAndFairnessServers/src/database/__pycache__/db.cpython-39.pyc
  BiasAndFairnessServers/src/database/config.py
  BiasAndFairnessServers/src/database/db.py
  BiasAndFairnessServers/src/database/migrations/README
  BiasAndFairnessServers/src/database/migrations/__pycache__/env.cpython-39.pyc
  BiasAndFairnessServers/src/database/migrations/env.py
  BiasAndFairnessServers/src/database/migrations/script.py.mako
  BiasAndFairnessServers/src/database/migrations/versions/3c77b926911a_create_table_for_metrics.py
  BiasAndFairnessServers/src/database/migrations/versions/7e483c3a8e0c_add_target_and_sensitive_column_in_.py
  BiasAndFairnessServers/src/database/migrations/versions/8d57f06f93c2_create_table_for_bias_and_fairness_files.py
  BiasAndFairnessServers/src/database/migrations/versions/__pycache__/3c77b926911a_create_table_for_metrics.cpython-39.pyc
  BiasAndFairnessServers/src/database/migrations/versions/__pycache__/7e483c3a8e0c_add_target_and_sensitive_column_in_.cpython-39.pyc
  BiasAndFairnessServers/src/database/migrations/versions/__pycache__/8d57f06f93c2_create_table_for_bias_and_fairness_files.cpython-39.pyc
  BiasAndFairnessServers/src/models/FairnessRun.py
  BiasAndFairnessServers/src/models/ModelData.py
  BiasAndFairnessServers/src/models/ModelFile.py
  BiasAndFairnessServers/src/requirements.txt
  BiasAndFairnessServers/src/routers/__pycache__/bias_and_fairness.cpython-39.pyc
  BiasAndFairnessServers/src/routers/bias_and_fairness.py
  BiasAndFairnessServers/src/utils/__pycache__/run_bias_and_fairness_check.cpython-39.pyc
  BiasAndFairnessServers/src/utils/run_bias_and_fairness_check.py
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Servers/.dockerignore
  Servers/index.ts
  Servers/package-lock.json
  Servers/package.json
  Servers/routes/biasAndFairnessRoutes.route.ts
  docker-compose.override.yml
  docker-compose.prod.yml
  docker-compose.yml
Labels: backend

#1559 Change .env.dev to fit invitation link logic
  .env.dev
  .gitignore
Labels: backend

#1560 Add feedback and Discord link to sidebar
  Clients/src/presentation/assets/icons/discord.svg
  Clients/src/presentation/assets/icons/feedback.svg
  Clients/src/presentation/components/Sidebar/index.tsx
Labels: frontend

#1544 Fix: Project Framework ID from FE to BE
  Clients/src/application/tools/fileDownload.ts
  Clients/src/presentation/components/Reporting/GenerateReport/GenerateReportFrom/index.tsx
  Clients/src/presentation/components/Reporting/GenerateReport/index.tsx
  Servers/controllers/reporting.ctrl.ts
  Servers/routes/reporting.route.ts
  Servers/services/markdowns/allReportMarkdown.ts
  Servers/services/reportService.ts
Labels: frontend, backend

#1566 Fix project owner issue
  Servers/controllers/autoDriver.ctrl.ts
  Servers/driver/autoDriver.driver.ts
  Servers/scripts/resetDatabase.ts
  Servers/utils/files/getUserFilesMetaData.utils.ts
Labels: bug, backend

#1582 Fix: Fix in ISO42001 Chart
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/Overview/index.tsx
Labels: frontend

#1574 Error in Deleting the Project Risks
  Servers/utils/projectRisk.utils.ts
Labels: bug, backend

#1580 Fix: Vendor and Vendor Risk Table
  Servers/services/markdowns/vendorAndRisksMarkdown.ts
Labels: backend

#1585 Feat: Subheading in EU-AI Framework
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
Labels: frontend

#1608 Feat: Company name in reports
  Servers/controllers/reporting.ctrl.ts
  Servers/services/markdowns/allReportMarkdown.ts
  Servers/services/markdowns/annexesMarkdown.ts
  Servers/services/markdowns/assessmentTrackerMarkdown.ts
  Servers/services/markdowns/complianceMarkdown.ts
  Servers/services/markdowns/projectRiskMarkdown.ts
  Servers/services/markdowns/vendorAndRisksMarkdown.ts
  Servers/services/reportService.ts
Labels: backend

#1590 Filter evidence files (re-opened)
  Clients/src/presentation/components/Reporting/GenerateReport/index.tsx
  Servers/controllers/file.ctrl.ts
  Servers/controllers/reporting.ctrl.ts
  Servers/database/migrations/20250606193526-add ISO report enums.js
  Servers/middleware/auth.middleware.ts
  Servers/models/file.model.ts
  Servers/models/reporting.model.ts
  Servers/services/markdowns/allReportMarkdown.ts
  Servers/services/markdowns/complianceMarkdown.ts
  Servers/services/reportService.ts
  Servers/types/express.d.ts
  Servers/utils/fileUpload.utils.ts
  Servers/utils/files/getUserFilesMetaData.utils.ts
  Servers/utils/reporting.utils.ts
Labels: backend

#1616 Fix: All reports generated (Clauses and annexes)
  Servers/utils/reporting.utils.ts
Labels: backend

#1628 Mo 149 jun 10 duration type
  Clients/src/presentation/components/Modals/NewTraining/index.tsx
  Clients/src/presentation/pages/TrainingRegistar/index.tsx
  Clients/src/presentation/pages/TrainingRegistar/trainingTable.tsx
  Servers/database/migrations/20250602134847-TrainingRegistar.js
  Servers/models/trainingRegistar.model.ts
Labels: enhancement, frontend, backend

#1627 Fix: Email Validation in Invitation
  Clients/src/presentation/components/Modals/InviteUser/index.tsx
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
Labels: frontend

#1629 Project Risk Modal
  Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
Labels: frontend

#1633 Mo 151 jun 11 fix max height risk modal
  Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/Popup/index.tsx
Labels: enhancement, frontend

#1635 Merging develop into master: June 11th 2025
  .env.prod
  .github/workflows/docker-image.yml
  Clients/env.vars.ts
  Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/Modals/NewTraining/index.tsx
  Clients/src/presentation/components/Popup/index.tsx
Labels: enhancement, Main

#1659 Fix: Installation MD
  INSTALLATION.md
  README.md
Labels: documentation

#1660 Feat: Curl and Error Handling in install.sh
  install.sh
Labels: enhancement

#1663 Fix SSL error in prod
  .env.prod
  BiasAndFairnessServers/src/requirements.txt
  Servers/database/config/config.js
Labels: backend

#1662 Change Log in page phrase to "Click on Sign in button directly to continue"
  Clients/src/presentation/pages/Authentication/Login/index.tsx
Labels: frontend

#1666 Tooltips edited
  Clients/src/presentation/components/Cards/ProjectCard/index.tsx
  Clients/src/presentation/components/Helpers/Guider/index.tsx
  Clients/src/presentation/components/RichTextEditor/index.tsx
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/components/Table/RisksTable/index.tsx
  Clients/src/presentation/components/VWQuestion/index.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/AssessmentQuestions/AssessmentQuestions.tsx
  Clients/src/presentation/pages/FairnessDashboard/FairnessResultsPage.tsx
Labels: enhancement, frontend

#1668 Feat: Max File Size Upload UI
  Clients/src/presentation/pages/FairnessDashboard/FairnessDashboard.tsx
Labels: frontend

#1679 Completely automating the application run
  .gitignore
  start.sh
Labels: backend

#1689 Change framework chip to button
  Clients/src/presentation/components/Cards/ProjectCard/index.tsx
  Clients/src/presentation/components/Cards/ProjectCard/style.ts
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/index.tsx
Labels: frontend

#1696 Mo 154 jun 24 removing console.logs
  Clients/src/application/hooks/useProjectData.tsx
  Clients/src/application/hooks/useRegisterUser.tsx
  Clients/src/application/repository/annexCategory_iso.repository.ts
  Clients/src/application/repository/annex_struct_iso.repository.ts
  Clients/src/application/repository/entity.repository.ts
  Clients/src/application/repository/organization.repository.ts
  Clients/src/infrastructure/api/networkServices.ts
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/AddNewVendorRiskForm/index.tsx
  Clients/src/presentation/components/Cards/SmallStatsCard/index.tsx
  Clients/src/presentation/components/Drawer/ClauseDrawerDialog/index.tsx
  Clients/src/presentation/components/IconButton/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/index.tsx
  Clients/src/presentation/components/ProtectedRoute/index.tsx
  Clients/src/presentation/components/VWQuestion/index.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/AssessmentQuestions/AssessmentQuestions.tsx
  Clients/src/presentation/pages/Authentication/Login/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterUser/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
  Clients/src/presentation/pages/ISO/Clause/index.tsx
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
  Clients/src/presentation/pages/ProjectView/index.tsx
  Servers/scripts/resetDatabase.ts
Labels: frontend, backend

#1703 More User class dependencies including user update is added
  Servers/controllers/user.ctrl.ts
  Servers/domain.layer/models/user/user.model.ts
Labels: backend

#1704 Feat: Insert MIT AI Risk 1st part
  Clients/src/presentation/assets/MITAIRISKDB.json
  Clients/src/presentation/components/AddNewRiskMITForm/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/ProjectRisks/index.tsx
Labels: enhancement

#1714 Mo 157 jun 28 class based project
  Servers/controllers/eu.ctrl.ts
  Servers/controllers/iso42001.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/domain.layer/enums/ai-risk-classification.enum.ts
  Servers/domain.layer/enums/high-risk-role.enum.ts
  Servers/domain.layer/interfaces/i.project.ts
  Servers/domain.layer/interfaces/i.projectFramework.ts
  Servers/domain.layer/models/project/project.mock.data.ts
  Servers/domain.layer/models/project/project.model.ts
  Servers/domain.layer/tests/project.model.spec.ts
  Servers/driver/autoDriver.driver.ts
  Servers/utils/project.utils.ts
Labels: enhancement, backend, Minor

#1715 Add backend checks workflow for pull requests
  .github/workflows/backend-checks.yml
Labels: backend

#1717 Multi-tenant sign-up is added
  Clients/src/application/validations/formValidation.ts
  Clients/src/application/validations/organizationFormValidation.ts
  Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
Labels: enhancement, frontend
