Repository bluewave-labs/verifywise, pull requests merged in 2025-09, with the labels that each got.

#2022 Fix auto drivers
  Servers/driver/autoDriver.driver.ts
Labels: bug, backend

#2023 Update the UI for organizational frameworks
  Clients/src/domain/types/Project.ts
  Clients/src/presentation/pages/Framework/ISO27001/Annex/index.tsx
  Clients/src/presentation/pages/Framework/ISO27001/Clause/index.tsx
  Clients/src/presentation/pages/Framework/ISO42001/Annex/index.tsx
  Clients/src/presentation/pages/Framework/ISO42001/Clause/index.tsx
  Clients/src/presentation/pages/Framework/index.tsx
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
  Clients/src/presentation/vw-v2-components/Forms/ProjectForm/constants.ts
  Clients/src/presentation/vw-v2-components/Forms/ProjectForm/index.tsx
  Servers/driver/autoDriver.driver.ts
  Servers/utils/autoDriver.utils.ts
  Servers/utils/iso27001.utils.ts
  Servers/utils/project.utils.ts
Labels: bug, frontend, backend

#2030 Updated manage frameworks project view UI
  Clients/src/domain/types/Framework.ts
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
Labels: bug, frontend

#2036 Mo 208 sept 4 code quality
  .claude/settings.local.json
  Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.md
  Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.md
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/index.md
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
Labels: enhancement, frontend

#2055 Mo 209 sept 6 bug fix
  Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/ProjectRisks/index.tsx
Labels: bug, enhancement, frontend

#2059 Mo 210 sept 7 code enhancement
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/Breadcrumbs/PageBreadcrumbs.tsx
  Clients/src/presentation/components/Breadcrumbs/index.md
  Clients/src/presentation/components/Breadcrumbs/index.tsx
  Clients/src/presentation/components/Breadcrumbs/routeMapping.ts
  Clients/src/presentation/components/Button/CustomizableButton/index.md
  Clients/src/presentation/components/Button/CustomizableButton/index.tsx
  Clients/src/presentation/components/Button/index.tsx
  Clients/src/presentation/components/Cards/ProjectCard/index.tsx
  Clients/src/presentation/components/Drawer/AnnexDrawerDialog/index.tsx
  Clients/src/presentation/components/Drawer/ClauseDrawerDialog/index.tsx
  Clients/src/presentation/components/Drawer/ISO27001AnnexDrawerDialog/index.tsx
  Clients/src/presentation/components/Drawer/ISO27001ClauseDrawerDialog/index.tsx
  Clients/src/presentation/components/LinkedRisks/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/Modals/InviteUser/index.tsx
  Clients/src/presentation/components/Modals/NewModelInventory/index.tsx
  Clients/src/presentation/components/Modals/NewRisk/index.tsx
  Clients/src/presentation/components/Modals/NewTraining/index.tsx
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/components/Policies/PolicyDetailsModal.tsx
  Clients/src/presentation/components/Reporting/GenerateReport/GenerateReportFrom/index.tsx
  Clients/src/presentation/components/RiskPopup/AuditRiskPopup.tsx
  Clients/src/presentation/components/Table/AuditRiskTable/AuditRiskTableBody.tsx
  Clients/src/presentation/components/Table/ProjectRiskMitigationTable/ProjectRiskMitigationTableBody.tsx
  Clients/src/presentation/pages/AITrustCenter/Overview/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Resources/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Settings/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Subprocessors/index.tsx
  Clients/src/presentation/pages/AITrustCenter/index.tsx
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
  Clients/src/presentation/pages/ModelInventory/index.tsx
  Clients/src/presentation/pages/PolicyDashboard/PoliciesDashboard.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/ProjectRisks/index.tsx
  Clients/src/presentation/pages/Reporting/GenerateReport/index.tsx
  Clients/src/presentation/pages/SettingsPage/Organization/index.tsx
  Clients/src/presentation/pages/SettingsPage/Password/index.tsx
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
  Clients/src/presentation/pages/TrainingRegistar/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
  Clients/src/presentation/pages/index.tsx
  Clients/src/presentation/vw-v2-components/Buttons/index.tsx
  Clients/src/presentation/vw-v2-components/Dialogs/DualButtonModal/index.tsx
  Clients/src/presentation/vw-v2-components/Forms/ProjectForm/index.tsx
  Clients/src/presentation/vw-v2-components/Table/VWProjectRisksTableBody.tsx
  Clients/tsconfig.app.tsbuildinfo
Labels: documentation, enhancement, frontend

#2062 Fix training registry bug
  Servers/scripts/createNewTenant.ts
Labels: bug, backend

#2086 Update status colors in ISO styles for better clarity and consistency
  Clients/src/presentation/pages/ISO/style.ts
Labels: UI/UX Design

#2125 Enable event tracker for OSS
  Clients/src/presentation/components/ProtectedRoute/index.tsx
  Clients/src/presentation/components/Sidebar/index.tsx
Labels: frontend

#2120 Fix: Add missing Training API endpoints to Swagger documentation
  Servers/swagger.yaml
Labels: documentation, enhancement, backend, descriptive/informative

#2146 Mo 219 sept 16 Updating Current Helpers
  Clients/src/presentation/helpers/ai-trust-center-help.html
  Clients/src/presentation/helpers/bias-fairness-help.html
  Clients/src/presentation/helpers/evidences-help.html
  Clients/src/presentation/helpers/policy-manager-help.html
  Clients/src/presentation/helpers/reporting-help.html
  Clients/src/presentation/helpers/training-help.html
  Clients/src/presentation/helpers/vendor-help.html
  Clients/src/presentation/pages/FileManager/index.tsx
  Clients/src/presentation/pages/PolicyDashboard/PoliciesDashboard.tsx
Labels: enhancement, frontend

#2142 Fix SQL Queries
  Servers/utils/eu.utils.ts
  Servers/utils/iso27001.utils.ts
  Servers/utils/iso42001.utils.ts
  Servers/utils/utility.utils.ts
Labels: bug, backend

#2147 Ks 015 sep 16 esc button modal close 2058
  Clients/src/presentation/components/Dialogs/DualButtonModal/index.tsx
  Clients/src/presentation/components/Drawer/HelperDrawer/index.tsx
Labels: enhancement, frontend

#2149 Ks 016 sep 16 figma icons 2047
  Clients/src/presentation/assets/icons/chevron-down-grey.svg
  Clients/src/presentation/assets/icons/chevron-down-white.svg
  Clients/src/presentation/components/Inputs/Dropdowns/ProjectFilter/ProjectFilterDropdown.tsx
  Clients/src/presentation/components/Inputs/Select/Multi/index.tsx
  Clients/src/presentation/components/Inputs/Select/ReviewerSelect/index.tsx
  Clients/src/presentation/components/Inputs/Select/index.css
  Clients/src/presentation/components/Inputs/Select/index.tsx
  Clients/src/presentation/components/StatusDropdown/index.tsx
  Clients/src/presentation/pages/Framework/index.tsx
Labels: frontend, UI/UX Design

#2150 Mo 220 sept 17 completing helpers
  Clients/src/presentation/helpers/event-tracker-help.html
  Clients/src/presentation/helpers/organizational-frameworks-help.html
  Clients/src/presentation/helpers/settings-help.html
  Clients/src/presentation/helpers/task-management-help.html
  Clients/src/presentation/pages/Framework/index.tsx
  Clients/src/presentation/pages/SettingsPage/index.tsx
  Clients/src/presentation/pages/Tasks/index.tsx
  Clients/src/presentation/pages/WatchTower/index.tsx
Labels: enhancement, frontend

#2151 When the user registers the user should be logged in automatically (`SAAS`)
  Clients/src/presentation/pages/Authentication/Login/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterMultiTenant/index.tsx
  Clients/src/presentation/pages/SettingsPage/Password/index.tsx
  Servers/controllers/organization.ctrl.ts
  Servers/controllers/user.ctrl.ts
Labels: frontend

#2170 Replace MUI `Delete` icons with custom SVGs
  Clients/src/presentation/assets/icons/TrashCan.svg
  Clients/src/presentation/assets/icons/trash-01.svg
  Clients/src/presentation/assets/icons/trash-02.svg
  Clients/src/presentation/assets/icons/trash-black.svg
  Clients/src/presentation/assets/icons/trash-filled-red.svg
  Clients/src/presentation/assets/icons/trash-filled-white.svg
  Clients/src/presentation/assets/icons/trash-grey.svg
  Clients/src/presentation/components/FileUpload/index.tsx
  Clients/src/presentation/components/Inputs/FileUpload/index.tsx
  Clients/src/presentation/components/Table/FairnessTable/TableBody/index.tsx
  Clients/src/presentation/pages/Framework/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
Labels: enhancement, frontend

#2183 Bug fixes
  Servers/scripts/createNewTenant.ts
Labels: bug, backend

#2179 Ks 020 sep 20 figma icons 2047
  Clients/src/presentation/assets/icons/right-arrow-black.svg
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/Forms/ProjectForm/index.tsx
  Clients/src/presentation/components/Modals/CreateTask/index.tsx
  Clients/src/presentation/components/Modals/NewModelInventory/index.tsx
  Clients/src/presentation/components/Modals/NewModelRisk/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlCategory.tsx
  Clients/src/presentation/pages/Framework/ISO27001/Annex/index.tsx
  Clients/src/presentation/pages/Framework/ISO27001/Clause/index.tsx
  Clients/src/presentation/pages/Framework/ISO42001/Annex/index.tsx
  Clients/src/presentation/pages/Framework/ISO42001/Clause/index.tsx
  Clients/src/presentation/pages/ISO/Annex/index.tsx
  Clients/src/presentation/pages/ISO/Clause/index.tsx
  Clients/src/presentation/pages/ISO/style.ts
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
Labels: enhancement, frontend

#2210 hide slack from settings page
  Clients/src/presentation/pages/SettingsPage/index.tsx
Labels: frontend

#2211 get-model-info-from-model-inventory-json-added-additional-fields
  Clients/src/domain/interfaces/i.modelInventory.ts
  Clients/src/presentation/components/Modals/NewModelInventory/index.tsx
  Clients/src/presentation/components/Modals/NewModelRisk/index.tsx
  Clients/src/presentation/pages/ModelInventory/index.tsx
  Clients/src/presentation/pages/ModelInventory/modelInventoryTable.tsx
  Servers/controllers/modelInventory.ctrl.ts
  Servers/database/migrations/20250923174329-add-fields-in-model-inventory-table.js
  Servers/domain.layer/interfaces/i.modelInventory.ts
  Servers/domain.layer/models/modelInventory/modelInventory.model.ts
  Servers/scripts/createNewTenant.ts
  Servers/utils/modelInventory.utils.ts
Labels: frontend, backend

#2227 Mo 229 sept 26 part 3 FE class based models
  Clients/src/domain/models/Common/aiTrustCenter/AITrustCenterCompanyDescription.model.ts
  Clients/src/domain/models/Common/aiTrustCenter/AITrustCenterComplianceBadges.model.ts
  Clients/src/domain/models/Common/aiTrustCenter/AITrustCenterInfoModel.model.ts
  Clients/src/domain/models/Common/aiTrustCenter/AITrustCenterIntro.model.ts
  Clients/src/domain/models/Common/aiTrustCenter/AITrustCenterResources.model.ts
  Clients/src/domain/models/Common/aiTrustCenter/AITrustCenterSubprocessors.model.ts
  Clients/src/domain/models/Common/aiTrustCenter/AITrustCenterTermsAndContact.model.ts
  Clients/src/domain/models/Common/file/file.model.ts
  Clients/src/domain/models/Common/framework/framework.model.ts
  Clients/src/domain/models/Common/modelInventory/modelInventory.model.ts
  Clients/src/domain/models/Common/modelRisk/modelRisk.model.ts
  Clients/src/domain/models/Common/organization/organization.model.ts
  Clients/src/domain/models/Common/policy/policyManager.model.ts
  Clients/src/domain/models/Common/project/project.model.ts
  Clients/src/domain/models/Common/projectFramework/projectFrameworks.model.ts
  Clients/src/domain/models/Common/projectsMembers/projectsMembers.model.ts
  Clients/src/domain/models/Common/risks/risk.model.ts
  Clients/src/domain/models/Common/role/role.model.ts
  Clients/src/domain/models/Common/subscription/subscription.model.ts
  Clients/src/domain/models/Common/task/task.model.ts
  Clients/src/domain/models/Common/taskAssignee/taskAssignee.model.ts
  Clients/src/domain/models/Common/tier/tier.model.ts
  Clients/src/domain/models/Common/trainingRegistar/trainingRegistar.model.ts
  Clients/src/domain/models/Common/user/user.model.ts
  Clients/src/domain/models/Common/vendor/vendor.model.ts
  Clients/src/domain/models/Common/vendorRisk/vendorRisk.model.ts
  Clients/src/domain/models/Common/vendorsProjects/vendorsProjects.model.ts
  Clients/src/domain/models/EU-AI-Act/assessment/assessment.model.ts
  Clients/src/domain/models/EU-AI-Act/control/control.model.ts
  Clients/src/domain/models/EU-AI-Act/controlCategory/controlCategory.model.ts
  Clients/src/domain/models/EU-AI-Act/projectScope/projectScope.model.ts
  Clients/src/domain/models/EU-AI-Act/question/question.model.ts
  Clients/src/domain/models/EU-AI-Act/subcontrol/subControl.model.ts
  Clients/src/domain/models/EU-AI-Act/subtopic/subtopic.model.ts
  Clients/src/domain/models/EU-AI-Act/topic/topic.model.ts
  Clients/src/domain/models/ISO-42001/annexCategoryISO42001/annexCategoryISO42001.model.ts
  Clients/src/domain/models/ISO-42001/annexCategoryISO42001RIsk/annexCategoryISO42001RIsk.model.ts
  Clients/src/domain/models/ISO-42001/annexCategoryStructISO42001/annexCategoryStructISO42001.model.ts
  Clients/src/domain/models/ISO-42001/annexStructISO42001/annexStructISO42001.model.ts
  Clients/src/domain/models/ISO-42001/clauseStructISO42001/clauseStructISO42001.model.ts
  Clients/src/domain/models/ISO-42001/subClauseISO42001/subClauseISO42001.model.ts
  Clients/src/domain/models/ISO-42001/subClauseISO42001Risk/subClauseISO42001Risk.model.ts
  Clients/src/domain/models/ISO-42001/subClauseStructISO42001/subClauseStructISO42001.model.ts
Labels: enhancement, frontend

#2244 fix query params in clients and control query in server for evidence …
  Clients/src/presentation/components/Table/FilesBasicTable/FileBasicTable.tsx
  Servers/utils/files/getUserFilesMetaData.utils.ts
Labels: frontend, backend

#2246 tooltip-issue-fixes
  Clients/src/presentation/components/VWQuestion/index.tsx
Labels: frontend

#2254 Ks 028 sep 29 vendor not visible 2221
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
Labels: frontend, backend
