Repository bluewave-labs/verifywise, pull requests merged in 2025-01, with the labels that each got.

#383 Removed inputs from Risk control
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/styles.css
Labels: frontend

#407 adding page tour to dashboard/home page
  Clients/package-lock.json
  Clients/package.json
  Clients/src/App.css
  Clients/src/presentation/components/PageTour/index.tsx
  Clients/src/presentation/components/Popup/index.tsx
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/containers/Dashboard/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
Labels: enhancement, frontend

#406 added a modal for sending invitation
  Clients/src/presentation/components/Modals/InviteUser/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
Labels: frontend

#409 004 dec 23 vendor edit
  Clients/src/presentation/components/Modals/Basic/index.tsx
Labels: frontend

#410 058 jan 6 implement project scope
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/assessments.tsx
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Clients/src/presentation/structures/AssessmentTracker/Topics.ts
  Clients/src/presentation/structures/AssessmentTracker/project-scope.subtopic.ts
  Servers/controllers/project.ctrl.ts
  Servers/endpoints-test/project.http.test.rest
  Servers/routes/project.route.ts
Labels: frontend

#411 Users' emails are added on the dropdown as well
  Clients/src/presentation/components/CreateProjectForm/index.tsx
Labels: enhancement, frontend

#413 removed extra columns in file manager
  Clients/src/presentation/pages/FileManager/index.tsx
Labels: enhancement, frontend

#417 Fixed font size
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/Modals/Controlpane/index.tsx
Labels: frontend

#408 added new features to setting page
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
  Clients/src/presentation/vw-v2-components/Dialogs/DualButtonModal/index.tsx
Labels: frontend

#423 060 jan 6 select multiple items
  Clients/src/presentation/pages/index.tsx
  Clients/src/presentation/vw-v2-components/Selects/Multi/index.css
  Clients/src/presentation/vw-v2-components/Selects/Multi/index.tsx
Labels: frontend

#421 059 Dec 30: Add PUT endpoint for Assessment and Compliance Tracker metadata
  Servers/controllers/assessment.ctrl.ts
  Servers/controllers/control.ctrl.ts
  Servers/routes/assessment.route.ts
  Servers/routes/control.route.ts
  Servers/utils/question.utils.ts
Labels: backend

#425 061 jan 9 component documentations
  Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/AddNewVendorRiskForm/index.tsx
  Clients/src/presentation/components/Breadcrumbs/index.tsx
  Clients/src/presentation/components/Charts/BarChart/index.tsx
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/Fallback/index.tsx
Labels: documentation, frontend

#414 Creating a vendor
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
Labels: frontend

#431 060 Jan 9: Use database for API calls
  Servers/flags.ts
Labels: backend

#437 Adding logo click to move to the home page
  Clients/src/presentation/components/Sidebar/index.tsx
Labels: frontend

#442 doc for components
  Clients/src/presentation/components/Inputs/Autocomplete/index.md
  Clients/src/presentation/components/Inputs/Checkbox/index.md
  Clients/src/presentation/components/Inputs/Datepicker/index.md
  Clients/src/presentation/components/Inputs/Dropdowns/index.md
  Clients/src/presentation/components/Inputs/Field/index.md
  Clients/src/presentation/components/Inputs/Image/index.md
  Clients/src/presentation/components/Inputs/Radio/index.md
  Clients/src/presentation/components/Inputs/Select/index.md
  Clients/src/presentation/components/Label/BaseLabel/index.md
Labels: documentation, frontend

#443 061 Jan 9: Documentation for Controllers for Backend
  Servers/documenation/controllers/assessment.md
  Servers/documenation/controllers/autoDriver.md
  Servers/documenation/controllers/control.md
  Servers/documenation/controllers/controlCategory.md
  Servers/documenation/controllers/project.md
  Servers/documenation/controllers/projectRisks.md
  Servers/documenation/controllers/projectScope.md
  Servers/documenation/controllers/question.md
  Servers/documenation/controllers/role.md
  Servers/documenation/controllers/subcontrol.md
  Servers/documenation/controllers/subtopic.md
  Servers/documenation/controllers/topic.md
  Servers/documenation/controllers/user.md
  Servers/documenation/controllers/vendor.md
  Servers/documenation/controllers/vendorRisk.md
Labels: documentation, backend, team work and collaboration

#444 062 Jan 10: Documentation for Database Utility for Backend
  Servers/documentation/database/db.md
Labels: documentation, backend, team work and collaboration

#445 063 Jan 10: Documentation for Auto Driver for Backend
  Servers/documentation/driver/autoDriver.md
Labels: documentation, backend, team work and collaboration

#447 063 jan 10 bug fix
  Clients/src/presentation/vw-v2-components/Selects/Multi/index.tsx
  Servers/controllers/project.ctrl.ts
  Servers/controllers/user.ctrl.ts
  Servers/mocks/tools/user.mock.db.ts
Labels: bug

#448 Feat/004 jan 10 fetch project status
  Clients/src/application/hooks/useProjectData.tsx
  Clients/src/application/hooks/useProjectStatus.tsx
  Clients/src/presentation/components/MetricSection/index.tsx
  Clients/src/presentation/components/ProjectCard/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
Labels: frontend

#449 063 jan 10 bug fix
  Clients/src/application/hooks/useProjectStatus.tsx
  Clients/src/presentation/pages/Home/index.tsx
  Servers/mocks/subtopic.mock.data.ts
  Servers/mocks/topic.mock.data.ts
Labels: bug, frontend, backend

#450 064 jan 12 components docs
  Clients/src/presentation/components/Label/ColoredLabel/index.md
  Clients/src/presentation/components/Label/StatusLabel/index.md
  Clients/src/presentation/components/Link/inedx.md
  Clients/src/presentation/components/MetricSection/index.md
  Clients/src/presentation/components/Modals/Banner/index.md
  Clients/src/presentation/components/Modals/Basic/index.md
  Clients/src/presentation/components/Modals/ComplianceFeedback/index.md
  Clients/src/presentation/components/Modals/Controlpane/index.md
  Clients/src/presentation/components/Modals/Controlpane/index.tsx
  Clients/src/presentation/components/Modals/DeleteAccount/index.md
  Clients/src/presentation/components/Modals/Error/index.md
  Clients/src/presentation/components/Modals/FileUpload/index.md
  Clients/src/presentation/components/Modals/InviteUser/index.md
  Clients/src/presentation/components/Modals/InviteUser/index.tsx
  Clients/src/presentation/components/Modals/NewVendor/index.md
  Clients/src/presentation/components/PageTour/CustomStep/index.md
  Clients/src/presentation/components/PageTour/index.md
  Clients/src/presentation/components/Popup/index.md
  Clients/src/presentation/components/ProgressBar/index.md
  Clients/src/presentation/components/ProjectCard/ProgressBar/index.md
  Clients/src/presentation/components/ProjectCard/index.md
  Clients/src/presentation/components/ProtectedRoute/index.md
  Clients/src/presentation/components/RichTextEditor/index.md
  Clients/src/presentation/components/RiskLevel/index.md
  Clients/src/presentation/components/Risks/index.md
  Clients/src/presentation/components/Search/index.md
  Clients/src/presentation/components/Sidebar/index.md
  Clients/src/presentation/components/Steps/ProgressStepper/index.md
  Clients/src/presentation/components/Steps/StepIcon/index.md
  Clients/src/presentation/components/Table/AccordionTable/index.md
  Clients/src/presentation/components/Table/WithPlaceholder/index.md
  Clients/src/presentation/components/Table/index.md
  Clients/src/presentation/components/TablePagination/index.md
Labels: documentation, frontend

#451 065 jan 12 vw components
  Clients/src/presentation/pages/Home/index.tsx
  Clients/src/presentation/pages/index.tsx
  Clients/src/presentation/vw-v2-components/Skeletons/index.tsx
Labels: enhancement, frontend

#453 Justify project modal textfield height
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/Inputs/Field/index.css
  Clients/src/presentation/components/Inputs/Field/index.tsx
Labels: enhancement

#454 Display projects in grid
  Clients/src/presentation/components/MetricSection/styles.ts
  Clients/src/presentation/components/ProjectCard/styles.ts
  Clients/src/presentation/pages/Home/index.tsx
Labels: enhancement

#456 066 jan 14 db network fix
  Servers/controllers/assessment.ctrl.ts
  Servers/controllers/control.ctrl.ts
  Servers/controllers/controlCategory.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/controllers/projectRisks.ctrl.ts
  Servers/controllers/projectScope.ctrl.ts
  Servers/controllers/question.ctrl.ts
  Servers/controllers/role.ctrl.ts
  Servers/controllers/subcontrol.ctrl.ts
  Servers/controllers/subtopic.ctrl.ts
  Servers/controllers/topic.ctrl.ts
  Servers/controllers/user.ctrl.ts
  Servers/controllers/vendor.ctrl.ts
  Servers/controllers/vendorRisk.ctrl.ts
  Servers/endpoints-test/assessment.http.test.rest
  Servers/flags.ts
Labels: Conflict

#457 066 jan 14 db network fix
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/mocks/vendors/vendors.data.ts
  Clients/src/presentation/pages/Vendors/index.tsx
  Servers/driver/autoDriver.driver.ts
Labels: Conflict

#459 065 Jan 10: Documentation for Mocks and Tools
  Servers/documentation/mocks/assessment.md
  Servers/documentation/mocks/control.md
  Servers/documentation/mocks/controlCategory.md
  Servers/documentation/mocks/project.md
  Servers/documentation/mocks/projectRisks.md
  Servers/documentation/mocks/projectScope.md
  Servers/documentation/mocks/question.md
  Servers/documentation/mocks/role.md
  Servers/documentation/mocks/subcontrol.md
  Servers/documentation/mocks/subtopic.md
  Servers/documentation/mocks/tools/assessment.md
  Servers/documentation/mocks/tools/control.md
  Servers/documentation/mocks/tools/controlCategory.md
  Servers/documentation/mocks/tools/project.md
  Servers/documentation/mocks/tools/projectRisk.md
  Servers/documentation/mocks/tools/projectScope.md
  Servers/documentation/mocks/tools/question.md
  Servers/documentation/mocks/tools/role.md
  Servers/documentation/mocks/tools/subcontrol.md
  Servers/documentation/mocks/tools/subtopic.md
  Servers/documentation/mocks/tools/topic.md
  Servers/documentation/mocks/tools/user.md
  Servers/documentation/mocks/tools/vendor.md
  Servers/documentation/mocks/tools/vendorRisk.md
  Servers/documentation/mocks/topic.md
  Servers/documentation/mocks/users.md
  Servers/documentation/mocks/vendor.md
  Servers/documentation/mocks/vendorRisk.md
Labels: documentation, backend, team work and collaboration

#460 066 Jan 14: Documentation for Models
  Servers/documentation/controllers/assessment.md
  Servers/documentation/controllers/autoDriver.md
  Servers/documentation/controllers/control.md
  Servers/documentation/controllers/controlCategory.md
  Servers/documentation/controllers/project.md
  Servers/documentation/controllers/projectRisks.md
  Servers/documentation/controllers/projectScope.md
  Servers/documentation/controllers/question.md
  Servers/documentation/controllers/role.md
  Servers/documentation/controllers/subcontrol.md
  Servers/documentation/controllers/subtopic.md
  Servers/documentation/controllers/topic.md
  Servers/documentation/controllers/user.md
  Servers/documentation/controllers/vendor.md
  Servers/documentation/controllers/vendorRisk.md
  Servers/documentation/models/assessment.md
  Servers/documentation/models/control.md
  Servers/documentation/models/controlCategory.md
  Servers/documentation/models/file.md
  Servers/documentation/models/project.md
  Servers/documentation/models/projectRisk.md
  Servers/documentation/models/projectScope.md
  Servers/documentation/models/question.md
  Servers/documentation/models/role.md
  Servers/documentation/models/subcontrol.md
  Servers/documentation/models/subtopic.md
  Servers/documentation/models/topic.md
  Servers/documentation/models/user.md
  Servers/documentation/models/vendor.md
  Servers/documentation/models/vendorRisk.md
Labels: documentation, backend, team work and collaboration

#461 067 Jan 15: Documentation for Routes
  Servers/documentation/routes/assessment.md
  Servers/documentation/routes/autoDriver.md
  Servers/documentation/routes/control.md
  Servers/documentation/routes/controlCategory.md
  Servers/documentation/routes/project.md
  Servers/documentation/routes/projectRisk.md
  Servers/documentation/routes/projectScope.md
  Servers/documentation/routes/question.md
  Servers/documentation/routes/role.md
  Servers/documentation/routes/subcontrol.md
  Servers/documentation/routes/subtopic.md
  Servers/documentation/routes/topic.md
  Servers/documentation/routes/user.md
  Servers/documentation/routes/vendor.md
  Servers/documentation/routes/vendorRisk.md
Labels: documentation, backend, team work and collaboration

#462 068 Jan 15: Documentation for Utils
  Servers/documentation/utils/assessment.md
  Servers/documentation/utils/autoDriver.md
  Servers/documentation/utils/control.md
  Servers/documentation/utils/controlCategory.md
  Servers/documentation/utils/fileUpload.md
  Servers/documentation/utils/jwt.md
  Servers/documentation/utils/project.md
  Servers/documentation/utils/projectRisk.md
  Servers/documentation/utils/projectScope.md
  Servers/documentation/utils/question.md
  Servers/documentation/utils/role.md
  Servers/documentation/utils/statusCode.md
  Servers/documentation/utils/subcontrol.md
  Servers/documentation/utils/subtopic.md
  Servers/documentation/utils/topic.md
  Servers/documentation/utils/user.md
  Servers/documentation/utils/vendor.md
  Servers/documentation/utils/vendorRisk.md
Labels: documentation, backend, team work and collaboration

#463 069 Jan 15: Documentation for Validations
  Servers/documentation/validations/email.md
  Servers/documentation/validations/number.md
  Servers/documentation/validations/password.md
Labels: documentation, backend, team work and collaboration

#464 Feat/005 jan 15 add project status to overview project
  Clients/src/App.tsx
  Clients/src/application/contexts/VerifyWise.context.ts
  Clients/src/application/hooks/useProjectStatus.tsx
  Clients/src/application/tools/getProjectData.ts
  Clients/src/presentation/components/MetricSection/index.tsx
  Clients/src/presentation/components/ProjectCard/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
  Clients/src/presentation/pages/ProjectView/Overview/index.tsx
Labels: frontend

#466 Clean Architecture Readme is added
  Clients/clean-architecture.md
Labels: documentation, frontend

#467 069 jan 16 compliance tracker calcs
  Clients/src/presentation/mocks/compliance.data.ts
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
  Clients/src/presentation/pages/ComplianceTracker/index.css
Labels: frontend, backend

#468 Assessments Tracker Calculations
  Clients/src/presentation/pages/Assessment/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
Labels: frontend, backend

#486 070 jan 17 adding auth token
  Clients/src/application/repository/entity.repository.ts
  Clients/src/infrastructure/api/networkServices.ts
Labels: frontend

#487 Assessment values fixed
  Clients/src/presentation/pages/Assessment/index.tsx
Labels: enhancement, frontend

#474 Save input data values for risk-form and mitigation-form
  Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/interface.tsx
Labels: backend

#475 Implement functionality to delete the project
  Clients/src/application/tools/getProjectData.ts
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
Labels: frontend, backend

#490 070 Jan 17: Fix 500 error in DB
  Servers/utils/controlCategory.util.ts
  Servers/utils/projectRisk.utils.ts
  Servers/utils/projectScope.utils.ts
Labels: bug, backend

#493 Inconsistent font size matched
  Clients/src/presentation/pages/Assessment/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
  Clients/src/presentation/pages/FileManager/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
  Servers/utils/controlCategory.util.ts
  Servers/utils/projectRisk.utils.ts
  Servers/utils/projectScope.utils.ts
Labels: frontend

#494 Fixed missing values in Vendor table
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
Labels: bug

#496 Feat/006 jan 19 create use project risks
  Clients/src/application/hooks/useProjectRisks.tsx
  Clients/src/presentation/components/Risks/index.tsx
  Clients/src/presentation/pages/ProjectView/Overview/index.tsx
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
  Clients/src/presentation/pages/ProjectView/index.tsx
Labels: frontend

#498 Fixed the context
  Clients/src/application/contexts/VerifyWise.context.ts
Labels: bug

#499 072 Jan 20: Full Dockerization
  Clients/Dockerfile
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
  docker-compose.yml
  env.example
Labels: frontend, backend

#501 Connect Project Risks table to backend
  Clients/src/application/hooks/useProjectRisks.tsx
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
  Clients/src/presentation/pages/ProjectView/index.tsx
Labels: frontend

#503 VWCheckbox, new checkbox component is added
  Clients/src/presentation/pages/index.tsx
  Clients/src/presentation/vw-v2-components/Checks/index.tsx
Labels: enhancement, frontend

#508 075 Jan 21: Revert `docker-compose.yml` location change
  docker-compose.yml
Labels: Minor

#510 076 Jan 21: Add Vendor Risks calculations
  Servers/controllers/project.ctrl.ts
  Servers/mocks/tools/project.mock.db.ts
  Servers/routes/project.route.ts
  Servers/swagger.yaml
  Servers/utils/project.utils.ts
Labels: backend

#511 Delete project
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/components/ProjectCard/index.tsx
  Clients/src/presentation/pages/ProjectView/Overview/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Clients/src/presentation/pages/ProjectView/index.tsx
Labels: frontend, backend

#514 077 Jan 21: Add endpoint to delete mock data from the db
  Servers/controllers/autoDriver.ctrl.ts
  Servers/driver/autoDriver.driver.ts
  Servers/routes/autoDriver.route.ts
  Servers/utils/autoDriver.util.ts
Labels: backend

#515 078 Jan 21: Fix Project create fields
  Servers/controllers/project.ctrl.ts
  Servers/controllers/role.ctrl.ts
  Servers/swagger.yaml
  Servers/utils/project.utils.ts
  Servers/utils/role.utils.ts
  Servers/utils/vendor.utils.ts
Labels: bug, backend

#520 Dymanic Project Risks
  Clients/src/presentation/pages/ProjectView/Overview/index.tsx
  Clients/src/presentation/pages/ProjectView/index.tsx
Labels: frontend, backend

#517 49 20 jan pdf upload pop up
  Clients/src/presentation/components/FileUpload/index.tsx
  Clients/src/presentation/components/Modals/FileUpload/index.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
  Clients/src/presentation/pages/Assessment/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
  Clients/src/presentation/pages/FileManager/index.tsx
Labels: frontend

#523 074 Jan 21: Fix delete mechanism in Projects
  Servers/utils/project.utils.ts
Labels: enhancement, backend

#531 073 dashboard fix modification
  Clients/src/presentation/components/MetricSection/index.tsx
  Clients/src/presentation/components/ProjectCard/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
  Clients/src/presentation/pages/index.tsx
  Clients/src/presentation/themes/alerts.ts
  Clients/src/presentation/themes/v1SingleTheme.ts
  Clients/src/presentation/vw-v2-components/Alerts/index.tsx
  Clients/src/presentation/vw-v2-components/Checks/index.tsx
Labels: bug, enhancement, frontend

#533 Refactoring Code
  Clients/src/application/hooks/useProjectRisks.tsx
  Clients/src/application/hooks/useVendorRisks.tsx
  Clients/src/application/tools/stringUtil.ts
  Clients/src/presentation/pages/ProjectView/index.tsx
Labels: bug, frontend

#534 project title on view project page.
  Clients/src/presentation/pages/ProjectView/Overview/index.tsx
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
  Clients/src/presentation/pages/ProjectView/index.tsx
Labels: frontend

#537 Fix typo in useVendorRisks import in ProjectView component
  Clients/src/presentation/pages/ProjectView/index.tsx
Labels: bug, frontend, Minor

#539 Update Project description string and send ids to the fields where nu…
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/pages/ProjectView/index.tsx
Labels: frontend

#536 080 Jan 23: File Handling
  Servers/controllers/assessment.ctrl.ts
  Servers/controllers/control.ctrl.ts
  Servers/controllers/file.ctrl.ts
  Servers/controllers/question.ctrl.ts
  Servers/controllers/subcontrol.ctrl.ts
  Servers/driver/autoDriver.driver.ts
  Servers/index.ts
  Servers/mocks/subcontrol.mock.data.ts
  Servers/models/subcontrol.model.ts
  Servers/routes/assessment.route.ts
  Servers/routes/control.route.ts
  Servers/routes/file.route.ts
  Servers/utils/project.utils.ts
  Servers/utils/question.utils.ts
  Servers/utils/subControl.utils.ts
Labels: frontend, backend, team work and collaboration

#541 Route protection enabled
  Clients/src/App.tsx
Labels: frontend

#552 075 jan 27 demo data popup
  Clients/src/presentation/pages/index.tsx
  Clients/src/presentation/vw-v2-components/Dialogs/DualButtonModal/index.css
  Clients/src/presentation/vw-v2-components/Dialogs/DualButtonModal/index.tsx
  Clients/vite.config.ts.timestamp-1737902954929-88f5d1bd1efce.mjs
Labels: frontend, backend, team work and collaboration

#553 Check box is now selectable
  Clients/src/presentation/components/Inputs/Checkbox/index.tsx
  Clients/src/presentation/pages/Authentication/Login/index.tsx
Labels: bug, frontend

#555 Add create project button for empty state
  Clients/src/presentation/pages/Home/index.tsx
Labels: bug, frontend

#559 081 Jan 27: Fix Auto-Driver
  Servers/driver/autoDriver.driver.ts
  Servers/mocks/project.mock.data.ts
Labels: backend

#561 Edit vendor functionality
  Clients/src/application/repository/entity.repository.ts
  Clients/src/infrastructure/api/networkServices.ts
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
Labels: frontend

#564 Fetch project data in project setting page
  Clients/src/application/hooks/useProjectData.tsx
  Clients/src/presentation/pages/ProjectView/Overview/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
Labels: frontend

#568 078 jan 28 fix enhancement
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Servers/endpoints-test/assessment.http.test.rest
Labels: bug, frontend, UI/UX Design

#569 082 Jan 27: Added `install` shell script
  .env
  Clients/.env
  Clients/Dockerfile
  Clients/env.vars.ts
  Clients/package-lock.json
  Clients/package.json
  Clients/src/infrastructure/api/customAxios.ts
  Clients/src/presentation/components/FileUpload/uppyConfig.ts
  Clients/vite.config.ts
  INSTALLATION.md
  SQL_Commands.sql
  docker-compose.yml
  env.example
  install.sh
Labels: enhancement, Main, team work and collaboration

#572 File upload component fixed
  Clients/src/infrastructure/api/customAxios.ts
  Clients/src/presentation/components/FileUpload/index.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
Labels: bug, frontend

#574 Fixing tooltip font
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
Labels: frontend, UI/UX Design

#575 Toast component
  Clients/src/presentation/pages/index.tsx
  Clients/src/presentation/vw-v2-components/Toast/index.tsx
Labels: frontend

#579 082 Jan 27: Create installation shell script
  .env
  Clients/Dockerfile
  Clients/env.vars.ts
  Clients/src/infrastructure/api/customAxios.ts
  Clients/startup.sh
  Clients/vite.config.ts
  INSTALLATION.md
  docker-compose.yml
Labels: enhancement, frontend, Main, team work and collaboration

#580 083 Jan 30: Fix auto driver
  Servers/driver/autoDriver.driver.ts
  Servers/mocks/role.mock.data.ts
  Servers/mocks/users.data.ts
  Servers/utils/autoDriver.util.ts
Labels: frontend, backend, team work and collaboration

#570 Updated Project settings page
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Clients/src/presentation/vw-v2-components/Dialogs/DualButtonModal/index.tsx
Labels: frontend

#587 Replacing userId with dynamic value
  Clients/src/App.tsx
  Clients/src/application/tools/extractToken.ts
Labels: enhancement, frontend

#577 Added users from database for Team users
  Clients/src/application/hooks/useProjectData.tsx
  Clients/src/application/tools/stringUtil.ts
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Clients/src/presentation/vw-v2-components/Selects/Multi/index.tsx
Labels: frontend

#589 Minor bug fixes and changes
  Clients/src/application/tools/extractToken.ts
  Clients/src/presentation/pages/Assessment/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
  Clients/src/presentation/vw-v2-components/Selects/Multi/index.tsx
Labels: frontend, UI/UX Design
