Repository bluewave-labs/verifywise, pull requests merged in 2025-07, with the labels that each got.

#1718 Feat: Multiple Risk Category DB
  Clients/src/domain/types/ProjectRisk.ts
  Servers/database/migrations/20250630192711-update-risk-category-projectrisks.js
  Servers/domain.layer/models/projectRisks/projectRisk.model.ts
  Servers/domain.layer/models/projectRisks/projectRisks.mock.data.ts
  Servers/driver/autoDriver.driver.ts
  Servers/utils/projectRisk.utils.ts
Labels: enhancement, backend

#1726 AI Trust Overview
  Clients/src/application/config/routes.tsx
  Clients/src/presentation/assets/icons/aiTrustCenter.svg
  Clients/src/presentation/components/Inputs/Toggle/index.tsx
  Clients/src/presentation/components/Inputs/Toggle/styles.ts
  Clients/src/presentation/components/Inputs/ToggleCard/index.tsx
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Controls/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Controls/styles.ts
  Clients/src/presentation/pages/AITrustCenter/Overview/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Overview/styles.ts
  Clients/src/presentation/pages/AITrustCenter/Resources/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Resources/styles.ts
  Clients/src/presentation/pages/AITrustCenter/Settings/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Settings/styles.ts
  Clients/src/presentation/pages/AITrustCenter/Subprocessors/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Subprocessors/styles.ts
  Clients/src/presentation/pages/AITrustCenter/index.tsx
  Clients/src/presentation/pages/AITrustCenter/styles.ts
Labels: frontend, team work and collaboration

#1729 Assessment unit tests added
  Servers/domain.layer/tests/assessment.model.spec.ts
Labels: backend

#1730 Add logging to backend
  Servers/controllers/user.ctrl.ts
  Servers/database/migrations/20250703153628-create-event-logs.js
  Servers/middleware/auth.middleware.ts
  Servers/middleware/context.middleware.ts
  Servers/package-lock.json
  Servers/package.json
  Servers/utils/context/context.ts
  Servers/utils/logger/dbLogger.ts
  Servers/utils/logger/fileLogger.ts
Labels: backend

#1732 Feat: MIT AI RISK Frontend
  Clients/src/application/validations/selectValidation.ts
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/interface.tsx
  Clients/src/presentation/components/AddNewRiskMITForm/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/ProjectRisks/index.tsx
Labels: enhancement, frontend

#1736 Add logging to vendor risk
  Servers/controllers/vendorRisk.ctrl.ts
  Servers/utils/logger/logHelper.ts
Labels: backend

#1739 Fix: Risk Categories Selection
  Clients/src/application/validations/selectValidation.ts
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
Labels: bug

#1751 Add logging to vendor controller
  Servers/controllers/vendor.ctrl.ts
Labels: backend

#1752 Integrate email invitations
  .env.dev
  .env.prod
  Clients/src/presentation/components/Modals/InviteUser/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
  README.md
  Servers/controllers/user.ctrl.ts
  Servers/controllers/vwmailer.ctrl.ts
  Servers/package-lock.json
  Servers/package.json
  Servers/routes/vwmailer.route.ts
  Servers/services/emailService.ts
  Servers/templates/account-creation-email.mjml
Labels: frontend, backend

#1754 Mo 167 july 10 class based project framework
  Servers/domain.layer/interfaces/i.projectFramework.ts
  Servers/domain.layer/models/projectFrameworks/projectFrameworks.model.ts
  Servers/domain.layer/tests/projectFrameworks.model.spec.ts
Labels: enhancement, backend

#1757 Role domain-layer
  Servers/controllers/role.ctrl.ts
  Servers/domain.layer/interfaces/i.role.ts
  Servers/domain.layer/models/role/role.model.ts
  Servers/domain.layer/tests/role.model.spec.ts
  Servers/utils/project.utils.ts
  Servers/utils/role.utils.ts
Labels: backend

#1766 Mo 171 july 13 class based question
  Servers/controllers/question.ctrl.ts
  Servers/domain.layer/interfaces/i.question.ts
  Servers/domain.layer/models/question/question.mock.data.ts
  Servers/domain.layer/models/question/question.model.ts
  Servers/domain.layer/tests/question.model.spec.ts
  Servers/utils/question.utils.ts
  Servers/utils/subtopic.utils.ts
Labels: enhancement, backend

#1773 Fix: Create Organization Error on First Time
  Servers/controllers/organization.ctrl.ts
  Servers/utils/user.utils.ts
Labels: bug, backend

#1775 Add logging to projects controller
  Servers/controllers/project.ctrl.ts
  Servers/controllers/user.ctrl.ts
  Servers/controllers/vendor.ctrl.ts
  Servers/controllers/vendorRisk.ctrl.ts
  Servers/utils/logger/logHelper.ts
Labels: backend

#1748 AI Trust Overview with backend integration
  Clients/src/application/hooks/useAITrustCentreOverview.tsx
  Clients/src/application/repository/aiTrustCentre.repository.ts
  Clients/src/application/tools/extractToken.ts
  Clients/src/presentation/pages/AITrustCenter/Overview/constants.ts
  Clients/src/presentation/pages/AITrustCenter/Overview/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Overview/styles.ts
  Clients/src/presentation/pages/AITrustCenter/Resources/constants.ts
  Clients/src/presentation/pages/AITrustCenter/Resources/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Resources/styles.ts
  Clients/src/presentation/pages/AITrustCenter/Settings/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Settings/styles.ts
  Clients/src/presentation/pages/AITrustCenter/Subprocessors/constants.ts
  Clients/src/presentation/pages/AITrustCenter/Subprocessors/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Subprocessors/styles.ts
  Clients/src/presentation/pages/AITrustCenter/index.tsx
  Servers/SQL_Commands.sql
  Servers/controllers/aiTrustCentre.ctrl.ts
  Servers/database/db.ts
  Servers/database/migrations/20250712145401-create-ai-trust-centre-tables.js
  Servers/documentation/routes/aiTrustCentre.md
  Servers/domain.layer/interfaces/i.aiTrustCentreOverview.ts
  Servers/domain.layer/interfaces/i.aiTrustCentrePublic.ts
  Servers/domain.layer/interfaces/i.aiTrustCentreResources.ts
  Servers/domain.layer/interfaces/i.aiTrustCentreSubprocessors.ts
  Servers/domain.layer/models/aiTrustCentre/aiTrustCenterInfo.model.ts
  Servers/domain.layer/models/aiTrustCentre/aiTrustCentreCompanyDescription.model.ts
  Servers/domain.layer/models/aiTrustCentre/aiTrustCentreComplianceBadges.model.ts
  Servers/domain.layer/models/aiTrustCentre/aiTrustCentreIntro.model.ts
  Servers/domain.layer/models/aiTrustCentre/aiTrustCentreResources.model.ts
  Servers/domain.layer/models/aiTrustCentre/aiTrustCentreSubprocessors.model.ts
  Servers/domain.layer/models/aiTrustCentre/aiTrustCentreTermsAndContract.model.ts
  Servers/driver/autoDriver.driver.ts
  Servers/endpoints-test/aiTrustCentre.http.test.rest
  Servers/index.ts
  Servers/middleware/validateAITrustCentreVisibility.middleware.ts
  Servers/routes/aiTrustCentre.route.ts
  Servers/scripts/createNewTenant.ts
  Servers/utils/aiTrustCentre.utils.ts
  Servers/utils/fileUpload.utils.ts
  Servers/utils/question.utils.ts
Labels: frontend, backend

#1779 Mo 174 july 15 class based subtopic and home page changes
  Clients/src/presentation/components/NoProject/NoProject.tsx
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
  Servers/controllers/subtopic.ctrl.ts
  Servers/domain.layer/interfaces/i.subtopic.ts
  Servers/domain.layer/models/subtopic/subtopic.mock.data.ts
  Servers/domain.layer/models/subtopic/subtopic.model.ts
  Servers/domain.layer/tests/subtopic.model.spec.ts
  Servers/utils/subtopic.utils.ts
Labels: enhancement, backend

#1769 Sid 07 09 documenting changes
  Servers/package-lock.json
  Servers/package.json
  Servers/routes/trainingRegistar.route.ts
  Servers/swagger.yaml
Labels: documentation, backend

#1780 Feat: Stripe DB Changes Integrations
  Servers/database/migrations/20250319220000-create-organizations-table.js
  Servers/database/migrations/20250319225827-initial-setup.js
Labels: enhancement

#1784 Fix: No Members Validation
  Clients/src/presentation/vw-v2-components/Forms/ProjectForm/index.tsx
  Servers/controllers/project.ctrl.ts
Labels: bug

#1786 Fixing project risk update bug
  Servers/controllers/projectRisks.ctrl.ts
Labels: bug

#1788 Fix organization update issue
  Servers/controllers/organization.ctrl.ts
  Servers/domain.layer/interfaces/i.organization.ts
  Servers/domain.layer/models/organization/organization.model.ts
  Servers/routes/organization.route.ts
  Servers/utils/organization.utils.ts
Labels: bug, backend

#1799 Update license description
  README.md
Labels: codex

#1796 Fix: Framework Clauses subclauses state handling
  Clients/src/presentation/pages/ISO/Clause/index.tsx
Labels: bug, frontend

#1809 AI Trust Center Subprocessor Page Backend Integration
  Clients/src/application/hooks/useAITrustCentreSubprocessors.tsx
  Clients/src/application/repository/aiTrustCentre.repository.ts
  Clients/src/presentation/pages/AITrustCenter/Resources/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Resources/styles.ts
  Clients/src/presentation/pages/AITrustCenter/Subprocessors/constants.ts
  Clients/src/presentation/pages/AITrustCenter/Subprocessors/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Subprocessors/styles.ts
Labels: frontend

#1798 Add logging to assessment controller
  Servers/controllers/assessment.ctrl.ts
Labels: backend

#1804 Update email invitations
  Clients/src/application/tools/alertUtils.ts
  Clients/src/domain/interfaces/iAlert.ts
  Clients/src/presentation/components/Modals/InviteUser/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
  Servers/controllers/vwmailer.ctrl.ts
  Servers/routes/trainingRegistar.route.ts
Labels: frontend, backend

#1819 added_surname_to_teams_table
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
Labels: enhancement, frontend

#1820 Add route to download public resources
  Servers/controllers/aiTrustCentre.ctrl.ts
  Servers/routes/aiTrustCentre.route.ts
  Servers/utils/aiTrustCentre.utils.ts
Labels: backend

#1821 AI Trust Centre Public Page
  Clients/public.html
  Clients/public/assets/badges/ccpa.svg
  Clients/public/assets/badges/eu_ai_act.svg
  Clients/public/assets/badges/gdpr.svg
  Clients/public/assets/badges/hipaa.svg
  Clients/public/assets/badges/iso_27001.svg
  Clients/public/assets/badges/iso_42001.svg
  Clients/public/assets/badges/soc2_type_i.svg
  Clients/public/assets/badges/soc2_type_ii.svg
  Clients/src/presentation/pages/AITrustCentrePublic/Components/CustomTextField/CustomTextField.tsx
  Clients/src/presentation/pages/AITrustCentrePublic/Components/Header/AITrustCentreHeader.tsx
  Clients/src/presentation/pages/AITrustCentrePublic/Overview/index.tsx
  Clients/src/presentation/pages/AITrustCentrePublic/Resources/index.tsx
  Clients/src/presentation/pages/AITrustCentrePublic/Subprocessors/index.tsx
  Clients/src/presentation/pages/AITrustCentrePublic/index.tsx
  Clients/src/presentation/pages/AITrustCentrePublic/style.ts
  Clients/src/public.tsx
Labels: frontend

#1827 AI trust Logo Upload
  Clients/src/application/repository/aiTrustCentre.repository.ts
  Clients/src/presentation/pages/AITrustCenter/Overview/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Resources/styles.ts
  Clients/src/presentation/pages/AITrustCenter/Settings/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Settings/styles.ts
  Clients/src/presentation/pages/AITrustCenter/Subprocessors/styles.ts
Labels: frontend

#1831 Add logging to role controller
  Servers/controllers/role.ctrl.ts
Labels: backend

#1846 AI Trust Center
  Clients/src/application/config/routes.tsx
  Clients/src/presentation/pages/AITrustCenter/Settings/index.tsx
  Clients/src/presentation/pages/AITrustCenter/index.tsx
  Clients/src/presentation/pages/AITrustCentrePublic/Components/Header/AITrustCentreHeader.tsx
  Clients/src/presentation/pages/AITrustCentrePublic/Overview/index.tsx
  Clients/src/presentation/pages/AITrustCentrePublic/index.tsx
Labels: frontend

#1851 Fix autoDrivers
  Servers/scripts/createNewTenant.ts
Labels: bug, backend

#1832 Improvment- Vendor Form UI + Modal Changes
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Servers/controllers/vendor.ctrl.ts
  Servers/database/migrations/20250724154345-remove-risk-status-from-tenant-vendors.js
  Servers/documentation/models/vendor.md
  Servers/domain.layer/interfaces/i.vendor.ts
  Servers/domain.layer/models/vendor/vendor.mock.data.ts
  Servers/domain.layer/models/vendor/vendor.model.ts
  Servers/driver/autoDriver.driver.ts
  Servers/scripts/createNewTenant.ts
  Servers/services/markdowns/vendorAndRisksMarkdown.ts
  Servers/swagger.yaml
  Servers/utils/vendor.utils.ts
Labels: documentation, frontend, backend
