Repository bluewave-labs/verifywise, pull requests merged in 2025-08, with the labels that each got.

#1861 A few enhancements
  Clients/src/presentation/pages/WatchTower/index.tsx
  Servers/utils/logger.util.ts
Labels: enhancement, frontend, backend, descriptive/informative

#1866 Mo 190 aug 5 iso27001
  Servers/structures/ISO-27001/annexes/iso27001.annex.struct.ts
  Servers/structures/ISO-27001/clauses/iso27001.clause.struct.ts
Labels: documentation, backend

#1865 Attach risks to EU AI Act
  Clients/src/domain/interfaces/iWidget.ts
  Clients/src/domain/types/Control.ts
  Clients/src/domain/types/ProjectRisk.ts
  Clients/src/domain/types/Question.ts
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/ProjectRiskMitigation/ProjectRiskMitigation.tsx
  Clients/src/presentation/components/Table/ProjectRiskMitigationTable/ProjectRiskMitigationTableBody.tsx
  Clients/src/presentation/components/VWQuestion/index.tsx
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/index.tsx
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/questions.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/index.tsx
  Clients/src/presentation/vw-v2-components/Table/VWProjectRisksTableBody.tsx
  Servers/controllers/eu.ctrl.ts
  Servers/database/migrations/20250803010207-add-attached-risk-tables-for-EU.js
  Servers/domain.layer/frameworks/EU-AI-Act/answerEURisks.model.ts
  Servers/domain.layer/frameworks/EU-AI-Act/controlsEURisks.model.ts
  Servers/utils/eu.utils.ts
  Servers/utils/projectRisk.utils.ts
Labels: enhancement, frontend, backend

#1876 Mo 191 aug 8 iso27001 backend
  Servers/domain.layer/frameworks/ISO-27001/ISO27001AnnexCategory.model.ts
  Servers/domain.layer/frameworks/ISO-27001/ISO27001AnnexCrossMapping.model.ts
  Servers/domain.layer/frameworks/ISO-27001/ISO27001Clause.model.ts
  Servers/domain.layer/frameworks/ISO-27001/ISO27001ClauseCrossMapping.model.ts
  Servers/domain.layer/frameworks/ISO-27001/iso27001AnnexControl.model.ts
  Servers/domain.layer/interfaces/i.ISO27001AnnexCategory.ts
  Servers/domain.layer/interfaces/i.ISO27001AnnexCrossMapping.ts
  Servers/domain.layer/interfaces/i.ISO27001Clause.ts
  Servers/domain.layer/interfaces/i.ISO27001ClauseCrossMapping.ts
  Servers/domain.layer/interfaces/i.iso27001AnnexControl.ts
  Servers/domain.layer/tests/ISO27001AnnexCategory.model.spec.ts
  Servers/domain.layer/tests/ISO27001AnnexCrossMapping.model.spec.ts
  Servers/domain.layer/tests/ISO27001Clause.model.spec.ts
  Servers/domain.layer/tests/ISO27001ClauseCrossMapping.model.spec.ts
  Servers/domain.layer/tests/iso27001AnnexControl.model.spec.ts
  Servers/endpoints-test/iso27001-http.test.rest
  Servers/index.ts
  Servers/routes/iso27001.route.ts
Labels: backend

#1879 Minor bug fixes: Attach risks to EU
  Clients/src/presentation/components/Drawer/AnnexDrawerDialog/index.tsx
  Clients/src/presentation/components/Drawer/ClauseDrawerDialog/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/ProjectRiskMitigation/ProjectRiskMitigation.tsx
  Clients/src/presentation/components/Table/ProjectRiskMitigationTable/ProjectRiskMitigationTable.tsx
  Clients/src/presentation/components/VWQuestion/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/ProjectRisks/index.tsx
  Clients/src/presentation/vw-v2-components/Table/VWProjectRisksTableBody.tsx
Labels: bug, frontend

#1892 Implement Tanstack on Dashboard
  Clients/package-lock.json
  Clients/package.json
  Clients/src/App.tsx
  Clients/src/application/config/queryClient.ts
  Clients/src/application/hooks/useBaseQueries.ts
  Clients/src/application/hooks/useFrameworks.ts
  Clients/src/application/hooks/useProjects.ts
  Clients/src/main.tsx
  Clients/src/presentation/components/VWQuestion/index.tsx
Labels: frontend

#1901 Mo 196 aug 13 model inventory fixes
  Clients/src/presentation/components/Modals/NewModelInventory/index.tsx
  Clients/src/presentation/pages/ModelInventory/ModelInventorySummary.tsx
  Clients/src/presentation/pages/ModelInventory/index.tsx
  Clients/src/presentation/pages/ModelInventory/modelInventoryTable.tsx
  Clients/src/presentation/pages/ModelInventory/style.ts
Labels: enhancement, frontend

#1906 Mo 198 aug 14 bug fix
  Servers/domain.layer/frameworks/ISO-27001/ISO27001AnnexControlRisks.model.ts
  Servers/domain.layer/frameworks/ISO-27001/iso27001AnnexControl.model.ts
  Servers/domain.layer/interfaces/i.ISO27001Clause.ts
  Servers/domain.layer/interfaces/i.iso27001AnnexControl.ts
  Servers/domain.layer/models/frameworks/frameworks.model.ts
  Servers/domain.layer/tests/ISO27001AnnexCategory.model.spec.ts
Labels: bug, backend, Conflict

#1904 Reports: Remove tabs and move “Generate report” button to list view
  Clients/src/presentation/pages/Reporting/GenerateReport/ReportStatus/index.tsx
  Clients/src/presentation/pages/Reporting/GenerateReport/styles.ts
  Clients/src/presentation/pages/Reporting/index.tsx
  Clients/src/presentation/pages/Reporting/styles.ts
Labels: UI/UX Design

#1924 Mo 200 aug 16 fixing dashboard bugs
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/Alert/AlertBody.tsx
  Clients/src/presentation/components/Reporting/GenerateReport/index.tsx
  Clients/src/presentation/pages/Reporting/GenerateReport/index.tsx
  Clients/src/presentation/pages/Reporting/Reports/index.tsx
  Clients/src/presentation/pages/Reporting/Reports/styles.ts
  Clients/src/presentation/pages/Reporting/index.tsx
Labels: bug, frontend

#1925 Breadcrumbs added to the dashboard
  Clients/src/presentation/components/Breadcrumbs/PageBreadcrumbs.tsx
  Clients/src/presentation/components/Breadcrumbs/index.tsx
  Clients/src/presentation/components/Breadcrumbs/routeMapping.ts
  Clients/src/presentation/pages/AITrustCenter/index.tsx
  Clients/src/presentation/pages/FairnessDashboard/FairnessDashboard.tsx
  Clients/src/presentation/pages/FileManager/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
  Clients/src/presentation/pages/ModelInventory/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/index.tsx
  Clients/src/presentation/pages/ProjectView/index.tsx
  Clients/src/presentation/pages/Reporting/index.tsx
  Clients/src/presentation/pages/SettingsPage/index.tsx
  Clients/src/presentation/pages/TrainingRegistar/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
  Clients/src/presentation/pages/WatchTower/index.tsx
  Clients/src/presentation/pages/index.tsx
Labels: enhancement, frontend

#1910 refactor: restructure and expand vendor repository
  Clients/src/application/repository/vendor.repository.ts
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/components/Table/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
  Clients/tsconfig.app.tsbuildinfo
Labels: enhancement, frontend

#1927 Feat: Stripe Subscription + Tiers (Controllers + Utils + Routes)
  Servers/controllers/subscriptions.ctrl.ts
  Servers/controllers/tiers.ctrl.ts
  Servers/database/db.ts
  Servers/domain.layer/interfaces/i.subscriptions.ts
  Servers/domain.layer/models/subscriptions/subscriptions.mock.data.ts
  Servers/domain.layer/models/subscriptions/subscriptions.model.ts
  Servers/index.ts
  Servers/routes/subscription.route.ts
  Servers/routes/tiers.route.ts
  Servers/utils/subscription.util.ts
Labels: enhancement, backend

#1942 Update product descriptions for Policy Manager and AI Trust Center
  Clients/src/presentation/pages/AITrustCenter/index.tsx
  Clients/src/presentation/pages/PolicyDashboard/PoliciesDashboard.tsx
Labels: enhancement, frontend

#1960 Add table view for projects with card/table toggle and persistence
  Clients/src/presentation/components/ProjectsList/ProjectTableView.tsx
  Clients/src/presentation/components/ProjectsList/ProjectsList.tsx
  Clients/src/presentation/hooks/usePersistedViewMode.ts
  Clients/src/presentation/pages/Home/index.tsx
  Clients/src/presentation/vw-v2-components/ViewToggle/index.tsx
Labels: frontend

#1973 Implement the Tanstack query on AITrust page
  Clients/src/application/config/queryClient.ts
  Clients/src/application/hooks/useAITrustCentreOverviewQuery.ts
  Clients/src/application/hooks/useAITrustCentreResourcesQuery.ts
  Clients/src/application/hooks/useAITrustCentreSubprocessorsQuery.ts
  Clients/src/presentation/pages/AITrustCenter/Overview/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Resources/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Settings/index.tsx
  Clients/src/presentation/pages/AITrustCenter/Subprocessors/index.tsx
Labels: frontend

#1993 Framework button replaced
  Clients/src/presentation/pages/Framework/index.tsx
Labels: enhancement, frontend

#1989 Added Tanstack query on Vendors page
  Clients/src/application/hooks/useProjects.ts
  Clients/src/application/hooks/useVendorRiskMutations.ts
  Clients/src/application/hooks/useVendorRisks.tsx
  Clients/src/application/hooks/useVendors.ts
  Clients/src/presentation/components/Modals/NewRisk/index.tsx
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/pages/FileManager/index.tsx
  Clients/src/presentation/pages/Reporting/Reports/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
Labels: frontend

#1974 Helpful text for the recommended size
  Clients/src/presentation/pages/AITrustCenter/Settings/index.tsx
  Clients/src/presentation/pages/SettingsPage/Organization/index.tsx
Labels: frontend

#1998 vendor-risk-sections-should-accept-256-chars
  Clients/src/presentation/components/Modals/NewRisk/index.tsx
Labels: enhancement, frontend

#1999 models-cards-showing-incorrect-count-fix
  Servers/utils/dashboard.utils.ts
Labels: enhancement, frontend

#2001 Refactor report type field: replace RadioGroup with Select to optimize space in GenerateReportFrom
  Clients/src/presentation/components/Inputs/Select/index.css
  Clients/src/presentation/components/Reporting/GenerateReport/GenerateReportFrom/index.tsx
  Clients/src/presentation/components/Reporting/GenerateReport/GenerateReportFrom/styles.ts
  Clients/src/presentation/components/Reporting/GenerateReport/styles.ts
Labels: frontend

#2006 Mo 205 aug 30 iso42001 organizational
  .claude/settings.local.json
  Clients/src/presentation/components/Drawer/AnnexDrawerDialog/index.tsx
  Clients/src/presentation/components/Drawer/ClauseDrawerDialog/index.tsx
  Clients/src/presentation/components/Drawer/ISO27001AnnexDrawerDialog/index.tsx
  Clients/src/presentation/components/Drawer/ISO27001ClauseDrawerDialog/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/pages/Framework/ISO42001/Annex/index.tsx
  Clients/src/presentation/pages/Framework/ISO42001/Clause/index.tsx
  Clients/src/presentation/pages/Framework/ISO42001/index.tsx
  Clients/src/presentation/pages/Framework/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
  Clients/tsconfig.app.tsbuildinfo
  Servers/utils/project.utils.ts
Labels: enhancement, frontend

#2007 Status dropdown for clauses and annexes
  .claude/settings.local.json
  Clients/src/presentation/components/StatusDropdown/index.tsx
Labels: enhancement, frontend, backend, descriptive/informative
