Repository bluewave-labs/verifywise, pull requests merged in 2025-05, with the labels that each got.

#1254 #1098 bugfix-vendor-page
  Clients/src/presentation/pages/Vendors/index.tsx
Labels: frontend

#1258 Fix file downloads and add support all file-types
  Clients/src/application/repository/entity.repository.ts
  Clients/src/application/tools/createUppy.ts
  Clients/src/application/tools/fileDownload.ts
  Clients/src/infrastructure/api/networkServices.ts
  Clients/src/presentation/vw-v2-components/Inputs/FileUpload/index.tsx
  Servers/controllers/control.ctrl.ts
  Servers/controllers/file.ctrl.ts
  Servers/database/migrations/20250501050948-add-file-type-field.js
  Servers/models/file.model.ts
  Servers/utils/fileUpload.utils.ts
  Servers/utils/subControl.utils.ts
Labels: bug, frontend, backend

#1264 Fill in the login information for demo app
  Clients/src/presentation/pages/Authentication/Login/index.tsx
Labels: frontend

#1260 Move Complience tracker to Frameworks tab.
  Clients/src/application/config/routes.tsx
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.md
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/styles.ts
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/index.tsx
Labels: frontend

#1267 Mo 125 may 2 modifications enhancements
  Clients/src/domain/enums/mitigitaion.ts
  Clients/src/domain/interfaces/iAlert.ts
  Clients/src/domain/interfaces/iForm.ts
  Clients/src/domain/interfaces/iResponse.ts
  Clients/src/domain/interfaces/iRiskForm.ts
  Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/style.ts
  Clients/src/presentation/components/AddNewVendorRiskForm/index.tsx
Labels: enhancement, frontend

#1272 Mo 126 may 3 enhancements
  Clients/src/application/tools/alertUtils.ts
  Clients/src/domain/enums/checkVariants.ts
  Clients/src/domain/enums/risk.ts
  Clients/src/domain/interfaces/iAlert.ts
  Clients/src/domain/interfaces/iForm.ts
  Clients/src/domain/interfaces/iRiskSummary.ts
  Clients/src/domain/interfaces/iStatsCard.ts
  Clients/src/domain/interfaces/iUser.ts
  Clients/src/domain/interfaces/iWidget.ts
  Clients/src/presentation/components/AddNewVendorRiskForm/index.tsx
  Clients/src/presentation/components/Alert/index.tsx
  Clients/src/presentation/components/Alert/style.ts
  Clients/src/presentation/components/Cards/RisksCard/index.tsx
  Clients/src/presentation/components/Cards/StatsCard/index.tsx
  Clients/src/presentation/components/Checks/index.tsx
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx
  Clients/src/presentation/components/VWQuestion/index.tsx
  Clients/src/presentation/pages/Authentication/ForgotPassword/index.tsx
  Clients/src/presentation/pages/Authentication/ResetPassword/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
Labels: enhancement, frontend

#1273 Update datatype for subtopic_id in questions
  Servers/models/question.model.ts
Labels: bug, backend

#1274 Add `Source` in Evidences tab
  Clients/src/application/hooks/useFetchFiles.ts
  Clients/src/domain/types/File.ts
  Clients/src/presentation/components/Table/FilesBasicTable/FileBasicTable.tsx
  Clients/src/presentation/pages/FileManager/index.tsx
Labels: frontend

#1289 Mo 127 may 5 types organizing
  Clients/src/domain/interfaces/iWidget.ts
  Clients/src/presentation/components/FileUpload/FileUpload.styles.ts
  Clients/src/presentation/components/FileUpload/index.tsx
  Clients/src/presentation/components/IconButton/index.tsx
  Clients/src/presentation/components/Inputs/Autocomplete/index.tsx
  Clients/src/presentation/components/Inputs/Checkbox/index.tsx
  Clients/src/presentation/components/Inputs/Datepicker/index.tsx
  Clients/src/presentation/components/Inputs/Datepicker/style.ts
Labels: enhancement, frontend

#1279 Transactionalize all the DB queries
  Servers/controllers/assessment.ctrl.ts
  Servers/controllers/control.ctrl.ts
  Servers/controllers/controlCategory.ctrl.ts
  Servers/controllers/eu.ctrl.ts
  Servers/controllers/file.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/controllers/projectRisks.ctrl.ts
  Servers/controllers/projectScope.ctrl.ts
  Servers/controllers/question.ctrl.ts
  Servers/controllers/reporting.ctrl.ts
  Servers/controllers/role.ctrl.ts
  Servers/controllers/subcontrol.ctrl.ts
  Servers/controllers/subtopic.ctrl.ts
  Servers/controllers/topic.ctrl.ts
  Servers/controllers/user.ctrl.ts
  Servers/controllers/vendor.ctrl.ts
  Servers/controllers/vendorRisk.ctrl.ts
  Servers/utils/assessment.utils.ts
  Servers/utils/control.utils.ts
  Servers/utils/controlCategory.util.ts
  Servers/utils/eu.utils.ts
  Servers/utils/fileUpload.utils.ts
  Servers/utils/project.utils.ts
  Servers/utils/projectRisk.utils.ts
  Servers/utils/projectScope.utils.ts
  Servers/utils/question.utils.ts
  Servers/utils/role.utils.ts
  Servers/utils/subControl.utils.ts
  Servers/utils/subtopic.utils.ts
  Servers/utils/topic.utils.ts
  Servers/utils/user.utils.ts
  Servers/utils/vendor.utils.ts
  Servers/utils/vendorRisk.util.ts
Labels: backend

#1280 Fix AutoDriver for EU AI Act
  Servers/controllers/autoDriver.ctrl.ts
  Servers/driver/autoDriver.driver.ts
  Servers/utils/autoDriver.util.ts
  Servers/utils/eu.utils.ts
  Servers/utils/project.utils.ts
  Servers/utils/user.utils.ts
  Servers/utils/vendor.utils.ts
Labels: backend

#1299 Mo 128 may 6 type definition
  Clients/src/domain/interfaces/iMetricSection.ts
  Clients/src/domain/interfaces/iSelect.ts
  Clients/src/domain/interfaces/iWidget.ts
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Inputs/Dropdowns/style.ts
  Clients/src/presentation/components/Inputs/Field/index.tsx
  Clients/src/presentation/components/Inputs/Image/constants.ts
  Clients/src/presentation/components/Inputs/Image/index.tsx
  Clients/src/presentation/components/Inputs/Select/index.tsx
  Clients/src/presentation/components/MetricSection/index.tsx
  Clients/src/presentation/components/Modals/Banner/index.tsx
  Clients/src/presentation/components/Modals/Banner/style.ts
  Clients/src/presentation/components/Modals/Basic/index.tsx
  Clients/src/presentation/components/Modals/Basic/style.ts
Labels: enhancement, frontend

#1300 Remove extra space and step from joy ride for project selector
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/pages/Home/1.0Home/HomeSteps.tsx
Labels: frontend

#1317 Mo 129 may 6 iso UI
  Clients/src/presentation/components/ComingSoonMessage/index.tsx
  Clients/src/presentation/pages/ISO/Annex/annex.structure.ts
  Clients/src/presentation/pages/ISO/Annex/index.tsx
  Clients/src/presentation/pages/ISO/Clause/clause.structure.ts
  Clients/src/presentation/pages/ISO/Clause/index.tsx
  Clients/src/presentation/pages/ISO/style.ts
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
  Servers/database/migrations/20250502184633-create-structure-for-assessment-tracker.js
  Servers/database/migrations/20250502184712-create-structure-for-compliance-tracker.js
  Servers/package.json
Labels: frontend

#1305 Remove overall StatusCard from Dashboard
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
Labels: frontend

#1309 Add `api` to endpoints
  Clients/src/infrastructure/api/customAxios.ts
  Servers/index.ts
  Servers/swagger.yaml
Labels: frontend, backend

#1316 Create migration script for reporting
  Servers/database/migrations/20250508061148-update-enum_files_source-reporting.js
  Servers/models/file.model.ts
  Servers/utils/fileUpload.utils.ts
Labels: backend

#1325 Add migration script to create ISO 42001 structure
  Servers/database/migrations/20250502184633-create-structure-for-assessment-tracker.js
  Servers/database/migrations/20250502184712-create-structure-for-compliance-tracker.js
  Servers/database/migrations/20250508221800-add-ISO-42001-framework.js
  Servers/database/migrations/20250508222038-add-clauses-ISO-42001.js
  Servers/database/migrations/20250509022034-add-annex-ISO-42001.js
  Servers/structures/ISO-42001/annex/annex.struct.ts
  Servers/structures/ISO-42001/annex/annexcategories/05-organizational-policies-and-governance.annexcategory.ts
  Servers/structures/ISO-42001/clauses/clauses.struct.ts
  Servers/structures/ISO-42001/clauses/subclauses/04-context-of-organization.subclause.ts
  Servers/structures/ISO-42001/clauses/subclauses/05-leadership.subclause.ts
  Servers/tsconfig.json
Labels: backend

#1324 Sam 08 apr merge api routes into master
  Clients/src/infrastructure/api/customAxios.ts
  Servers/controllers/user.ctrl.ts
  Servers/index.ts
  Servers/swagger.yaml
Labels: frontend, backend

#1310 added very low risk in project risk for database migration
  .gitignore
  Clients/package-lock.json
  Servers/database/migrations/20250505161929-add_very_low_risk_to_risk_level_autocalculated.js
  Servers/models/projectRisk.model.ts
Labels: backend

#1334 fix: ensure all headers are allowed in CORS configuration
  Servers/index.ts
Labels: backend

#1304 Fix migration script
  Servers/database/migrations/20250502184525-create-table-for-frameworks.js
  Servers/database/migrations/20250502184633-create-structure-for-assessment-tracker.js
  Servers/database/migrations/20250502184712-create-structure-for-compliance-tracker.js
Labels: bug, backend

#1330 Update migration scripts and structure
  Servers/database/migrations/20250508222038-add-clauses-ISO-42001.js
  Servers/database/migrations/20250509022034-add-annex-ISO-42001.js
  Servers/models/ISO-42001/annexCategoryISO.model.ts
  Servers/models/ISO-42001/subClauseISO.model.ts
Labels: backend

#1332 Update file-source enum
  Servers/database/migrations/20250508061148-update-enum_files_source-reporting.js
Labels: backend

#1335 fix: update CORS allowedHeaders to specific values
  Servers/index.ts
Labels: backend

#1336 fix: add 'allowedHeaders' to CORS configuration for improved security
  Servers/index.ts
Labels: backend

#1337 Mo 130 may 10 iso modals
  Clients/src/presentation/components/Drawer/ClauseDrawerDialog/index.tsx
  Clients/src/presentation/pages/ISO/Clause/clause.structure.ts
  Clients/src/presentation/pages/ISO/Clause/index.tsx
  Clients/src/presentation/pages/index.tsx
Labels: frontend

#1339 Mo 131 may 11 annexes drawer form
  Clients/src/presentation/components/Drawer/AnnexDrawerDialog/index.tsx
  Clients/src/presentation/pages/ISO/Annex/index.tsx
Labels: frontend

#1321 Fix undefined subcontrols
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx
  Servers/controllers/eu.ctrl.ts
  Servers/utils/eu.utils.ts
Labels: bug, frontend, backend

#1342 fixed UI in Profile tab
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
Labels: enhancement, frontend

#1347 #1188 Refactor project risks calculation
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/projectRiskValue.ts
  Clients/src/presentation/components/RiskLevel/index.tsx
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
  Clients/src/presentation/tools/riskCalculator.ts
Labels: frontend

#1348 #1294 Create API endpoint to retrieve all risks across all vendors and projects
  Servers/controllers/vendorRisk.ctrl.ts
  Servers/routes/vendorRisk.route.ts
  Servers/utils/vendorRisk.util.ts
Labels: backend

#1349 Fix for create project
  Servers/utils/eu.utils.ts
Labels: bug, backend

#1350 Create ISO 42001 framework when creating project
  Servers/controllers/project.ctrl.ts
  Servers/database/db.ts
  Servers/utils/eu.utils.ts
  Servers/utils/iso42001.utils.ts
  Servers/utils/project.utils.ts
Labels: backend

#1352 Report generation bug fixed
  Servers/controllers/reporting.ctrl.ts
Labels: frontend, backend

#1353 Mo 132 may 12 ai implemented iso
  Clients/package-lock.json
  Clients/package.json
  Clients/src/presentation/pages/ISO/AiImplemented/AiGeneratedISO42001Annexes.tsx
  Clients/src/presentation/pages/ISO/AiImplemented/AiGeneratedISO42001Clauses.tsx
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
Labels: frontend

#1354 Report generate and remove fixed
  Servers/controllers/reporting.ctrl.ts
  Servers/utils/fileUpload.utils.ts
  Servers/utils/reporting.utils.ts
Labels: bug, frontend, backend

#1363 removing ai iso and fixing details
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlCategory.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/index.css
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/index.tsx
  Clients/src/presentation/pages/ISO/Annex/index.tsx
  Clients/src/presentation/pages/ISO/Clause/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/styles.ts
  Clients/src/presentation/vw-v2-components/Table/index.tsx
Labels: frontend

#1359 Add PATCH route for ISO 42001
  Servers/controllers/iso42001.ctrl.ts
  Servers/controllers/projectRisks.ctrl.ts
  Servers/database/migrations/20250514000706-add-file-sources-for-ISO42001.js
  Servers/index.ts
  Servers/models/file.model.ts
  Servers/routes/iso42001.route.ts
  Servers/routes/projectRisks.route.ts
  Servers/utils/fileUpload.utils.ts
  Servers/utils/iso42001.utils.ts
  Servers/utils/projectRisk.utils.ts
Labels: backend

#1361 Add DELETE routes for ISO
  Servers/controllers/iso42001.ctrl.ts
  Servers/routes/iso42001.route.ts
  Servers/utils/eu.utils.ts
  Servers/utils/iso42001.utils.ts
  Servers/utils/project.utils.ts
Labels: backend

#1366 fixed joyride tour in compliance tracker page
  Clients/src/App.tsx
  Clients/src/application/contexts/VerifyWise.context.ts
  Clients/src/application/interfaces/ComponentVisible.ts
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
Labels: enhancement, frontend

#1372 #1265 vendors new UI
  Clients/src/application/hooks/useVendorRisks.tsx
  Clients/src/domain/types/VendorRisk.ts
  Clients/src/presentation/components/Modals/NewRisk/index.tsx
  Clients/src/presentation/components/Table/RisksTable/index.tsx
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
Labels: frontend

#1369 Add GET routes for ISO
  Servers/controllers/iso42001.ctrl.ts
  Servers/package-lock.json
  Servers/package.json
  Servers/routes/iso42001.route.ts
  Servers/utils/iso42001.utils.ts
  Servers/validations/id.valid.ts
Labels: backend

#1373 Add autoDriver for ISO
  Servers/driver/autoDriver.driver.ts
  Servers/models/EU/answerEU.model.ts
  Servers/models/EU/controlEU.model.ts
  Servers/models/EU/subControlEU.model.ts
  Servers/models/ISO-42001/annexCategoryISO.model.ts
  Servers/models/ISO-42001/annexStructISO.model.ts
  Servers/models/ISO-42001/clauseStructISO.model.ts
  Servers/models/ISO-42001/subClauseISO.model.ts
  Servers/structures/ISO-42001/annex/annexcategories/05-organizational-policies-and-governance.annexcategory.ts
  Servers/structures/ISO-42001/annex/annexcategories/06-internal-organization.annexcategory.ts
  Servers/structures/ISO-42001/annex/annexcategories/07-resource-for-AI-systems.annexcategory.ts
  Servers/structures/ISO-42001/annex/annexcategories/08-AI-system-lifecycle.annexcategory.ts
  Servers/structures/ISO-42001/annex/annexcategories/09-data-for-AI-systems.annexcategory.ts
  Servers/structures/ISO-42001/annex/annexcategories/10-ict.annexcategory.ts
  Servers/structures/ISO-42001/annex/annexcategories/11-third-party-relationships.annexcategory.ts
  Servers/structures/ISO-42001/clauses/subclauses/04-context-of-organization.subclause.ts
  Servers/structures/ISO-42001/clauses/subclauses/05-leadership.subclause.ts
  Servers/structures/ISO-42001/clauses/subclauses/06-planning.subclause.ts
  Servers/structures/ISO-42001/clauses/subclauses/07-support.subclause.ts
  Servers/structures/ISO-42001/clauses/subclauses/08-operation.subclause.ts
  Servers/structures/ISO-42001/clauses/subclauses/09-performance-evaluation.subclause.ts
  Servers/structures/ISO-42001/clauses/subclauses/10-improvement.subclause.ts
  Servers/tsconfig.json
  Servers/types/status.type.ts
  Servers/utils/eu.utils.ts
  Servers/utils/iso42001.utils.ts
Labels: backend

#1371 Fix file upload issue
  Clients/src/domain/types/Question.ts
  Clients/src/presentation/components/Cards/ProjectCard/index.tsx
  Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/VWQuestion/index.tsx
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/index.tsx
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/questions.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/Overview/index.tsx
  Servers/controllers/eu.ctrl.ts
  Servers/controllers/file.ctrl.ts
  Servers/utils/eu.utils.ts
  Servers/utils/fileUpload.utils.ts
Labels: bug, backend

#1358 Login Issue
  Clients/src/App.tsx
  Clients/src/infrastructure/api/customAxios.ts
  Servers/utils/user.utils.ts
Labels: bug, backend

#1377 Add route to add framework to project
  Servers/controllers/framework.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/routes/frameworks.route.ts
  Servers/types/framework.type.ts
  Servers/utils/framework.utils.ts
  Servers/utils/project.utils.ts
Labels: backend

#1381 Fix: TabList Indicator Width
  Clients/src/presentation/pages/Vendors/style.ts
Labels: frontend

#1388 Add route to delete framework from project
  Servers/controllers/framework.ctrl.ts
  Servers/controllers/iso42001.ctrl.ts
  Servers/routes/frameworks.route.ts
  Servers/routes/iso42001.route.ts
  Servers/utils/framework.utils.ts
Labels: backend

#1389 Mo 135 may 17 integrating iso42001
  Clients/src/App.tsx
  Clients/src/application/hooks/useFrameworks.ts
  Clients/src/application/redux/getAuthToken.ts
  Clients/src/application/repository/clause_struct_iso.repository.ts
  Clients/src/application/repository/entity.repository.ts
  Clients/src/domain/interfaces/iRequestParams.ts
  Clients/src/domain/types/RootState.ts
  Clients/src/presentation/components/Drawer/ClauseDrawerDialog/index.tsx
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
  Clients/src/presentation/pages/ISO/Annex/index.tsx
  Clients/src/presentation/pages/ISO/Clause/index.tsx
  Clients/src/presentation/pages/ProjectView/AddNewFramework/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
  Servers/database/migrations/20250502184525-create-table-for-frameworks.js
  Servers/database/migrations/20250508221800-add-ISO-42001-framework.js
  Servers/endpoints-test/projects.http.test.rest
  Servers/routes/project.route.ts
Labels: backend

#1387 Push the images to GHCR
  .github/workflows/docker-image.yml
Labels: frontend, backend

#1392 Fix: TabIndicator Width Settings & Project Overview
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/style.ts
  Clients/src/presentation/pages/SettingsPage/style.ts
Labels: frontend

#1391 Fix the Evidences page
  Clients/src/application/hooks/useFetchProjects.ts
  Clients/src/application/hooks/useUserFilesMetaData.ts
  Clients/src/domain/types/File.ts
  Clients/src/presentation/components/Inputs/Dropdowns/ProjectFilter/ProjectFilterDropdown.tsx
  Clients/src/presentation/components/Table/FilesBasicTable/FileBasicTable.tsx
  Clients/src/presentation/pages/FileManager/index.tsx
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
Labels: frontend

#1394 Mo 136 may 18 integrating iso annexes
  Clients/src/application/repository/annex_struct_iso.repository.ts
  Clients/src/domain/types/AnnexCategoryISO.ts
  Clients/src/domain/types/AnnexCategoryStructISO.ts
  Clients/src/domain/types/AnnexStructISO.ts
  Clients/src/domain/types/ClauseStructISO.ts
  Clients/src/domain/types/Status.ts
  Clients/src/domain/types/SubClauseISO.ts
  Clients/src/domain/types/SubClauseStructISO.tsx
  Clients/src/presentation/pages/ISO/Annex/index.tsx
  Clients/src/presentation/pages/ISO/Clause/index.tsx
  Servers/routes/iso42001.route.ts
Labels: frontend, backend

#1390 Add an endpoint to get file data for all user projects
  Servers/controllers/file.ctrl.ts
  Servers/routes/file.route.ts
  Servers/utils/files/getUserFilesMetaData.utils.ts
Labels: backend

#1395 Fix add new project
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
  Servers/controllers/project.ctrl.ts
Labels: frontend, backend

#1397 403 error handling in generating reports
  Clients/src/application/tools/fileDownload.ts
  Clients/src/infrastructure/api/networkServices.ts
  Clients/src/infrastructure/exceptions/customeException.tsx
  Clients/src/presentation/components/Reporting/GenerateReport/DownloadReportFrom/index.tsx
  Clients/src/presentation/components/Reporting/GenerateReport/index.tsx
  Servers/controllers/reporting.ctrl.ts
Labels: frontend, backend

#1399 Mo 137 may 19 clauses update
  Clients/src/application/repository/subClause_iso.repository.ts
  Clients/src/presentation/components/Drawer/ClauseDrawerDialog/index.tsx
  Clients/src/presentation/pages/ISO/AiImplemented/AiGeneratedISO42001Annexes.tsx
  Clients/src/presentation/pages/ISO/AiImplemented/AiGeneratedISO42001Clauses.tsx
  Clients/src/presentation/pages/ISO/Clause/index.tsx
Labels: frontend, backend

#1351 Fixing Team and Password tabs bugs
  Clients/src/infrastructure/api/networkServices.ts
  Clients/src/presentation/pages/SettingsPage/Password/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
  Servers/controllers/user.ctrl.ts
Labels: bug

#1400 Fix compliance tracker calculations
  Servers/utils/eu.utils.ts
Labels: bug, backend

#1423 Mo 138 may 20 annexes update
  Clients/src/application/repository/annexCategory_iso.repository.ts
  Clients/src/application/repository/annex_struct_iso.repository.ts
  Clients/src/presentation/components/Drawer/AnnexDrawerDialog/index.tsx
  Clients/src/presentation/pages/ISO/Annex/index.tsx
  Clients/src/presentation/pages/ISO/Clause/index.tsx
  Servers/endpoints-test/iso42001.http.test.rest
Labels: frontend, backend

#1403 Feat: Vendors and Vendors Risks Report
  Servers/services/reportService.ts
Labels: backend

#1417 Add calculations endpoints for ISO
  Servers/controllers/eu.ctrl.ts
  Servers/controllers/iso42001.ctrl.ts
  Servers/routes/iso42001.route.ts
  Servers/utils/iso42001.utils.ts
Labels: backend

#1416 Change column name in users table from role to role_id
  Clients/src/App.tsx
  Clients/src/application/contexts/VerifyWise.context.ts
  Clients/src/application/hooks/useProjectData.tsx
  Clients/src/application/hooks/useProjectStatus.tsx
  Clients/src/application/hooks/useRegisterUser.tsx
  Clients/src/application/hooks/useUsers.tsx
  Clients/src/application/tools/extractToken.ts
  Clients/src/application/validations/formValidation.ts
  Clients/src/domain/interfaces/iUser.ts
  Clients/src/domain/interfaces/iWidget.ts
  Clients/src/domain/types/User.ts
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/Cards/ProjectCard/index.tsx
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/Drawer/ClauseDrawerDialog/index.tsx
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Modals/InviteUser/index.tsx
  Clients/src/presentation/components/Modals/NewRisk/index.tsx
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/components/ProjectCard/index.tsx
  Clients/src/presentation/components/Reporting/GenerateReport/index.tsx
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/components/Table/RisksTable/index.tsx
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/components/VWQuestion/index.tsx
  Clients/src/presentation/containers/Dashboard/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterUser/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/Overview/index.tsx
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
  Clients/src/presentation/vw-v2-components/Forms/ProjectForm/index.tsx
  Clients/src/presentation/vw-v2-components/Table/index.tsx
  Servers/controllers/user.ctrl.ts
  Servers/database/migrations/20250520134340-rename-role-column.js
  Servers/driver/autoDriver.driver.ts
  Servers/models/user.model.ts
  Servers/utils/user.utils.ts
Labels: frontend, backend

#1427 Implement Middleware for Role-Based Access
  Servers/controllers/user.ctrl.ts
  Servers/middleware/accessControl.middleware.ts
  Servers/scripts/resetDatabase.ts
  Servers/utils/user.utils.ts
Labels: backend

#1429 #1428 Add text ellipsis
  Clients/src/presentation/components/Inputs/Select/index.tsx
Labels: frontend

#1432 #1431: fix the wiggle in vendor risks
  Clients/src/presentation/components/Table/RisksTable/index.tsx
  Clients/src/presentation/pages/Vendors/index.tsx
Labels: frontend

#1436 Frameworks Management from Frameworks Tab
  Clients/src/presentation/pages/ProjectView/AddNewFramework/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/index.tsx
Labels: frontend

#1452 Remove unnecessary comments and clean up insertMockData function
  Servers/driver/autoDriver.driver.ts
Labels: backend

#1465 Add permissions to project risks
  Clients/src/application/constants/permissions.ts
  Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/RiskLevel/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/ProjectRisks/index.tsx
  Clients/src/presentation/vw-v2-components/Table/VWProjectRisksTableBody.tsx
  Clients/src/presentation/vw-v2-components/Table/VWProjectRisksTableHead.tsx
  Clients/src/presentation/vw-v2-components/Table/index.tsx
Labels: frontend

#1470 Add VerifyWise Admin user to team members in resetDatabase function
  Servers/scripts/resetDatabase.ts
Labels: backend

#1474 Add migration for creating organizations table
  Servers/database/migrations/20250527134337-create-organizations-table.js
Labels: backend

#1481 Add permissions to ISO 42001
  Clients/src/application/constants/permissions.ts
  Clients/src/presentation/components/Drawer/AnnexDrawerDialog/index.tsx
  Clients/src/presentation/components/Drawer/ClauseDrawerDialog/index.tsx
  Clients/src/presentation/components/Inputs/Checkbox/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
Labels: frontend

#1488 Add permissions to EU AI Act framework
  Clients/src/domain/interfaces/iWidget.ts
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/RichTextEditor/index.tsx
  Clients/src/presentation/components/VWQuestion/index.tsx
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/index.tsx
Labels: frontend

#1496 Fix console error and fix issue to show progress bar based on framework
  Clients/src/presentation/components/Cards/ProjectCard/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/Overview/index.tsx
  Clients/src/presentation/vw-v2-components/Buttons/index.tsx
Labels: frontend, backend

#1501 Mo 142 may 31 remove unused and duplications files
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/Cards/ProjectCard/index.tsx
  Clients/src/presentation/components/ComingSoonMessage/index.tsx
  Clients/src/presentation/components/Drawer/AnnexDrawerDialog/index.tsx
  Clients/src/presentation/components/Drawer/ClauseDrawerDialog/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/Modals/InviteUser/index.tsx
  Clients/src/presentation/components/Modals/NewRisk/index.tsx
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/components/ProtectedRoute/index.tsx
  Clients/src/presentation/components/Reporting/GenerateReport/GenerateReportFrom/index.tsx
  Clients/src/presentation/components/Reporting/GenerateReport/GenerateReportFrom/styles.ts
  Clients/src/presentation/components/Table/index.tsx
  Clients/src/presentation/components/VWQuestion/index.tsx
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/index.tsx
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/questions.tsx
  Clients/src/presentation/pages/Authentication/Login/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterUser/index.tsx
  Clients/src/presentation/pages/Authentication/SetNewPassword/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/index.tsx
  Clients/src/presentation/pages/FileManager/index.tsx
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
  Clients/src/presentation/pages/ProjectView/AddNewFramework/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/Overview/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/ProjectRisks/index.tsx
  Clients/src/presentation/pages/ProjectView/V1.0ProjectView/index.tsx
  Clients/src/presentation/pages/Reporting/GenerateReport/index.tsx
  Clients/src/presentation/pages/SettingsPage/Organization/index.tsx
  Clients/src/presentation/pages/SettingsPage/Password/index.tsx
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
  Clients/src/presentation/pages/StatusCodeHandling/StatusCodePage.tsx
  Clients/src/presentation/pages/StatusCodeHandling/index.md
  Clients/src/presentation/pages/StatusCodeHandling/statusCodes.ts
  Clients/src/presentation/pages/Vendors/index.tsx
  Clients/src/presentation/vw-v2-components/Alerts/index.tsx
  Clients/src/presentation/vw-v2-components/Buttons/index.tsx
  Clients/src/presentation/vw-v2-components/Dialogs/DualButtonModal/index.tsx
  Clients/src/presentation/vw-v2-components/Forms/ProjectForm/constants.ts
  Clients/src/presentation/vw-v2-components/Forms/ProjectForm/index.tsx
  Clients/src/presentation/vw-v2-components/Selects/Multi/index.tsx
  Clients/src/presentation/vw-v2-components/Skeletons/index.tsx
  Clients/src/presentation/vw-v2-components/Toast/index.tsx
Labels: enhancement, frontend
