Repository bluewave-labs/verifywise, pull requests merged in 2025-02, with the labels that each got.

#594 085 Jan 31: Add intermediate table for projects and vendors
  SQL_Commands.sql
  Servers/driver/autoDriver.driver.ts
  Servers/mocks/vendor.mock.data.ts
  Servers/mocks/vendorsProjects.mock.data.ts
  Servers/models/vendor.model.ts
  Servers/models/vendorsProjects.model.ts
  Servers/utils/autoDriver.util.ts
  Servers/utils/project.utils.ts
  Servers/utils/vendor.utils.ts
Labels: backend, team work and collaboration

#595 086 Jan 31: Send `assessment_id` when sending Projects
  Servers/swagger.yaml
  Servers/utils/project.utils.ts
Labels: backend

#597 081 feb 1 mailjet markup language
  Servers/package-lock.json
  Servers/package.json
  Servers/routes/user.route.ts
  Servers/services/emailService.ts
  Servers/templates/account-creation-email.mjml
  Servers/templates/password-reset-email.mjml
  Servers/tools/mjmlCompiler.ts
Labels: backend

#598 Gmail user pass added
  Servers/services/emailService.ts
Labels: backend

#599 082 feb 1 one time admin reg
  Clients/src/App.tsx
  Clients/src/application/repository/entity.repository.ts
  Clients/src/presentation/components/ProtectedRoute/index.tsx
Labels: enhancement, frontend, backend

#664 083 feb 2 VWMailer Service
  Servers/endpoints-test/vwmailer.http.rest
  Servers/index.ts
  Servers/routes/vwmailer.route.ts
  Servers/services/emailService.ts
Labels: backend

#675 088 Feb 3: Fix admin creation
  SQL_Commands.sql
  Servers/driver/autoDriver.driver.ts
  Servers/mocks/role.mock.data.ts
  Servers/mocks/users.data.ts
Labels: backend

#687 Register page changes
  Clients/src/application/validations/formValidation.ts
  Clients/src/presentation/pages/Authentication/Login/index.tsx
  Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
Labels: frontend

#690 Feat/feb 03 add create demo data
  Clients/src/App.tsx
  Clients/src/application/repository/entity.repository.ts
  Clients/src/presentation/components/CreateDemoData/index.tsx
  Clients/src/presentation/containers/Dashboard/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
  Clients/src/presentation/pages/index.tsx
Labels: frontend

#692 Save answers in assessment tracker
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
Labels: frontend, backend, team work and collaboration

#694 Bug fixed
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/containers/Dashboard/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
  Clients/src/presentation/pages/index.tsx
  Servers/endpoints-test/vwmailer.http.rest
Labels: bug, frontend

#695 Set dynamic assessmentIDon save assessment answers
  Clients/src/App.tsx
  Clients/src/application/contexts/VerifyWise.context.ts
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
Labels: frontend, backend

#697 Routing Protection
  Clients/src/App.tsx
  Clients/src/application/authentication/authSlice.ts
  Clients/src/presentation/components/ProtectedRoute/index.tsx
Labels: frontend

#698 089 Feb 4: Add surname to Users table
  Servers/swagger.yaml
  Servers/utils/user.utils.ts
Labels: bug, backend

#699 Fix create demo data process
  Clients/src/application/repository/entity.repository.ts
  Clients/src/presentation/pages/Home/index.tsx
Labels: bug, frontend

#700 Checking tables fixed
  Servers/database/db.ts
  Servers/index.ts
Labels: backend

#701 Add owners from backend in Project settings view
  Clients/src/presentation/components/Inputs/Select/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
Labels: frontend

#703 ProjectRisks & VendorRisks CRUD
  Clients/src/application/hooks/useProjectData.tsx
  Clients/src/application/hooks/useProjectRisks.tsx
  Clients/src/application/hooks/useVendorRisks.tsx
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
  Clients/src/presentation/pages/ProjectView/index.tsx
  Servers/controllers/projectRisks.ctrl.ts
  Servers/controllers/vendorRisk.ctrl.ts
  Servers/routes/projectRisks.route.ts
  Servers/routes/vendorRisk.route.ts
  Servers/utils/projectRisk.utils.ts
  Servers/utils/vendorRisk.util.ts
Labels: frontend, backend

#710 090 Feb 4: Add Email invitation
  .env
  Servers/Dockerfile
  Servers/routes/vwmailer.route.ts
  Servers/services/emailService.ts
  Servers/utils/jwt.util.ts
  docker-compose.yml
Labels: backend

#717 Loading data into fields
  Clients/src/application/hooks/useProjectRisks.tsx
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/interface.tsx
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
Labels: frontend, backend

#719 Dynamic user values and invitee role placeholder
  Clients/src/presentation/components/Modals/InviteUser/index.tsx
  Clients/src/presentation/pages/SettingsPage/Password/index.tsx
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
Labels: frontend

#720 085 fix crud bug
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
Labels: bug, frontend

#721 Created useUser hooks to fetch the users
  Clients/src/application/authentication/authSlice.ts
  Clients/src/application/hooks/useUsers.tsx
  Clients/src/application/repository/entity.repository.ts
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
  Clients/src/presentation/components/AddNewVendorRiskForm/index.tsx
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
Labels: frontend

#723 Feat/feb 06 change file upload component
  Clients/src/application/hooks/useProjectData.tsx
  Clients/src/presentation/components/FileUpload/FileUpload.styles.ts
  Clients/src/presentation/components/FileUpload/drop-file-input.css
  Clients/src/presentation/components/FileUpload/index.tsx
  Clients/src/presentation/components/FileUpload/types.ts
  Clients/src/presentation/components/Modals/FileUpload/index.tsx
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
Labels: frontend

#724 54 feb3 removing mock data
  Clients/src/presentation/components/RiskLevel/index.tsx
  Clients/src/presentation/components/RiskLevel/riskValues.ts
  Clients/src/presentation/mocks/assessmentTracker/assessmentTracker.data.ts
  Clients/src/presentation/mocks/compliance.data.ts
  Clients/src/presentation/mocks/complianceTracker/compliance.data.ts
  Clients/src/presentation/mocks/dashboard/create-project.data.ts
  Clients/src/presentation/mocks/dashboard/dashboard.data.ts
  Clients/src/presentation/mocks/dashboard/project.data.ts
  Clients/src/presentation/mocks/projects/project-add-new-risk-tab1.data.ts
  Clients/src/presentation/mocks/projects/project-add-new-risk-tab2.data.ts
  Clients/src/presentation/mocks/projects/project-overview.data.ts
  Clients/src/presentation/mocks/projects/project-risks.data.ts
  Clients/src/presentation/mocks/projects/project-vendor-risks.data.ts
  Clients/src/presentation/mocks/risks/risks.data.ts
  Clients/src/presentation/mocks/roles/roles.data.ts
  Clients/src/presentation/mocks/users/users.data.ts
  Clients/src/presentation/mocks/vendors/vendors.data.ts
  Clients/src/presentation/pages/Assessment/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
  Clients/src/presentation/pages/ProjectView/RisksView/riskkViewValues.ts
  Servers/controllers/control.ctrl.ts
  Servers/controllers/controlCategory.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/controllers/projectRisks.ctrl.ts
  Servers/controllers/projectScope.ctrl.ts
  Servers/controllers/question.ctrl.ts
  Servers/controllers/role.ctrl.ts
  Servers/controllers/subcontrol.ctrl.ts
  Servers/controllers/subtopic.ctrl.ts
  Servers/controllers/topic.ctrl.ts
  Servers/controllers/user.ctrl.ts
  Servers/controllers/vendor.ctrl.ts
  Servers/controllers/vendorRisk.ctrl.ts
  Servers/endpoints-test/projectRisk..http.test.rest
Labels: enhancement

#725 086 complaince tracker crud
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/Modals/Controlpane/paneInterfaces.ts
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
  Servers/controllers/control.ctrl.ts
  Servers/controllers/subcontrol.ctrl.ts
  Servers/endpoints-test/control.http.test.rest
  Servers/routes/control.route.ts
  Servers/utils/subControl.utils.ts
Labels: frontend, backend

#729 Replace mock user info in SideBar for fetched data.
  Clients/src/App.tsx
  Clients/src/application/constants/roles.ts
  Clients/src/application/contexts/VerifyWise.context.ts
  Clients/src/application/hooks/useUsers.tsx
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/pages/Authentication/Login/index.tsx
Labels: frontend

#734 091 Feb 4: Add an endpoint to get Assessment Tracker data
  Servers/controllers/assessment.ctrl.ts
  Servers/routes/assessment.route.ts
  Servers/swagger.yaml
  Servers/utils/question.utils.ts
  Servers/utils/subtopic.utils.ts
  Servers/utils/topic.utils.ts
Labels: backend

#735 092 Feb 6: Fix NGINX SPA Routing
  Clients/Dockerfile
  Clients/nginx.conf
Labels: bug, frontend, backend, team work and collaboration

#765 Enhancements
  Clients/src/application/repository/entity.repository.ts
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Inputs/Field/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/pages/Authentication/Login/index.tsx
Labels: bug, enhancement, frontend

#766 User detail update complete
  Clients/src/application/hooks/useProjectData.tsx
  Clients/src/application/repository/entity.repository.ts
  Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
  Servers/controllers/user.ctrl.ts
Labels: frontend

#770 093 Feb 7: Added `role` in email request body
  Servers/routes/vwmailer.route.ts
  Servers/utils/jwt.util.ts
Labels: frontend, backend, team work and collaboration

#771 094 Feb 7: Add empty Assessment and Compliance Tracker metadata
  Servers/controllers/assessment.ctrl.ts
  Servers/controllers/control.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/routes/assessment.route.ts
  Servers/routes/control.route.ts
  Servers/utils/assessment.utils.ts
  Servers/utils/control.utils.ts
  Servers/utils/controlCategory.util.ts
  Servers/utils/question.utils.ts
  Servers/utils/subControl.utils.ts
  Servers/utils/subtopic.utils.ts
  Servers/utils/topic.utils.ts
Labels: frontend, backend, team work and collaboration

#772 088 feb 7 complaice crud
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/Modals/Controlpane/paneInterfaces.ts
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/components/Table/AccordionTable/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
  Servers/controllers/control.ctrl.ts
  Servers/utils/control.utils.ts
  Servers/utils/controlCategory.util.ts
  Servers/utils/subControl.utils.ts
  Servers/utils/user.utils.ts
Labels: enhancement, frontend, backend

#774 090 dynamic compliance real data
  Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/Modals/Controlpane/paneInterfaces.ts
  Clients/src/presentation/components/Table/AccordionTable/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
  SQL_Commands.sql
  Servers/controllers/control.ctrl.ts
  Servers/controllers/controlCategory.ctrl.ts
  Servers/controllers/subcontrol.ctrl.ts
  Servers/index.ts
  Servers/routes/control.route.ts
  Servers/routes/controlCategory.route.ts
  Servers/utils/control.utils.ts
  Servers/utils/controlCategory.util.ts
  Servers/utils/subControl.utils.ts
Labels: frontend

#775 091 feb 10 restructure fe be
  Servers/structures/compliance-tracker/controlCategories.struct.ts
  Servers/structures/compliance-tracker/controls/01-ai-literacy.controls.ts
  Servers/structures/compliance-tracker/controls/02-transparency-provision.controls.ts
  Servers/structures/compliance-tracker/controls/03-human-oversight.controls.ts
  Servers/structures/compliance-tracker/controls/04-corrective-actions.controls.ts
  Servers/structures/compliance-tracker/controls/05-responsibilities.control.ts
  Servers/structures/compliance-tracker/controls/06-obligations-of-deployers.control.ts
  Servers/structures/compliance-tracker/controls/07-fundamental-rights.control.ts
  Servers/structures/compliance-tracker/controls/08-transparency-obligations-for-providers.control.ts
  Servers/structures/compliance-tracker/controls/09-registration.control.ts
  Servers/structures/compliance-tracker/controls/10-eu-database-for-high-risk.control.ts
  Servers/structures/compliance-tracker/controls/11-post-market-monitor-by-providers.control.ts
  Servers/structures/compliance-tracker/controls/12-report-serious-incidents.control.ts
  Servers/structures/compliance-tracker/controls/13-general-purpose-ai.control.ts
Labels: backend

#780 "Edit vendor" user list should be retrieved from db
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/pages/Authentication/ForgotPassword/index.tsx
  Clients/src/presentation/pages/Authentication/Login/index.tsx
  Clients/src/presentation/pages/Authentication/ResetPassword/index.tsx
Labels: enhancement, frontend, backend

#782 091 feb 10 restructure fe be
  Servers/structures/assessment-tracker/subtopics/01-project-scope.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/02-risk-management-system.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/03-data-governance.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/04-technical-documentation.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/05-record-keeping.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/06-transparency-user-information.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/07-human-oversight.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/08-accuracy-robustness-cybersecurity.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/09-conformity-assessment.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/10-post-market-monitoring.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/11-bias-monitoring-and-mitigation.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/12-accountability-and-governance.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/13-explainability.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/14-environmental-impact.subtopic.ts
  Servers/structures/assessment-tracker/topics.struct.ts
  Servers/structures/compliance-tracker/controlCategories.struct.ts
Labels: enhancement, backend, team work and collaboration

#784 Project name field removed from Add new risk modal. Only in UI
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
Labels: frontend

#785 093 feb 11 new mock data
  Servers/structures/new-mock-data/projects.mock.ts
Labels: backend

#786 094 feb 11 new models & refactors
  Servers/models/assessment.model.ts
  Servers/models/control.model.ts
  Servers/models/controlCategory.model.ts
  Servers/models/project.model.ts
  Servers/models/question.model.ts
  Servers/models/subcontrol.model.ts
  Servers/models/subtopic.model.ts
  Servers/models/topic.model.ts
Labels: enhancement, backend

#791 Feat/feb 11 add conditional rendering to complience and assessment tracker
  Clients/src/presentation/components/NoProject/NoProject.tsx
  Clients/src/presentation/pages/Assessment/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
  Clients/src/presentation/pages/Home/index.tsx
Labels: frontend

#792 Small changes
  Clients/src/application/validations/formValidation.ts
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
Labels: frontend

#798 Vendor and VendorRisk new structure added
  Servers/models/control.model.ts
  Servers/models/controlCategory.model.ts
  Servers/models/question.model.ts
  Servers/models/subcontrol.model.ts
  Servers/models/subtopic.model.ts
  Servers/models/topic.model.ts
  Servers/models/vendor.model.ts
  Servers/models/vendorRisk.model.ts
Labels: enhancement, backend

#801 095 Feb 11: Update Compliance Tracker and Assessment Tracker Structure
  SQL_Commands.sql
  Servers/controllers/assessment.ctrl.ts
  Servers/controllers/control.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/controllers/question.ctrl.ts
  Servers/controllers/subcontrol.ctrl.ts
  Servers/controllers/subtopic.ctrl.ts
  Servers/controllers/topic.ctrl.ts
  Servers/driver/autoDriver.driver.ts
  Servers/mocks/assessment.mock.data.ts
  Servers/mocks/control.mock.data.ts
  Servers/mocks/controlCategory.mock.data.ts
  Servers/mocks/project.mock.data.ts
  Servers/mocks/question.mock.data.ts
  Servers/mocks/subcontrol.mock.data.ts
  Servers/mocks/subtopic.mock.data.ts
  Servers/mocks/topic.mock.data.ts
  Servers/models/assessment.model.ts
  Servers/models/control.model.ts
  Servers/models/controlCategory.model.ts
  Servers/models/project.model.ts
  Servers/models/question.model.ts
  Servers/models/subcontrol.model.ts
  Servers/models/subtopic.model.ts
  Servers/models/topic.model.ts
  Servers/routes/assessment.route.ts
  Servers/routes/control.route.ts
  Servers/routes/question.route.ts
  Servers/structures/assessment-tracker/subtopics/02-risk-management-system.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/03-data-governance.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/04-technical-documentation.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/05-record-keeping.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/07-human-oversight.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/08-accuracy-robustness-cybersecurity.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/10-post-market-monitoring.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/11-bias-monitoring-and-mitigation.subtopic.ts
  Servers/structures/assessment-tracker/subtopics/13-explainability.subtopic.ts
  Servers/structures/compliance-tracker/controls/02-transparency-provision.controls.ts
  Servers/structures/compliance-tracker/controls/03-human-oversight.controls.ts
  Servers/structures/compliance-tracker/controls/04-corrective-actions.controls.ts
  Servers/structures/compliance-tracker/controls/07-fundamental-rights.control.ts
  Servers/swagger.yaml
  Servers/utils/assessment.utils.ts
  Servers/utils/control.utils.ts
  Servers/utils/controlCategory.util.ts
  Servers/utils/project.utils.ts
  Servers/utils/question.utils.ts
  Servers/utils/subControl.utils.ts
  Servers/utils/subtopic.utils.ts
  Servers/utils/topic.utils.ts
  Servers/utils/user.utils.ts
Labels: frontend, backend

#803 099 feb 15 new cards
  Clients/src/App.tsx
  Clients/src/presentation/components/Cards/StatsCard/index.tsx
  Clients/src/presentation/components/Cards/StatsCard/style.ts
  Clients/src/presentation/components/ProjectCard/ProgressBar/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
  Clients/src/presentation/pages/index.tsx
Labels: enhancement, frontend

#737 054: Add CI/CD
  .circleci/config.yml
Labels: enhancement, frontend, backend, team work and collaboration

#807 Small details for compliance tracker
  Clients/src/presentation/components/Cards/StatsCard/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
  Clients/src/presentation/pages/index.tsx
  Clients/src/presentation/vw-v2-components/Skeletons/index.tsx
Labels: frontend

#813 Add GitHub Actions
  .circleci/config.yml
  .github/workflows/docker-image.yml
Labels: enhancement, frontend, backend, team work and collaboration

#817 101 feb 17 assessment tracker reform
  Clients/src/App.tsx
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/index.style.ts
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/index.tsx
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/questions.tsx
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
  Clients/src/presentation/pages/index.tsx
  Servers/controllers/assessment.ctrl.ts
  Servers/controllers/project.ctrl.ts
  Servers/controllers/question.ctrl.ts
  Servers/controllers/subtopic.ctrl.ts
  Servers/controllers/topic.ctrl.ts
  Servers/endpoints-test/assessment.http.test.rest
  Servers/endpoints-test/project.http.test.rest
  Servers/endpoints-test/topic.http.test.rest
  Servers/routes/assessment.route.ts
  Servers/routes/project.route.ts
  Servers/routes/question.route.ts
  Servers/routes/subtopic.route.ts
  Servers/routes/topic.route.ts
  Servers/utils/assessment.utils.ts
  Servers/utils/control.utils.ts
  Servers/utils/project.utils.ts
  Servers/utils/projectRisk.utils.ts
  Servers/utils/projectScope.utils.ts
  Servers/utils/question.utils.ts
  Servers/utils/role.utils.ts
  Servers/utils/subControl.utils.ts
  Servers/utils/subtopic.utils.ts
  Servers/utils/topic.utils.ts
  Servers/utils/vendor.utils.ts
  Servers/utils/vendorRisk.util.ts
Labels: frontend, backend

#796 Fixed the error on the change Password page
  Clients/src/presentation/pages/SettingsPage/Password/index.tsx
Labels: frontend

#812 Create useAssessmentAnswers to fetch Assessment questions and answers.
  Clients/src/application/hooks/useAssessmentAnswers.tsx
  Clients/src/application/tools/alertUtils.ts
  Clients/src/presentation/components/AddNewVendorRiskForm/index.tsx
  Clients/src/presentation/components/Alert/index.tsx
  Clients/src/presentation/components/FileUpload/index.tsx
  Clients/src/presentation/components/FileUpload/types.ts
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/AssessmentItem/AssessmentItem.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/AssessmentQuestions/AssessmentQuestions.tsx
  Clients/src/presentation/pages/Assessment/index.tsx
  Clients/src/presentation/pages/Home/index.tsx
  Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
  Clients/src/presentation/pages/SettingsPage/Team/index.tsx
Labels: frontend

#819 Stepper component refactor
  Clients/src/presentation/components/Steps/ProgressStepper/index.tsx
Labels: enhancement

#820 Table component refactor
  Clients/src/presentation/components/Table/index.tsx
Labels: enhancement

#821 Answering questions
  Clients/src/App.tsx
  Clients/src/application/hooks/useAssessmentAnswers.tsx
  Clients/src/domain/Question.ts
  Clients/src/domain/Subtopic.ts
  Clients/src/presentation/components/Question/index.tsx
  Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/questions.tsx
  Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
  Servers/controllers/project.ctrl.ts
  Servers/controllers/question.ctrl.ts
  Servers/routes/question.route.ts
  Servers/utils/question.utils.ts
Labels: frontend

#816 096 Feb 18: Update Vendor and VendorRisk model
  .env
  SQL_Commands.sql
  Servers/controllers/vendor.ctrl.ts
  Servers/controllers/vendorRisk.ctrl.ts
  Servers/driver/autoDriver.driver.ts
  Servers/mocks/vendor.mock.data.ts
  Servers/mocks/vendorRisk.mock.data.ts
  Servers/models/vendor.model.ts
  Servers/models/vendorRisk.model.ts
  Servers/utils/project.utils.ts
  Servers/utils/vendor.utils.ts
  Servers/utils/vendorRisk.util.ts
Labels: backend

#827 103 feb 22 dynamic compliance
  Clients/src/App.tsx
  Clients/src/domain/ControlCategory.ts
  Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlCategory.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/index.css
  Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/index.tsx
  Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
  Clients/src/presentation/pages/index.tsx
  Servers/controllers/control.ctrl.ts
Labels: bug, enhancement, frontend, backend

#818 #753 - fix: show vendor risk level in vendors table
  .gitignore
  Clients/.gitignore
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Servers/.gitignore
Labels: bug, frontend

#851 104 feb 23 Removing unused components: part one
  Clients/src/App.tsx
  Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
  Clients/src/presentation/components/AddNewRiskForm/index.tsx
  Clients/src/presentation/components/AddNewVendorRiskForm/index.tsx
  Clients/src/presentation/components/Alert/index.tsx
  Clients/src/presentation/components/Avatar/VWAvatar/index.tsx
  Clients/src/presentation/components/Cards/StatsCard/index.tsx
  Clients/src/presentation/components/Checks/index.tsx
  Clients/src/presentation/components/CreateDemoData/index.tsx
  Clients/src/presentation/components/CreateProjectForm/index.tsx
  Clients/src/presentation/components/IconButton/index.tsx
  Clients/src/presentation/components/Inputs/Checkbox/index.tsx
  Clients/src/presentation/components/Inputs/Datepicker/index.tsx
  Clients/src/presentation/components/Inputs/Field/index.tsx
  Clients/src/presentation/components/Inputs/Select/index.tsx
  Clients/src/presentation/components/MetricSection/index.tsx
  Clients/src/presentation/components/Modals/Basic/index.tsx
  Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx
  Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
  Clients/src/presentation/components/Modals/Error/index.tsx
  Clients/src/presentation/components/Modals/FileUpload/index.tsx
  Clients/src/presentation/components/Modals/InviteUser/index.tsx
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Clients/src/presentation/components/NoProject/NoProject.tsx
  Clients/src/presentation/components/PageTour/CustomStep/index.tsx
  Clients/src/presentation/components/PageTour/index.tsx
  Clients/src/presentation/components/Popup/index.tsx
  Clients/src/presentation/components/ProjectCard/ProgressBar/index.tsx
  Clients/src/presentation/components/ProjectCard/index.tsx
  Clients/src/presentation/components/ProtectedRoute/index.tsx
  Clients/src/presentation/components/Question/index.tsx
  Clients/src/presentation/components/RichTextEditor/index.tsx
  Clients/src/presentation/components/RiskLevel/index.tsx
  Clients/src/presentation/components/Risks/index.tsx
  Clients/src/presentation/components/Sidebar/index.tsx
  Clients/src/presentation/components/Table/RisksTable/index.tsx
  Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
  Clients/src/presentation/components/Table/index.tsx
  Clients/src/presentation/components/TablePagination/index.tsx
Labels: enhancement, frontend

#853 105 feb 25 removing vendorRisks tab
  Clients/src/presentation/pages/ProjectView/Overview/index.tsx
  Clients/src/presentation/pages/ProjectView/index.tsx
Labels: frontend

#854 # 814 change table background color
  Clients/src/presentation/themes/tables.ts
Labels: frontend

#857 098 Feb 20: Add mock data for assessment and compliance trackers
  Servers/driver/autoDriver.driver.ts
  Servers/mocks/control.mock.data.ts
  Servers/mocks/controlCategory.mock.data.ts
  Servers/mocks/question.mock.data.ts
  Servers/mocks/subcontrol.mock.data.ts
  Servers/mocks/subtopic.mock.data.ts
  Servers/mocks/topic.mock.data.ts
  Servers/mocks/vendorRisk.mock.data.ts
  Servers/utils/project.utils.ts
Labels: backend

#824 097 Feb 20: Add demo flag in table for mock data
  SQL_Commands.sql
  Servers/driver/autoDriver.driver.ts
  Servers/mocks/users.data.ts
  Servers/utils/autoDriver.util.ts
Labels: backend

#864 105.5 feb 25 fix project card
  Clients/src/application/validations/stringValidation.ts
  Clients/src/presentation/components/Alert/index.tsx
  Clients/src/presentation/components/Cards/ProjectCard/style.ts
  Clients/src/presentation/pages/Home/1.0Home/index.tsx
  Clients/src/presentation/vw-v2-components/Forms/ProjectForm/index.tsx
  Clients/src/presentation/vw-v2-components/Forms/ProjectForm/style.ts
Labels: frontend, backend

#862 #814 sub: 2.1. Update create vendor to reflect API changes
  Clients/src/presentation/components/Modals/NewVendor/index.tsx
  Servers/utils/vendor.utils.ts
Labels: frontend, backend

#863 099 Feb 27: Add project ids when fetching vendors
  Servers/utils/vendor.utils.ts
Labels: backend

#865 105.5 feb 25 fix project card
  Clients/src/presentation/vw-v2-components/Forms/ProjectForm/index.tsx
Labels: frontend
